Repository erigontech/silkworm, pull requests merged in 2023-04, with the labels that each got.

#946 rpcdaemon: improve security in eth_getLogs code
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/log.hpp
  tests/integration/goerly/eth_getLogs/test_20.json
  tests/integration/goerly/eth_getLogs/test_22.json
Labels: security

#950 node: find + erase API in memory mutation
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation.hpp
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
  silkworm/node/db/memory_mutation_test.cpp
Labels: memory-mutation

#951 rpcdaemon: shorten method signatures with using directive
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/erigon_api.hpp
  silkworm/silkrpc/commands/erigon_api_test.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/net_api.cpp
  silkworm/silkrpc/commands/net_api.hpp
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/commands/parity_api.hpp
Labels: maintenance

#952 infra: add missing namespace to ThreadSafeQueue
  silkworm/infra/concurrency/containers.hpp
  silkworm/infra/concurrency/thread_safe_queue.hpp
  silkworm/node/bittorrent/client_test.cpp
Labels: maintenance

#958 node: fix MDBX map config for dupsort tables in KV Tx server-side call
  silkworm/node/backend/remote/rpc/kv_calls.cpp
Labels: maintenance

#955 rpcdaemon: add ots_getBlockTransactions API
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/types/block.cpp
  silkworm/silkrpc/types/block.hpp
  tests/integration/goerly/ots_getBlockDetails/test_01.json
  tests/integration/goerly/ots_getBlockDetailsByHash/test_1.json
  tests/integration/goerly/ots_getBlockTransactions/test_1.json
Labels: rpc-api

#965 node: refactor find + erase API in memory mutation
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation.hpp
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor.hpp
  silkworm/node/db/memory_mutation_test.cpp
  silkworm/node/db/tables.cpp
  silkworm/node/db/tables.hpp
Labels: memory-mutation

#966 rpcdaemon: remove duplicated table names
  silkworm/node/db/tables.hpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/core/account_dumper.cpp
  silkworm/silkrpc/core/account_walker.cpp
  silkworm/silkrpc/core/blocks.cpp
  silkworm/silkrpc/core/blocks_test.cpp
  silkworm/silkrpc/core/cached_chain_test.cpp
  silkworm/silkrpc/core/evm_debug_test.cpp
  silkworm/silkrpc/core/evm_trace_test.cpp
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
  silkworm/silkrpc/core/state_reader.cpp
  silkworm/silkrpc/core/state_reader_test.cpp
  silkworm/silkrpc/core/storage_walker.cpp
  silkworm/silkrpc/ethdb/kv/cached_database.cpp
  silkworm/silkrpc/ethdb/kv/cached_database_test.cpp
  silkworm/silkrpc/ethdb/kv/state_cache.cpp
  silkworm/silkrpc/ethdb/tables.hpp
  silkworm/silkrpc/ethdb/tables_test.cpp
  silkworm/silkrpc/stagedsync/stages.cpp
  silkworm/silkrpc/stagedsync/stages_test.cpp
Labels: rpcdaemon

#967 node: make memory mutation movable
  silkworm/node/db/memory_mutation.hpp
Labels: memory-mutation

#947 rpcdaemon: refactor DebugExecutor::execute methods
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
Labels: maintenance

#969 rpcdaemon: separate JSON conversion routines for Log type
  silkworm/silkrpc/json/log.cpp
  silkworm/silkrpc/json/log.hpp
  silkworm/silkrpc/json/log_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#970 rpcdaemon: add check on cbor input
  silkworm/silkrpc/ethdb/cbor.cpp
Labels: security

#972 rpcdaemon: use fully-qualified gRPC sentry namespace
  silkworm/sync/messages/inbound_block_bodies.cpp
  silkworm/sync/messages/inbound_block_bodies.hpp
  silkworm/sync/messages/inbound_block_headers.cpp
  silkworm/sync/messages/inbound_block_headers.hpp
  silkworm/sync/messages/inbound_get_block_bodies.cpp
  silkworm/sync/messages/inbound_get_block_bodies.hpp
  silkworm/sync/messages/inbound_get_block_headers.cpp
  silkworm/sync/messages/inbound_get_block_headers.hpp
  silkworm/sync/messages/inbound_message.cpp
  silkworm/sync/messages/inbound_message.hpp
  silkworm/sync/messages/inbound_new_block.cpp
  silkworm/sync/messages/inbound_new_block.hpp
  silkworm/sync/messages/inbound_new_block_hashes.cpp
  silkworm/sync/messages/inbound_new_block_hashes.hpp
  silkworm/sync/messages/outbound_get_block_bodies.cpp
  silkworm/sync/messages/outbound_get_block_headers.cpp
  silkworm/sync/messages/outbound_new_block.cpp
  silkworm/sync/messages/outbound_new_block.hpp
  silkworm/sync/messages/outbound_new_block_hashes.cpp
Labels: maintenance

#973 sync: fix stats loop termination for Sentry client when disconnected
  silkworm/sync/sentry_client.cpp
Labels: maintenance

#974 sync: avoid spurious stage iteration when starting w/ empty database
  silkworm/sync/sync_engine_pow.cpp
Labels: maintenance

#975 node: avoid explicit MDBX close when the RW transaction is still open
  cmd/silkworm.cpp
  silkworm/infra/concurrency/signal_handler.cpp
Labels: maintenance

#976 node: add snapshots subfolder in data directory structure
  silkworm/infra/common/directories.hpp
  silkworm/node/snapshot/path.hpp
  silkworm/node/snapshot/settings.hpp
  silkworm/node/snapshot/sync.cpp
Labels: snapshot-sync

#977 node: add subscriptions in BitTorrent client
  silkworm/node/bittorrent/client.cpp
  silkworm/node/bittorrent/client.hpp
  silkworm/node/bittorrent/client_test.cpp
Labels: snapshot-sync

#980 node: wait for snapshot download completion
  silkworm/node/bittorrent/client.cpp
  silkworm/node/snapshot/sync.cpp
Labels: snapshot-sync

#982 node: refactor memory overlay
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation.hpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
  silkworm/node/db/memory_mutation_test.cpp
Labels: memory-mutation

#986 node: move and rename test_context module
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/db/bitmap_test.cpp
  silkworm/node/db/buffer_test.cpp
  silkworm/node/db/genesis_test.cpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
  silkworm/node/etl/collector_test.cpp
  silkworm/node/snapshot/sync_test.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/stages/stage_bodies_test.cpp
  silkworm/node/stagedsync/stages/stage_headers_test.cpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
  silkworm/node/test/context.cpp
  silkworm/node/test/context.hpp
  silkworm/sync/internals/body_sequence_test.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
  silkworm/sync/messages/internal_message_test.cpp
Labels: maintenance

#987 node: add utility to set max file descriptors per process
  silkworm/node/backend/remote/backend_kv_server_test.cpp
  silkworm/node/common/os.cpp
  silkworm/node/common/os.hpp
  silkworm/node/common/os_test.cpp
  silkworm/node/test/os.hpp
Labels: maintenance

#989 node: improve memory mutation init
  silkworm/node/db/memory_mutation.cpp
Labels: maintenance

#995 rpcdaemon: add block times in erigon_forks
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/chain_config.hpp
Labels: shanghai

#996 silkworm: fix std::optional assignment
  cmd/silkworm.cpp
Labels: maintenance

#998 rpcdaemon: improve base64_encode utility
  silkworm/silkrpc/common/util.cpp
  silkworm/silkrpc/common/util.hpp
  silkworm/silkrpc/common/util_test.cpp
  silkworm/silkrpc/types/dump_account.cpp
Labels: maintenance

#1001 infra: rename rpc folder to grpc
  cmd/backend_kv_server.cpp
  cmd/common/settings.hpp
  cmd/sentry.cpp
  cmd/silkworm.cpp
  cmd/test/backend_kv_test.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/infra/concurrency/context_pool_settings.hpp
  silkworm/infra/grpc/client/call.cpp
  silkworm/infra/grpc/client/call.hpp
  silkworm/infra/grpc/client/call_test.cpp
  silkworm/infra/grpc/common/completion_tag.hpp
  silkworm/infra/grpc/common/conversion.cpp
  silkworm/infra/grpc/common/conversion.hpp
  silkworm/infra/grpc/common/conversion_test.cpp
  silkworm/infra/grpc/common/util.hpp
  silkworm/infra/grpc/common/util_test.cpp
  silkworm/infra/grpc/interfaces/types.cpp
  silkworm/infra/grpc/interfaces/types.hpp
  silkworm/infra/grpc/server/call.hpp
  silkworm/infra/grpc/server/call_test.cpp
  silkworm/infra/grpc/server/server.hpp
  silkworm/infra/grpc/server/server_config.cpp
  silkworm/infra/grpc/server/server_config.hpp
  silkworm/infra/grpc/server/server_config_test.cpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/infra/grpc/server/server_context_pool.hpp
  silkworm/infra/grpc/server/server_context_pool_test.cpp
  silkworm/infra/grpc/server/server_test.cpp
  silkworm/infra/grpc/server/wait_strategy.cpp
  silkworm/infra/grpc/server/wait_strategy.hpp
  silkworm/infra/grpc/server/wait_strategy_test.cpp
  silkworm/node/backend/remote/backend_kv_server.hpp
  silkworm/node/backend/remote/backend_kv_server_test.cpp
  silkworm/node/backend/remote/rpc/backend_calls.cpp
  silkworm/node/backend/remote/rpc/backend_calls.hpp
  silkworm/node/backend/remote/rpc/kv_calls.cpp
  silkworm/node/backend/remote/rpc/kv_calls.hpp
  silkworm/node/backend/state_change_collection.cpp
  silkworm/node/backend/state_change_collection_test.cpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/sentry/peer_manager.hpp
  silkworm/sentry/rlpx/server.hpp
  silkworm/sentry/rpc/client/sentry_client.cpp
  silkworm/sentry/rpc/interfaces/peer_id.cpp
  silkworm/sentry/rpc/interfaces/status_data.cpp
  silkworm/sentry/rpc/server/server.cpp
  silkworm/sentry/rpc/server/server.hpp
  silkworm/sentry/rpc/server/server_calls.hpp
  silkworm/sentry/sentry.hpp
  silkworm/silkrpc/ethdb/kv/state_cache.cpp
  silkworm/silkrpc/ethdb/kv/state_cache_test.cpp
  silkworm/sync/internals/sentry_type_casts.hpp
Labels: maintenance

#1000 node: snapshot full download
  cmd/silkworm.cpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/snapshot/path.hpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
Labels: snapshot-sync

#992 core: Basic validation of EIP-4844 transactions
  cmd/test/consensus.cpp
  silkworm/core/chain/protocol_param.hpp
  silkworm/core/consensus/base/engine.cpp
  silkworm/core/consensus/base/engine.hpp
  silkworm/core/consensus/engine.cpp
  silkworm/core/consensus/engine.hpp
  silkworm/core/consensus/engine_test.cpp
  silkworm/core/consensus/pos/engine_test.cpp
  silkworm/core/consensus/validation.hpp
  silkworm/core/crypto/kzg.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/silkrpc/common/util_test.cpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/transaction_test.cpp
  silkworm/sync/internals/body_sequence.cpp
  silkworm/sync/sync_engine_pos.cpp
Labels: cancun

#1003 node: avoid tweaking max connections in BitTorrent client
  silkworm/node/bittorrent/client.cpp
Labels: snapshot-sync

#1004 node: increase KV Tx TTL timeout to reduce the chance of flaky unit test
  silkworm/node/backend/remote/backend_kv_server_test.cpp
Labels: maintenance

#1005 node: make snapshot downloading and index building stoppable at boundaries
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/memory_mapped_file.hpp
  silkworm/node/snapshot/index.hpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
Labels: snapshot-sync

#1010 rpcdaemon: cleanup EVM executor
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/core/evm_executor_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
Labels: maintenance

#1016 node: build snapshot indexes in parallel
  cmd/silkworm.cpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/huffman/decompressor_test.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/index.hpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/snapshot/sync.cpp
Labels: snapshot-sync

#1012 rpcdaemon: change constants representation
  silkworm/silkrpc/concurrency/context_pool.cpp
  silkworm/silkrpc/concurrency/context_pool.hpp
  silkworm/silkrpc/core/filter_storage.hpp
Labels: maintenance

#1017 rpcdaemon: add unit tests for json receipt
  silkworm/silkrpc/json/receipt_test.cpp
Labels: maintenance

#1019 node: rename rpc folder to grpc
  silkworm/node/backend/remote/backend_kv_server.cpp
  silkworm/node/backend/remote/backend_kv_server_test.cpp
  silkworm/node/backend/remote/grpc/backend_calls.cpp
  silkworm/node/backend/remote/grpc/backend_calls.hpp
  silkworm/node/backend/remote/grpc/kv_calls.cpp
  silkworm/node/backend/remote/grpc/kv_calls.hpp
  silkworm/node/backend/remote/grpc/kv_calls_test.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/silkrpc/ethdb/file/local_cursor.cpp
Labels: maintenance

#1020 node: add snapshot namespace
  cmd/common/settings.hpp
  cmd/common/snapshot_options.cpp
  cmd/common/snapshot_options.hpp
  cmd/silkworm.cpp
  cmd/snapshots.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/index.hpp
  silkworm/node/snapshot/index_test.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/path.hpp
  silkworm/node/snapshot/path_test.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/settings.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
  silkworm/node/snapshot/sync_test.cpp
  silkworm/node/test/context.cpp
  silkworm/node/test/context.hpp
  silkworm/node/test/snapshots.hpp
Labels: maintenance

#1021 rpcdaemon: admin_nodeInfo and admin_peers implementation
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/admin_api.cpp
  silkworm/silkrpc/commands/admin_api.hpp
  silkworm/silkrpc/commands/rpc_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/commands/rpc_api_table.hpp
  silkworm/silkrpc/common/constants.hpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  tests/integration/goerly/admin_nodeInfo/test_1.json
  tests/integration/goerly/admin_peers/test_1.json
Labels: rpc-api

#1011 infra: separation between concurrency::ContextPool and rpc::ServerContextPool
  cmd/common/common.cpp
  silkworm/infra/concurrency/context_pool.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/context_pool_settings.hpp
  silkworm/infra/concurrency/context_pool_test.cpp
  silkworm/infra/concurrency/idle_strategy.cpp
  silkworm/infra/concurrency/idle_strategy.hpp
  silkworm/infra/concurrency/idle_strategy_test.cpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/infra/grpc/server/server_context_pool.hpp
  silkworm/infra/grpc/server/server_context_pool_test.cpp
Labels: maintenance

#1027 cmd: test/ethereum should only depend on infra, not node
  cmd/test/CMakeLists.txt
Labels: maintenance

#1031 infra: cleanup and move OS utilities
  cmd/silkworm.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/memory_mapped_file.hpp
  silkworm/infra/common/memory_mapped_file_test.cpp
  silkworm/infra/common/os.cpp
  silkworm/infra/common/os.hpp
  silkworm/infra/common/os_test.cpp
  silkworm/node/backend/remote/backend_kv_server_test.cpp
Labels: snapshot-sync, maintenance

#1034 rpcdaemon: add ots_getContractCreator
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/rpc_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/ots_getContractCreator/test_01.json
  tests/integration/goerly/ots_getContractCreator/test_02.json
Labels: rpc-api

#1035 node: add recheck capability in BitTorrent client
  silkworm/node/bittorrent/client.cpp
  silkworm/node/bittorrent/client.hpp
  silkworm/node/bittorrent/client_test.cpp
  silkworm/node/bittorrent/settings.hpp
Labels: snapshot-sync
