Repository erigontech/silkworm, pull requests merged in 2023-02, with the labels that each got.

#856 node: refactor Bittorrent client
  cmd/snapshots.cpp
  node/silkworm/bittorrent/bittorrent_client.cpp
  node/silkworm/bittorrent/bittorrent_client.hpp
  node/silkworm/bittorrent/bittorrent_client_test.cpp
Labels: snapshot-sync

#859 node: move decompressor into dedicated package
  node/silkworm/huffman/decompressor.cpp
  node/silkworm/huffman/decompressor.hpp
  node/silkworm/huffman/decompressor_test.cpp
  node/silkworm/snapshot/index.hpp
  node/silkworm/snapshot/snapshot.hpp
Labels: maintenance

#867 node: fix Tx RPC unit tests
  node/silkworm/backend/backend_kv_server_test.cpp
  node/silkworm/backend/rpc/kv_calls.cpp
  node/silkworm/backend/rpc/kv_calls.hpp
  node/silkworm/db/mdbx.cpp
  node/silkworm/db/mdbx.hpp
Labels: maintenance

#872 node: make test fail if max per-process descriptors are insufficient
  node/silkworm/backend/backend_kv_server_test.cpp
  node/silkworm/test/os.hpp
Labels: maintenance

#873 Add args accumulation in logging facility
  node/silkworm/common/log.cpp
  node/silkworm/common/log.hpp
  node/silkworm/common/log_test.cpp
Labels: maintenance

#876 Refactor BitTorrent client
  cmd/snapshots.cpp
  node/silkworm/bittorrent/client.cpp
  node/silkworm/bittorrent/client.hpp
  node/silkworm/bittorrent/client_test.cpp
  node/silkworm/bittorrent/settings.hpp
  node/silkworm/snapshot/settings.hpp
Labels: snapshot-sync

#879 Cleanup node unit tests
  silkworm/node/common/test_context.cpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/db/buffer_test.cpp
  silkworm/node/downloader/internals/header_chain_test.cpp
  silkworm/node/etl/collector_test.cpp
  silkworm/node/rpc/server/call_test.cpp
  silkworm/node/rpc/server/server_config_test.cpp
  silkworm/node/rpc/server/server_context_pool_test.cpp
  silkworm/node/rpc/server/server_test.cpp
  silkworm/node/stagedsync/_test.cpp
  silkworm/node/stagedsync/stage_history_index_test.cpp
  silkworm/node/test/log.hpp
Labels: maintenance

#880 Small cleanups in RPC calls
  cmd/test/backend_kv_test.cpp
  silkworm/node/rpc/server/call.hpp
  silkworm/node/rpc/server/call_test.cpp
Labels: maintenance

#881 Fix status badge for GitHub Actions
  README.md
Labels: maintenance

#888 Skip server RPC test counting instances
  silkworm/node/rpc/server/call_test.cpp
Labels: maintenance

#894 Move Hash to core
  silkworm/core/types/hash.hpp
  silkworm/node/downloader/internals/types.hpp
  silkworm/node/rpc/interfaces/types.hpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/sync.cpp
Labels: maintenance

#896 Restore format compliance
  silkworm/node/downloader/block_exchange.hpp
  silkworm/node/downloader/internals/body_sequence.cpp
  silkworm/node/downloader/internals/header_chain.cpp
  silkworm/node/downloader/internals/header_chain_test.cpp
  silkworm/node/downloader/messages/inbound_new_block_hashes.cpp
  silkworm/node/downloader/messages/outbound_get_block_bodies.cpp
  silkworm/node/downloader/messages/outbound_message.cpp
Labels: maintenance

#893 PoS syncing
  cmd/silkworm.cpp
  silkworm/node/downloader/engine_apis/structs.cpp
  silkworm/node/downloader/engine_apis/structs.hpp
  silkworm/node/downloader/internals/header_chain_plus_exec_test.cpp
  silkworm/node/downloader/internals/header_chain_test.cpp
  silkworm/node/downloader/sync_engine_pos.cpp
  silkworm/node/downloader/sync_engine_pos.hpp
  silkworm/node/downloader/sync_engine_pow.cpp
  silkworm/node/downloader/sync_engine_pow.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
Labels: pos-sync
