Repository erigontech/silkworm, pull requests merged in 2023-11, with the labels that each got.

#1593 sdk: sentry API
  cmd/sentry.cpp
  cmd/silkworm.cpp
  conanfile.py
  silkworm/api/CMakeLists.txt
  silkworm/api/handle.hpp
  silkworm/api/sentry.cpp
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
  silkworm/infra/concurrency/awaitable_future_test.cpp
  silkworm/infra/concurrency/sync_wait_test.cpp
  silkworm/sentry/common/enode_url.cpp
  silkworm/sentry/common/enode_url.hpp
  silkworm/sentry/nat/nat_option.cpp
  silkworm/sentry/nat/nat_option.hpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/sentry.hpp
  silkworm/sentry/settings.hpp
Labels: c-api

#1628 conan: fix Windows build and upgrade to 1.60.2 for macOS
  .circleci/config.yml
  .github/workflows/macOS.yml
  .github/workflows/windows.yml
  README.md
  conanfile.py
Labels: maintenance

#1617 rpcdaemon: improve debug_traceBlockByNumber performance
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/json/stream.cpp
  silkworm/silkrpc/json/stream.hpp
  silkworm/silkrpc/json/stream_test.cpp
  silkworm/silkrpc/types/writer.cpp
  silkworm/silkrpc/types/writer.hpp
  silkworm/silkrpc/types/writer_test.cpp
Labels: enhancement

#1629 fix macOS build error due to std::to_chars not available
  CMakeLists.txt
  cmake/toolchain/cxx20.cmake
Labels: maintenance

#1630 core: support code rewrite in Bor
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_test.cpp
  silkworm/core/chain/genesis_mumbai.cpp
  silkworm/core/chain/genesis_mumbai.json
  silkworm/core/common/base.hpp
  silkworm/core/common/small_map.hpp
  silkworm/core/common/small_map_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/base_rule_set.hpp
  silkworm/core/protocol/bor_config.cpp
  silkworm/core/protocol/bor_config.hpp
  silkworm/core/protocol/bor_config_test.cpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/clique_rule_set.cpp
  silkworm/core/protocol/clique_rule_set.hpp
  silkworm/core/protocol/clique_rule_set_test.cpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/merge_rule_set.hpp
  silkworm/core/protocol/param.hpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
Labels: polygon

#1640 api: fix crash in silkworm_add_snapshot after PR 1593
  silkworm/api/silkworm_api.cpp
Labels: maintenance, c-api

#1638 rpcdaemon: fix accessList field name in JSON glaze
  silkworm/silkrpc/json/block.cpp
Labels: maintenance

#1639 rpcdaemon: fix wrong dump of stack entries in DebugTracer
  silkworm/silkrpc/core/evm_debug.cpp
Labels: maintenance

#1641 cmd: simplify command line of execute tool to build indexes
  cmd/api/execute.cpp
Labels: snapshots, maintenance

#1632 sentry: fix co_await Operation canceled crash (#1530)
  silkworm/infra/concurrency/co_spawn_sw.hpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.hpp
Labels: maintenance

#1643 node: in-memory ETL collector
  silkworm/node/etl/in_memory_collector.hpp
  silkworm/node/etl/in_memory_collector_test.cpp
Labels: enhancement

#1642 cmd: fix init in block execution tool
  cmd/api/execute.cpp
Labels: c-api

#1650 node: avoid ASAN error in memory ETL collector
  silkworm/node/etl/in_memory_collector.hpp
Labels: maintenance

#1646 core: schedule Agra hardfork on Polygon mainnet
  silkworm/core/chain/config.cpp
  silkworm/core/chain/genesis_polygon.cpp
  silkworm/core/chain/genesis_polygon.json
  silkworm/core/protocol/bor_config.cpp
  silkworm/core/protocol/bor_config.hpp
  silkworm/core/protocol/bor_config_test.cpp
Labels: polygon

#1651 core: add missing hooks in EVM tracer for block and self-destruct
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/execution_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
  silkworm/silkrpc/core/evm_trace_test.cpp
Labels: maintenance

#1633 rpcdaemon: CBOR decode must be ok when encoded value is null
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain.hpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
  silkworm/silkrpc/core/receipts.cpp
  silkworm/silkrpc/ethdb/cbor.cpp
Labels: maintenance

#1655 core: empty virtual hooks in EVM tracer
  silkworm/core/execution/call_tracer.hpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/execution_test.cpp
  silkworm/silkrpc/core/evm_access_list_tracer.hpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_trace.hpp
Labels: maintenance

#1654 infra: treat clang-tidy warnings as errors
  cmd/common/shutdown_signal.hpp
  silkworm/core/common/random_number.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/trie/prefix_set_test.cpp
  silkworm/infra/CMakeLists.txt
  silkworm/infra/common/asio_timer.hpp
  silkworm/infra/common/log_test.cpp
  silkworm/infra/common/mem_usage.cpp
  silkworm/infra/common/mem_usage.hpp
  silkworm/infra/concurrency/async_thread.cpp
  silkworm/infra/concurrency/awaitable_condition_variable.cpp
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/infra/concurrency/awaitable_future_test.cpp
  silkworm/infra/concurrency/channel.hpp
  silkworm/infra/concurrency/co_spawn_sw.hpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/event_notifier.hpp
  silkworm/infra/concurrency/parallel_group_test.cpp
  silkworm/infra/concurrency/parallel_group_utils.cpp
  silkworm/infra/concurrency/parallel_group_utils.hpp
  silkworm/infra/concurrency/sync_wait_test.cpp
  silkworm/infra/concurrency/task_group.cpp
  silkworm/infra/concurrency/task_group.hpp
  silkworm/infra/concurrency/task_group_test.cpp
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/concurrency/timeout_test.cpp
  silkworm/infra/grpc/client/client_context_pool_test.cpp
  silkworm/infra/grpc/server/server_context_pool_test.cpp
  silkworm/node/common/resource_usage.cpp
  silkworm/sentry/api/router/messages_call.hpp
  silkworm/sentry/api/router/peer_call.hpp
  silkworm/sentry/api/router/peer_events_call.hpp
  silkworm/sentry/api/router/send_message_call.hpp
  silkworm/sentry/common/socket_stream.hpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/discovery/disc_v4/discovery.hpp
  silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite.hpp
  silkworm/sentry/discovery/node_db/serial_node_db.hpp
  silkworm/sentry/message_receiver.hpp
  silkworm/sentry/message_sender.hpp
  silkworm/sentry/peer_discovery_feedback.hpp
  silkworm/sentry/peer_manager.hpp
  silkworm/sentry/peer_manager_api.hpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/rlpx/peer.hpp
  silkworm/sentry/rlpx/server.cpp
  silkworm/sentry/rlpx/server.hpp
  silkworm/sentry/status_manager.hpp
  silkworm/sync/sentry_client.cpp
  silkworm/sync/sentry_client.hpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1653 rpcdaemon: refactor glaze common methods
  silkworm/silkrpc/json/glaze.cpp
  silkworm/silkrpc/json/glaze.hpp
  silkworm/silkrpc/json/glaze_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1658 rpcdaemon: fix JSON stream serialization for DebugLog::error
  silkworm/silkrpc/core/evm_debug.cpp
Labels: maintenance

#1662 rpcdaemon: add check for block not found
  silkworm/silkrpc/core/gas_price_oracle.cpp
Labels: maintenance

#1661 cmd: add compare subcommand to db toolbox
  cmd/dev/snapshots.cpp
  cmd/dev/toolbox.cpp
Labels: enhancement

#1664 cmd: fix gcc 11 compilation for operator== in toolbox
  cmd/dev/toolbox.cpp
Labels: maintenance

#1663 node: fix some clang-tidy warnings
  .clang-tidy
  silkworm/infra/common/log_test.cpp
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/node/backend/remote/grpc/kv_calls.cpp
  silkworm/node/db/bitmap.cpp
  silkworm/node/db/bitmap.hpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/eth_status_data_provider.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/etl/util.cpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/node.cpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/snapshot/index.hpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/local_client.cpp
  silkworm/node/stagedsync/stages/stage_bodies.hpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_cursor.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/sentry/api/common/peer_event.hpp
Labels: maintenance

#1634 c api: refactor SilkwormHandle
  cmd/api/execute.cpp
  silkworm/api/instance.hpp
  silkworm/api/sentry.cpp
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
Labels: maintenance, c-api

#1670 rpcdaemon: improve readability for trace_block tracing config
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1666 rpcdaemon: avoid call for precompile in trace API
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/core/evm_trace_test.cpp
Labels: maintenance

#1669 cmd: diff paging in compare command of db toolbox
  cmd/dev/toolbox.cpp
Labels: maintenance

#1672 rpcdaemon: avoid unsolicited wrong HTTP reply in JSON streaming
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/request_handler.hpp
Labels: maintenance

#1673 cmd: add option to compare table in db toolbox
  cmd/dev/CMakeLists.txt
  cmd/dev/db_toolbox.cpp
Labels: enhancement

#1671 node: treat clang-tidy warnings as errors
  .clang-tidy
  silkworm/infra/concurrency/async_thread.cpp
  silkworm/infra/concurrency/awaitable_condition_variable.cpp
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/infra/concurrency/awaitable_future_test.cpp
  silkworm/infra/concurrency/parallel_group_test.cpp
  silkworm/infra/concurrency/parallel_group_utils.cpp
  silkworm/infra/concurrency/sync_wait_test.cpp
  silkworm/infra/concurrency/task_group.cpp
  silkworm/infra/concurrency/task_group_test.cpp
  silkworm/infra/concurrency/thread_pool.hpp
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/concurrency/timeout_test.cpp
  silkworm/node/CMakeLists.txt
  silkworm/node/backend/remote/grpc/kv_calls.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/util.hpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/local_client.cpp
  silkworm/node/stagedsync/server.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_cursor.cpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/sync/sync_pow.cpp
Labels: maintenance

#1676 Fix clang-tidy issues on Recsplit (and macos build)
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/snapshot/index.hpp
  silkworm/silkrpc/test/api_test_database.hpp
Labels: maintenance

#1678 rpcdaemon: read_transaction_by_hash improvement
  silkworm/silkrpc/core/cached_chain.cpp
Labels: maintenance

#1674 rpcdaemon: RPC request ID management
  silkworm/silkrpc/commands/admin_api.cpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/net_api.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/commands/txpool_api.cpp
  silkworm/silkrpc/commands/web3_api.cpp
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/request_handler.hpp
  silkworm/silkrpc/json/block.cpp
  silkworm/silkrpc/json/block.hpp
  silkworm/silkrpc/json/call.cpp
  silkworm/silkrpc/json/call.hpp
  silkworm/silkrpc/json/glaze.cpp
  silkworm/silkrpc/json/glaze.hpp
  silkworm/silkrpc/json/log.cpp
  silkworm/silkrpc/json/log.hpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1680 snapshots: refactor recsplit strategy files
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/recsplit/rec_split_par.hpp
  silkworm/node/recsplit/rec_split_par_test.cpp
  silkworm/node/recsplit/rec_split_seq.hpp
  silkworm/node/recsplit/rec_split_seq_test.cpp
  silkworm/node/snapshot/index.cpp
Labels: snapshots, maintenance

#1675 More clang-tidy checks
  .clang-tidy
  cmd/capi/execute.cpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/common/lru_cache.hpp
  silkworm/core/common/small_map.hpp
  silkworm/core/common/util.cpp
  silkworm/core/common/util.hpp
  silkworm/core/crypto/blake2b.c
  silkworm/core/crypto/rmd160.c
  silkworm/core/crypto/sha256.c
  silkworm/core/rlp/decode_vector.hpp
  silkworm/core/rlp/encode_vector.hpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/memory_mapped_file.hpp
  silkworm/infra/common/memory_mapped_file_test.cpp
  silkworm/infra/common/os.cpp
  silkworm/infra/common/secp256k1_context.hpp
  silkworm/infra/concurrency/awaitable_condition_variable.cpp
  silkworm/infra/concurrency/awaitable_future_test.cpp
  silkworm/infra/concurrency/awaitable_wait_for_one.hpp
  silkworm/infra/concurrency/channel.hpp
  silkworm/infra/concurrency/co_spawn_sw.hpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/coroutine_test.cpp
  silkworm/infra/concurrency/idle_strategy_test.cpp
  silkworm/infra/concurrency/parallel_group_utils.cpp
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/grpc/server/server.hpp
  silkworm/infra/grpc/server/server_test.cpp
  silkworm/node/common/resource_usage.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/prune_mode.cpp
  silkworm/node/recsplit/encoding/elias_fano.hpp
  silkworm/node/recsplit/encoding/golomb_rice.hpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/recsplit/rec_split_par.hpp
  silkworm/node/recsplit/rec_split_par_test.cpp
  silkworm/node/recsplit/rec_split_seq_test.cpp
  silkworm/node/recsplit/support/common.hpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_cursor.cpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.cpp
  silkworm/sentry/discovery/node_db/node_db.hpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/session_sentry_client.cpp
  silkworm/silkrpc/core/call_many.hpp
  silkworm/silkrpc/core/evm_access_list_tracer.hpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/types/writer.cpp
Labels: maintenance
