Repository erigontech/silkworm, pull requests merged in 2023-10, with the labels that each got.

#1552 core: Polygon genesis allocation
  cmd/dev/toolbox.cpp
  cmd/state-transition/state_transition.cpp
  cmd/test/ethereum.cpp
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/chain/genesis.hpp
  silkworm/core/chain/genesis_mumbai.cpp
  silkworm/core/chain/genesis_mumbai.json
  silkworm/core/chain/genesis_polygon.cpp
  silkworm/core/chain/genesis_polygon.json
  silkworm/core/chain/genesis_test.cpp
  silkworm/core/common/hash_maps.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/rule_set.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/state/in_memory_state.hpp
  silkworm/core/state/state.hpp
  silkworm/node/db/genesis.cpp
  silkworm/node/db/genesis.hpp
  silkworm/node/db/genesis_test.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
Labels: polygon

#1565 api: add progress info to periodic execution log
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
  silkworm/infra/common/log.hpp
  silkworm/infra/common/log_test.cpp
Labels: maintenance, c-api

#1567 infra: portable signal handler function
  silkworm/infra/concurrency/signal_handler.cpp
Labels: maintenance

#1562 sentry: filter discovered nodes by compatible ENR fork ID
  silkworm/infra/concurrency/channel.hpp
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/discovery/disc_v4/find/find_neighbors.cpp
  silkworm/sentry/discovery/disc_v4/find/find_neighbors.hpp
  silkworm/sentry/discovery/disc_v4/find/find_node_handler.cpp
  silkworm/sentry/discovery/disc_v4/find/lookup.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.hpp
  silkworm/sentry/discovery/disc_v4/ping/ping_handler.cpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/discovery.hpp
  silkworm/sentry/discovery/node_db/CMakeLists.txt
  silkworm/sentry/discovery/node_db/node_db.hpp
  silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite_test.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.hpp
  silkworm/sentry/eth/fork_id.cpp
  silkworm/sentry/eth/fork_id.hpp
  silkworm/sentry/eth/protocol.cpp
  silkworm/sentry/eth/protocol.hpp
  silkworm/sentry/peer_discovery_feedback.cpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/peer_manager.hpp
  silkworm/sentry/rlpx/auth/auth_message.cpp
  silkworm/sentry/rlpx/protocol.hpp
  silkworm/sentry/sentry.cpp
Labels: enhancement

#1569 api: refactor subcommands in API execute tool
  cmd/api/execute.cpp
Labels: maintenance, c-api

#1570 api: add rpcdaemon start/stop C API with default options
  cmd/api/CMakeLists.txt
  cmd/api/execute.cpp
  silkworm/api/CMakeLists.txt
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
Labels: c-api

#1568 api: fix first progress log in execution
  silkworm/api/silkworm_api.cpp
Labels: maintenance

#1572 api: change data type for memory-mapped file length
  silkworm/api/silkworm_api.h
Labels: maintenance, c-api

#1574 rpcdaemon, sync: move MDBX environment creation
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/core/local_state.hpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
  silkworm/silkrpc/ethdb/file/local_database.cpp
  silkworm/silkrpc/ethdb/file/local_database.hpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1571 core: start implementing BorRuleSet
  cmd/dev/check_pow.cpp
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/chain/genesis_mumbai.cpp
  silkworm/core/chain/genesis_mumbai.json
  silkworm/core/chain/genesis_polygon.cpp
  silkworm/core/chain/genesis_polygon.json
  silkworm/core/common/base.hpp
  silkworm/core/common/overloaded.hpp
  silkworm/core/common/test_util.cpp
  silkworm/core/common/test_util.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/base_rule_set.hpp
  silkworm/core/protocol/bor_config.cpp
  silkworm/core/protocol/bor_config.hpp
  silkworm/core/protocol/bor_config_test.cpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/clique_rule_set.cpp
  silkworm/core/protocol/clique_rule_set.hpp
  silkworm/core/protocol/clique_rule_set_test.cpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/param.hpp
  silkworm/core/protocol/rule_set.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/node/db/genesis.cpp
  silkworm/node/snapshot/config.cpp
Labels: polygon

#1577 api: add MDBX env handle in silkworm_start_rpcdaemon C API
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
Labels: c-api

#1579 rpcdaemon: remove outdated precondition check
  silkworm/silkrpc/daemon.cpp
Labels: maintenance

#1578 node: pass MDBX environment handle by value
  cmd/silkworm.cpp
  silkworm/node/node.cpp
  silkworm/node/node.hpp
Labels: maintenance

#1586 rpcdaemon: fuzzer test database refactor
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_test.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/test/api_test_database.hpp
Labels: maintenance

#1583 docs: perf flag Yes for eth_getBlockByNumber/eth_getTransactionByHash/eth_getTransactionReceipt
  docs/JSON-RPC-API.md
Labels: documentation

#1584 core: implement BorRuleSet::get_beneficiary & add_fee_transfer_log
  silkworm/core/chain/config.cpp
  silkworm/core/crypto/ecdsa.c
  silkworm/core/crypto/ecdsa.h
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/base_rule_set.hpp
  silkworm/core/protocol/bor_config.cpp
  silkworm/core/protocol/bor_config.hpp
  silkworm/core/protocol/bor_config_test.cpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/clique_rule_set.cpp
  silkworm/core/protocol/clique_rule_set.hpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/intrinsic_gas.cpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/merge_rule_set.hpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/types/block.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
Labels: polygon

#1581 rpcdaemon: validate json rpc api requests
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/request_handler.hpp
Labels: maintenance

#1589 core: revert fix for create-after-destruct
  silkworm/core/execution/evm_test.cpp
  silkworm/core/state/intra_block_state.cpp
Labels: maintenance

#1580 node: read page size from existing MDBX database
  cmd/dev/toolbox.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
Labels: maintenance

#1591 api: handle RPCDaemon not started or already started
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
Labels: maintenance, c-api

#1592 cmd: fix BitTorrent command-line options
  cmd/common/snapshot_options.cpp
  silkworm/node/bittorrent/client.cpp
  silkworm/node/bittorrent/client_test.cpp
  silkworm/node/bittorrent/settings.hpp
Labels: maintenance

#1595 core: fix gcc13 compilation
  silkworm/core/common/bytes.hpp
Labels: maintenance

#1599 sentry: fix std::optional double-free error in gcc 11
  silkworm/sentry/peer_manager_api.cpp
Labels: maintenance

#1596 infra, node: add support for START_AT_STAGE env variable
  silkworm/infra/common/environment.cpp
  silkworm/infra/common/environment.hpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
Labels: maintenance

#1602 ci: conan version 1.60 for macOS and Windows
  .github/workflows/macOS.yml
  .github/workflows/windows.yml
Labels: maintenance

#1601 Update README.md - fix architecture link
  README.md
Labels: documentation

#1604 rpcdaemon: Json version as stringview
  silkworm/silkrpc/json/block.cpp
  silkworm/silkrpc/json/call.cpp
  silkworm/silkrpc/json/log.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
Labels: maintenance

#1605 rpcdaemon: use glaze in eth_getBlockByHash
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
Labels: enhancement

#1610 docs: Google's Style Guide updated to C++20
  docs/CONTRIBUTING.md
Labels: documentation

#1608 node: use correct check for BMI instructions in RecSplit
  silkworm/node/recsplit/support/common.hpp
Labels: enhancement

#1603 cmd: fix RPCDaemon start in execute tool
  cmd/api/execute.cpp
Labels: maintenance

#1606 infra: disable logging option for coloured output if log file is required
  cmd/api/execute.cpp
  silkworm/api/silkworm_api.cpp
  silkworm/infra/common/log.cpp
  silkworm/infra/common/log_test.cpp
Labels: maintenance

#1612 core: replace eip1559FeeCollector with burntContract
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_map.hpp
  silkworm/core/chain/config_map_test.cpp
  silkworm/core/chain/genesis_mumbai.cpp
  silkworm/core/chain/genesis_mumbai.json
  silkworm/core/chain/genesis_polygon.cpp
  silkworm/core/chain/genesis_polygon.json
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/bor_config.cpp
  silkworm/core/protocol/bor_config.hpp
  silkworm/core/protocol/bor_config_test.cpp
Labels: polygon

#1618 core: fix ConfigMap conversion error in MSVC
  silkworm/core/chain/config_map.hpp
Labels: maintenance

#1614 node: change cursor usage in trie test causing abort in debug
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/node/test/context.cpp
  silkworm/node/test/context.hpp
Labels: maintenance

#1622 node: make stage TxLookup start from last frozen block
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/stagedsync/stages/stage.cpp
  silkworm/node/stagedsync/stages/stage.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
Labels: maintenance

#1623 sentry: fix update_eth1_fork_id column index out of range
  silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite_test.cpp
Labels: maintenance
