Repository erigontech/silkworm, pull requests merged in 2023-08, with the labels that each got.

#1380 rpcdaemon: read block number by transaction hash
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend_test.cpp
  silkworm/silkrpc/storage/chain_storage.hpp
  silkworm/silkrpc/storage/local_chain_storage.cpp
  silkworm/silkrpc/storage/local_chain_storage.hpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
  silkworm/silkrpc/storage/remote_chain_storage.hpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
Labels: snapshots

#1391 rpcdaemon: adapt parity API to snapshots
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/commands/parity_api.hpp
Labels: snapshots

#1389 rpcdaemon: add snapshot support in ots API
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/storage/chain_storage.hpp
  tests/integration/goerly/debug_getModifiedAccountsByNumber/test_1.json
  tests/integration/goerly/eth_getBlockTransactionCountByHash/test_2.json
  tests/integration/goerly/eth_getStorageAt/test_3.json
  tests/integration/goerly/eth_getStorageAt/test_4.json
  tests/integration/goerly/eth_getStorageAt/test_5.json
Labels: snapshots

#1395 node: create decompressor from memory address and length
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/huffman/decompressor_test.cpp
Labels: c-api

#1393 rpcdaemon: adapt eth API using get block by transaction hash to snapshots
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/ethdb/transaction_database.hpp
Labels: snapshots

#1396 api: add EVM analysis cache and state pool in C API for block execution
  silkworm/api/silkworm_api.cpp
  silkworm/core/execution/execution.hpp
Labels: c-api

#1399 node: fix stage Senders after snapshot support (PR #1264)
  silkworm/node/db/tables.hpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
Labels: pos-sync

#1397 cmd, api, node: snapshot refactoring
  cmd/dev/snapshots.cpp
  silkworm/api/silkworm_api.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/path_test.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/test/snapshots.hpp
Labels: maintenance

#1400 node: make initial progress log uniform in first stages
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
Labels: maintenance

#1403 sync: fix crash in Sync::start_chain_sync
  silkworm/sync/sync.cpp
Labels: maintenance

#1401 rpcdaemon: adapt erigon API to snapshots
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
Labels: snapshots

#1402 rpcdaemon: adapt API using block by transaction hash to snapshots
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  tests/integration/goerly/eth_callBundle/test_9.json
  tests/integration/goerly/eth_getStorageAt/test_6.json
Labels: snapshots

#1407 api: support platform-independent API library path
  cmd/api/execute.cpp
Labels: c-api

#1409 node: reduce number of parameters and refactor write_tx_lookup
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
Labels: maintenance

#1408 cmd: add blocks and unwind commands in toolbox
  cmd/dev/toolbox.cpp
  silkworm/node/db/util.cpp
  silkworm/node/db/util.hpp
Labels: maintenance

#1410 node: custom stack size for non-main thread running block execution
  silkworm/infra/concurrency/active_component.hpp
  silkworm/infra/concurrency/async_thread.cpp
  silkworm/infra/concurrency/async_thread.hpp
  silkworm/node/node.cpp
Labels: maintenance

#1411 rpcdaemon: remove unused functions in cached chain
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/core/cached_chain_test.cpp
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/call_many.hpp
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain.hpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
Labels: maintenance

#1406 rpcdeamon: enable eth_getTransactionByHash test
  silkworm/node/db/access_layer.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/json/transaction.cpp
  silkworm/silkrpc/json/transaction_test.cpp
Labels: rpcdaemon, unit-test

#1421 rpcdaemon: exclude RPC IO tests from ASAN/TSAN builds
  silkworm/silkrpc/commands/rpc_api_test.cpp
Labels: maintenance

#1412 rpcdeamon: enable eth_getTransactionReceipt test
  silkworm/node/snapshot/repository.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/json/receipt.cpp
  silkworm/silkrpc/json/receipt_test.cpp
Labels: rpcdaemon, unit-test

#1415 rpcdaemon: fix local db access without snapshots
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/core/evm_debug.cpp
Labels: snapshots, maintenance

#1420 api: add snapshot by specifying memory region for segment and index(es)
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/memory_mapped_file.hpp
  silkworm/infra/common/memory_mapped_file_test.cpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/huffman/decompressor_test.cpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/recsplit/rec_split_test.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
Labels: snapshots, c-api

#1417 rpcdaemon: update test result
  tests/integration/README.md
Labels: documentation, integration-test

#1382 rpcdaemon: erigon_getBalanceChangesInBlock API
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/erigon_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/block_reader.cpp
  silkworm/silkrpc/core/block_reader.hpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/erigon_getBalanceChangesInBlock/test_01.json
  tests/integration/goerly/erigon_getBalanceChangesInBlock/test_02.tar
  tests/integration/goerly/erigon_getBalanceChangesInBlock/test_03.json
  tests/integration/goerly/erigon_getBalanceChangesInBlock/test_04.tar
  tests/integration/goerly/erigon_getBalanceChangesInBlock/test_05.json
Labels: json-rpc-api

#1418 rpcdaemon: modify ethbackend version from 3.2 to 3.3
  silkworm/infra/grpc/common/version.hpp
  silkworm/infra/grpc/common/version_test.cpp
Labels: maintenance, rpcdaemon

#1426 infra, node, sentry, sync: thread name in log traces for async_thread
  cmd/dev/backend_kv_server.cpp
  silkworm/infra/concurrency/active_component.hpp
  silkworm/infra/concurrency/async_thread.cpp
  silkworm/infra/concurrency/async_thread.hpp
  silkworm/infra/grpc/client/reconnect.cpp
  silkworm/infra/grpc/server/server.hpp
  silkworm/node/node.cpp
  silkworm/sentry/grpc/server/server.cpp
  silkworm/sync/block_exchange.cpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync_pow.cpp
Labels: maintenance

#1428 infra: small improvement in OS page size detection
  silkworm/infra/common/os.cpp
Labels: maintenance

#1378 build, core: switch to std::bit_cast. Bump min Clang to 14
  .circleci/config.yml
  .github/workflows/macOS.yml
  README.md
  cmd/state-transition/state_transition.cpp
  cmd/test/ethereum.cpp
  silkworm/core/common/base_test.cpp
  silkworm/core/common/cast.hpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/core/state/intra_block_state_test.cpp
  silkworm/core/trie/hash_builder.cpp
  silkworm/core/types/block.cpp
  silkworm/core/types/transaction.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/core/override_state.cpp
  silkworm/silkrpc/storage/local_chain_storage.cpp
Labels: maintenance

#1430 sentry: improve STUN host not found error message
  silkworm/sentry/nat/stun_ip_resolver.cpp
Labels: maintenance

#1427 api: sample cgo client to call silkworm_api lib
  cmd/api/sample-go-client/README.md
  cmd/api/sample-go-client/load.go
  cmd/api/sample-go-client/main.go
  cmd/api/sample-go-client/silkworm.go
  silkworm/api/silkworm_api.h
Labels: c-api

#1433 rpcdaemon: erigon_getBlockReceiptsByBlockHash
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/erigon_api.cpp
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_01.tar
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_02.tar
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_03.tar
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_04.tar
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_05.json
  tests/integration/goerly/erigon_getBlockReceiptsByBlockHash/test_06.tar
Labels: json-rpc-api

#1432 rpcdaemon: add Erigon compatibility flag for JSON API
  cmd/common/rpcdaemon_options.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/common/compatibility.cpp
  silkworm/silkrpc/common/compatibility.hpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/json/receipt.cpp
  silkworm/silkrpc/json/transaction.cpp
  silkworm/silkrpc/settings.hpp
Labels: enhancement

#1437 rpcademon: temporarily skip ots_getInternalOperations in integration tests
  tests/integration/run_tests.py
Labels: integration-test

#1441 rpcdaemon: remove core:rawdb::read_total_difficulty calls from eth api
  silkworm/silkrpc/commands/eth_api.cpp
Labels: maintenance

#1443 rpcdaemon: fix serialization of "to" field as JSON null in Receipt
  silkworm/silkrpc/json/receipt.cpp
Labels: maintenance

#1440 cmd: blocks and unwind commands in toolbox command-line utility
  cmd/dev/toolbox.cpp
Labels: enhancement

#1449 rpcdaemon: fix BackEnd mock memory leaks detected by ASAN in unit tests
  silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
  silkworm/silkrpc/core/remote_state_test.cpp
Labels: maintenance

#1447 rpcdaemon: remove calls to core::rawdb::read_chain_config & core::rawdb::read_chain_id
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1446 rpcdaemon: update test result with erigon 2.48.1
  tests/integration/README.md
Labels: integration-test

#1450 sync: workarounds for difficulty and total difficulty in header chain
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/internals/header_only_state.cpp
  silkworm/sync/internals/header_only_state.hpp
Labels: maintenance

#1451 rpcdaemon: remove rawdb:.read_block
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
Labels: maintenance

#1442 sentry: discovery bootnodes
  cmd/common/sentry_options.cpp
  cmd/sentry.cpp
  cmd/silkworm.cpp
  silkworm/sentry/discovery/bootnodes.cpp
  silkworm/sentry/discovery/bootnodes.hpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/discovery.hpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/settings.hpp
Labels: enhancement

#1448 rpcdaemon: extract backend mock
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
  silkworm/silkrpc/core/evm_debug_test.cpp
  silkworm/silkrpc/core/evm_executor_test.cpp
  silkworm/silkrpc/core/evm_trace_test.cpp
  silkworm/silkrpc/core/remote_state_test.cpp
  silkworm/silkrpc/test/mock_back_end.hpp
Labels: maintenance

#1424 infra: rethrow unhandled exceptions from TaskGroup::wait
  silkworm/infra/concurrency/task_group.cpp
  silkworm/infra/concurrency/task_group.hpp
  silkworm/infra/concurrency/task_group_test.cpp
Labels: maintenance

#1453 rpcdaemon: remove core::rawdb::read header, read_body, read_block, read_senders
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.hpp
  silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain.hpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
  silkworm/silkrpc/test/mock_chain_storage.hpp
Labels: maintenance

#1455 rpcdaemon: remove unused public functions from chain module
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/rawdb/chain.hpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
Labels: maintenance

#1457 Rpcdaemon: Extract CallBundle to_json() into separate file
  silkworm/silkrpc/json/call_bundle.cpp
  silkworm/silkrpc/json/call_bundle.hpp
  silkworm/silkrpc/json/call_bundle_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/call_bundle.hpp
  silkworm/silkrpc/types/transaction.hpp
Labels: maintenance

#1456 RpcDaemon: BlockNum types instead of uint64_t
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/core/remote_state.cpp
  silkworm/silkrpc/storage/chain_storage.hpp
  silkworm/silkrpc/types/block.hpp
Labels: maintenance

#1458 clang-tidy fixes
  .circleci/config.yml
  .clang-tidy
  cmd/api/execute.cpp
  silkworm/core/execution/precompile_benchmark.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/grpc/interfaces/types.cpp
  silkworm/infra/grpc/interfaces/types.hpp
  silkworm/node/backend/remote/grpc/kv_calls.cpp
  silkworm/node/common/preverified_hashes.cpp
  silkworm/node/db/eth_status_data_provider.cpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/sentry/api/router/direct_service.cpp
  silkworm/sentry/grpc/interfaces/peer_event.cpp
  silkworm/sentry/grpc/interfaces/peer_id.cpp
  silkworm/sentry/grpc/interfaces/status_data.cpp
  silkworm/sentry/grpc/server/server_calls.hpp
  silkworm/sentry/node_key_config_test.cpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/rlpx/crypto/hmac.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/sync/internals/header_chain.cpp
  third_party/clang-tidy-html/LICENSE
  third_party/clang-tidy-html/clang_visualizer.py
Labels: maintenance

#1464 node: clean up stage senders state in repeated forward
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
Labels: maintenance

#1463 core: improve readability in zeroless_view function implementation
  silkworm/core/common/util.cpp
  silkworm/core/common/util_test.cpp
Labels: maintenance

#1465 node: fix payload offset for non-legacy transaction in TransactionSnapshot
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: snapshots, maintenance

#1469 rpcdaemon: add static snapshot support in standalone mode
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
Labels: snapshots

#1471 rpcdaemon: fix path to string conversion on Windows build
  silkworm/silkrpc/daemon.cpp
Labels: maintenance

#1467 rpcdaemon: enable mimalloc override on conanfile
  conanfile.txt
Labels: maintenance

#1468 doc: new organisation in README links
  README.md
Labels: documentation

#1470 cmd: fix argument passing for sentry list options
  cmd/common/sentry_options.cpp
Labels: maintenance

#1444 rpcdaemon: erigon_getLatestLogs
  .gitignore
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/core/logs_walker.cpp
  silkworm/silkrpc/core/logs_walker.hpp
  silkworm/silkrpc/json/filter.cpp
  silkworm/silkrpc/json/filter.hpp
  silkworm/silkrpc/json/filter_test.cpp
  silkworm/silkrpc/json/log.cpp
  silkworm/silkrpc/types/filter.cpp
  silkworm/silkrpc/types/filter.hpp
  silkworm/silkrpc/types/filter_test.cpp
  silkworm/silkrpc/types/log.hpp
  tests/integration/README.md
  tests/integration/goerly/erigon_getLatestLogs/test_01.json
  tests/integration/goerly/erigon_getLatestLogs/test_02.json
  tests/integration/goerly/erigon_getLatestLogs/test_03.json
  tests/integration/goerly/erigon_getLatestLogs/test_04.json
  tests/integration/goerly/erigon_getLatestLogs/test_05.json
  tests/integration/goerly/erigon_getLatestLogs/test_06.json
  tests/integration/goerly/erigon_getLatestLogs/test_07.json
  tests/integration/goerly/erigon_getLatestLogs/test_08.json
  tests/integration/goerly/erigon_getLatestLogs/test_09.json
  tests/integration/goerly/erigon_getLatestLogs/test_10.json
  tests/integration/goerly/erigon_getLatestLogs/test_11.json
  tests/integration/run_tests.py
Labels: json-rpc-api

#1473 node: fix transaction-to-block idx file name for Erigon compatibility
  cmd/api/execute.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/path.hpp
  silkworm/node/snapshot/snapshot.cpp
Labels: snapshots, maintenance

#1466 rpcdaemon: move state creation to worker thread in TraceCallExecutor::trace_operations
  silkworm/silkrpc/core/evm_trace.cpp
  tests/integration/run_tests.py
Labels: maintenance

#1474 node: fix block number by transaction hash lookup in snapshots
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: snapshots, maintenance

#1479 CI: fix windows build disabling mimalloc override option
  .github/workflows/windows.yml
  cmake/conan.cmake
Labels: maintenance

#1477 api: add write flags for state changes and call traces in block execution [WIP]
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
Labels: c-api

#1476 rpcdaemon: avoid transactions/header copies
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
Labels: maintenance

#1475 rpcdaemon: update tests result
  tests/integration/README.md
Labels: integration-test

#1481 rpcdaemon: accept both string and integer as block in erigon_getHeaderByNumber
  silkworm/silkrpc/commands/erigon_api.cpp
Labels: maintenance
