Repository erigontech/silkworm, pull requests merged in 2023-06, with the labels that each got.

#1208 execution: fix fork reintegration
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
Labels: maintenance

#1213 execution: add support for memory mutations to stages
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_loader.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_loader.hpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
Labels: pos-sync

#1214 sentry: unexpected first message ID in exception
  silkworm/sentry/eth/protocol.cpp
Labels: maintenance

#1215 node: add missing LastForkchoice table
  silkworm/node/db/tables.cpp
  silkworm/node/db/tables.hpp
Labels: maintenance

#1218 rpcdaemon: use shared chaindata MDBX env in embedded execution
  silkworm/silkrpc/core/remote_state.cpp
  silkworm/silkrpc/core/remote_state_test.cpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
  silkworm/silkrpc/ethdb/file/local_cursor.cpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1046 rpcdaemon: eth_callMany API
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/call_many.hpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/override_state.cpp
  silkworm/silkrpc/core/override_state.hpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/call.cpp
  silkworm/silkrpc/json/call.hpp
  silkworm/silkrpc/json/call_test.cpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/call.cpp
  silkworm/silkrpc/types/call.hpp
  tests/integration/goerly/eth_callMany/test_01.json
  tests/integration/goerly/eth_callMany/test_02.json
  tests/integration/goerly/eth_callMany/test_03.json
  tests/integration/goerly/eth_callMany/test_04.json
  tests/integration/goerly/eth_callMany/test_05.json
  tests/integration/goerly/eth_callMany/test_06.json
  tests/integration/goerly/eth_callMany/test_07.json
  tests/integration/run_tests.py
Labels: rpc-api

#1220 sentry: use Task type instead of awaitable
  .clang-format
  silkworm/node/common/resource_usage.hpp
  silkworm/node/node.hpp
  silkworm/sentry/api/api_common/sentry_client.hpp
  silkworm/sentry/api/api_common/service.hpp
  silkworm/sentry/api/router/direct_service.cpp
  silkworm/sentry/api/router/direct_service.hpp
  silkworm/sentry/api/router/messages_call.hpp
  silkworm/sentry/api/router/send_message_call.hpp
  silkworm/sentry/common/sleep.cpp
  silkworm/sentry/common/sleep.hpp
  silkworm/sentry/common/socket_stream.cpp
  silkworm/sentry/common/socket_stream.hpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/discovery.hpp
  silkworm/sentry/grpc/client/sentry_client.cpp
  silkworm/sentry/grpc/client/sentry_client.hpp
  silkworm/sentry/grpc/server/server.cpp
  silkworm/sentry/grpc/server/server.hpp
  silkworm/sentry/grpc/server/server_calls.hpp
  silkworm/sentry/message_receiver.cpp
  silkworm/sentry/message_receiver.hpp
  silkworm/sentry/message_sender.cpp
  silkworm/sentry/message_sender.hpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/multi_sentry_client.hpp
  silkworm/sentry/nat/ip_resolver.hpp
  silkworm/sentry/nat/local_ip_resolver.hpp
  silkworm/sentry/nat/stun_ip_resolver.hpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/peer_manager.hpp
  silkworm/sentry/peer_manager_api.cpp
  silkworm/sentry/peer_manager_api.hpp
  silkworm/sentry/rlpx/auth/auth_initiator.cpp
  silkworm/sentry/rlpx/auth/auth_initiator.hpp
  silkworm/sentry/rlpx/auth/auth_recipient.cpp
  silkworm/sentry/rlpx/auth/auth_recipient.hpp
  silkworm/sentry/rlpx/auth/handshake.cpp
  silkworm/sentry/rlpx/auth/handshake.hpp
  silkworm/sentry/rlpx/client.cpp
  silkworm/sentry/rlpx/client.hpp
  silkworm/sentry/rlpx/framing/message_stream.cpp
  silkworm/sentry/rlpx/framing/message_stream.hpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/rlpx/peer.hpp
  silkworm/sentry/rlpx/server.cpp
  silkworm/sentry/rlpx/server.hpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/sentry.hpp
  silkworm/sentry/session_sentry_client.cpp
  silkworm/sentry/session_sentry_client.hpp
  silkworm/sentry/status_manager.cpp
  silkworm/sentry/status_manager.hpp
Labels: maintenance

#1223 core: remove Rinkeby
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_test.cpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/chain/genesis_rinkeby.cpp
  silkworm/core/chain/genesis_rinkeby.json
  silkworm/core/chain/genesis_test.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/node/db/genesis_test.cpp
  silkworm/sentry/eth/fork_id_test.cpp
Labels: maintenance

#1225 rpcdaemon: handle timeout in eth_callMany
  silkworm/silkrpc/core/call_many.cpp
Labels: enhancement

#1221 core, sentry, rpcdaemon: add fork points by timestamp
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_test.cpp
  silkworm/core/common/base.hpp
  silkworm/node/db/eth_status_data_provider.cpp
  silkworm/sentry/eth/fork_id.cpp
  silkworm/sentry/eth/fork_id.hpp
  silkworm/sentry/eth/fork_id_test.cpp
  silkworm/sentry/eth/protocol.cpp
  silkworm/sentry/eth/status_data.hpp
  silkworm/sentry/grpc/interfaces/status_data.cpp
  silkworm/silkrpc/types/chain_config.hpp
Labels: enhancement, shanghai

#1230 rpcdaemon: local state must be deallocated by worker in eth_call
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/local_state.cpp
  silkworm/silkrpc/core/local_state.hpp
Labels: maintenance

#1229 Use C++20 safe integral comparisons
  silkworm/core/execution/evm.cpp
  silkworm/core/trie/node.cpp
  silkworm/core/trie/node_test.cpp
  silkworm/infra/common/binary_search_test.cpp
  silkworm/infra/common/memory_mapped_file_benchmark.cpp
  silkworm/node/db/bitmap_test.cpp
  silkworm/silkrpc/ethdb/cbor.cpp
Labels: maintenance

#1228 rpcdaemon: improve block number lookup
  silkworm/silkrpc/core/blocks.cpp
  silkworm/silkrpc/core/blocks_test.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1235 node: to_previous API in memory mutation
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor.hpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
Labels: memory-mutation

#1234 node: add FCU table usage and make some cleanups
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/canonical_chain.cpp
  silkworm/node/stagedsync/forks/canonical_chain.hpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/extending_fork.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/fork_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
Labels: pos-sync

#1237 rpcdaemon: timeout parameter in eth_callMany integration tests
  tests/integration/goerly/eth_callMany/test_01.json
  tests/integration/goerly/eth_callMany/test_02.json
  tests/integration/goerly/eth_callMany/test_03.json
  tests/integration/goerly/eth_callMany/test_04.json
  tests/integration/goerly/eth_callMany/test_05.json
  tests/integration/goerly/eth_callMany/test_06.json
  tests/integration/goerly/eth_callMany/test_07.json
Labels: maintenance

#1236 rpcdaemon: fix local state lifecycle
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/account_walker_test.cpp
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/core/local_state.cpp
  silkworm/silkrpc/core/local_state.hpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.cpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.hpp
  silkworm/silkrpc/ethdb/transaction.hpp
  silkworm/silkrpc/test/dummy_transaction.hpp
  silkworm/silkrpc/test/mock_transaction.hpp
Labels: maintenance

#1238 node: fix upsert + update in memory mutation
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor.hpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
Labels: memory-mutation

#1239 sync: add unit tests for ETH66 BlockBodies packet
  silkworm/sync/packets/packet_coding_test.cpp
Labels: maintenance

#1241 node: add lookup and ordinal lookup in RecSplit index
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/recsplit/rec_split_test.cpp
Labels: snapshot-sync

#1246 rpcdaemon: fix eth_callMany state on worker thread
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/call_many.hpp
Labels: maintenance

#1251 node: fix ASAN + UBSAN issues in snapshot RecSplit index
  .circleci/config.yml
  silkworm/node/recsplit/encoding/elias_fano.hpp
  silkworm/node/recsplit/encoding/elias_fano_test.cpp
  silkworm/node/recsplit/encoding/golomb_rice.hpp
  silkworm/node/recsplit/rec_split.hpp
Labels: maintenance

#1252 doc: fix and move JSON RPC API doc
  docs/JSON-RPC-API.md
Labels: documentation

#1255 node: add search functions in snapshot repository
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot.cpp
Labels: snapshot-sync

#1256 node: add support for snapshots in db access layer [WIP]
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/core/types/transaction_test.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: snapshot-sync

#1257 core: move validate_transaction to protocol/validation
  cmd/state-transition/state_transition.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
  silkworm/core/execution/processor_test.cpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/protocol/validation_test.cpp
Labels: maintenance

#1258 core: erigon names for tx types
  cmd/state-transition/state_transition.cpp
  silkworm/core/common/test_util.cpp
  silkworm/core/execution/execution_test.cpp
  silkworm/core/protocol/intrinsic_gas_test.cpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation_test.cpp
  silkworm/core/types/block_test.cpp
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/core/types/transaction_test.cpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/silkrpc/common/util_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/transaction_test.cpp
Labels: maintenance

#1261 node: skip tests that fail on windows
  silkworm/node/backend/remote/backend_kv_server_test.cpp
Labels: maintenance

#1263 node: more support for snapshots in db access layer
  silkworm/core/types/hash.hpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/silkrpc/core/rawdb/chain.cpp
Labels: snapshot-sync

#1245 rpcdaemon: eth_callMany API refinements
  silkworm/silkrpc/core/call_many.cpp
  tests/integration/goerly/eth_callMany/test_08.json
  tests/integration/goerly/eth_callMany/test_09.json
  tests/integration/goerly/eth_callMany/test_10.json
  tests/integration/run_tests.py
Labels: rpc-api

#1266 node: expose transaction RLP data from snapshots
  cmd/dev/snapshots.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/test/snapshots.hpp
Labels: snapshot-sync

#1264 execution: introduce data-model for snapshot support
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/forks/canonical_chain.cpp
  silkworm/node/stagedsync/forks/canonical_chain.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_bodies.hpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_headers.hpp
  silkworm/node/stagedsync/stages/stage_headers_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/sync/internals/header_retrieval.cpp
  silkworm/sync/internals/header_retrieval.hpp
Labels: snapshot-sync

#1267 node: expose RLP-encoded transactions from data model
  cmd/dev/snapshots.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/node.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
  silkworm/node/snapshot/sync_test.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
Labels: snapshot-sync

#1250 rpcdaemon: fix eth_estimateGas state on worker thread
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.hpp
  silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
  silkworm/silkrpc/test/mock_estimate_gas_oracle.hpp
Labels: maintenance

#1270 rpcdaemon: remove awaitable create_state
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/account_walker_test.cpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.cpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.hpp
  silkworm/silkrpc/ethdb/transaction.hpp
  silkworm/silkrpc/test/dummy_transaction.hpp
  silkworm/silkrpc/test/mock_transaction.hpp
Labels: maintenance

#1271 rpcdaemon: trace_block/trace_block_transactions rework actions by worker thread
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/core/evm_trace_test.cpp
  silkworm/silkrpc/test/dummy_transaction.hpp
Labels: maintenance

#1273 rpcdaemon: trace_calls rework worker thread actions
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1268 rpcdaemon: DebugExecutor refactoring
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
  silkworm/silkrpc/test/mock_block_cache.hpp
Labels: maintenance

#1278 rpcdaemon: fix transaction parsing for ExecutionPayload
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload_test.cpp
Labels: maintenance

#1279 core: fix Hash::from_hex
  silkworm/core/types/hash.hpp
  silkworm/core/types/hash_test.cpp
  silkworm/sync/packets/packet_coding_test.cpp
Labels: maintenance

#1275 node, sync: introduce and use get_header by number and hash
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/local_client.cpp
  silkworm/node/stagedsync/local_client.hpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/remote_client.hpp
  silkworm/node/stagedsync/server.cpp
  silkworm/node/stagedsync/server.hpp
  silkworm/sync/sync_pos.cpp
Labels: pos-sync

#1277 rpcdaemon: move state creation to worker thread in TraceCallExecutor
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1280 rpcdaemon: Transaction as json module
  silkworm/silkrpc/json/transaction.cpp
  silkworm/silkrpc/json/transaction.hpp
  silkworm/silkrpc/json/transaction_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1281 node: fix overflow in snapshot decompressor
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/snapshot/snapshot.cpp
Labels: pos-sync

#1282 rpcdaemon: fix integration test expected response
  tests/integration/README.md
  tests/integration/goerly/engine_getPayloadBodiesByHashV1/test_1.json
  tests/integration/goerly/engine_getPayloadBodiesByRangeV1/test_1.json
  tests/integration/goerly/eth_callMany/test_09.json
  tests/integration/run_tests.py
Labels: maintenance

#1283 node: enforce RecSplit invariants
  silkworm/node/recsplit/encoding/elias_fano.hpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/recsplit/rec_split_test.cpp
Labels: maintenance

#1284 node: update database after snapshot sync
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
Labels: snapshot-sync

#1285 snapshots: choose repository path according to user specified data-dir
  cmd/common/common.cpp
  cmd/silkworm.cpp
Labels: maintenance

#1265 rpcdaemon: debug_traceCallMany API
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/debug_traceCallMany/test_01.json
  tests/integration/goerly/debug_traceCallMany/test_02.json
  tests/integration/goerly/debug_traceCallMany/test_03.json
  tests/integration/goerly/debug_traceCallMany/test_04.json
  tests/integration/goerly/debug_traceCallMany/test_05.json
Labels: rpc-api

#1286 sync: move block when passing new target to block exchange
  silkworm/sync/block_exchange.cpp
  silkworm/sync/block_exchange.hpp
  silkworm/sync/sync_pos.cpp
Labels: pos-sync

#1288 rpcdaemon: move state creation to worker thread in DebugExecutor
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
Labels: maintenance

#1289 rpcdaemon: EVMExecutor tests using generic state
  silkworm/silkrpc/core/evm_executor_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1290 rpcdaemon: update perf results
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_01.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_05.txt
Labels: perf-test

#1293 rpcdaemon: EVMExecutor remove constructor with RemoteState
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/estimate_gas_oracle.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/core/evm_executor_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1291 cmd: add lookup_header command in snapshots tool
  cmd/dev/snapshots.cpp
Labels: snapshot-sync

#1292 node: improve find snapshot
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/test/snapshots.hpp
Labels: snapshot-sync

#1295 snapshot: fix MemoryMappedFile on Windows
  silkworm/infra/common/memory_mapped_file.cpp
Labels: maintenance

#1226 rpcdaemon: add ots_getInternalOperations API
  docs/JSON-RPC-API.md
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm_test.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/ots_getInternalOperations/test_1.json
  tests/integration/goerly/ots_getInternalOperations/test_2.json
  tests/integration/goerly/ots_traceTransaction/test_3.json
Labels: rpc-api

#1297 rpcdaemon: add try-catch around EVM::execute
  silkworm/silkrpc/core/evm_executor.cpp
Labels: maintenance
