Repository erigontech/silkworm, pull requests merged in 2023-09, with the labels that each got.

#1486 node: use uint32 roaring bitmaps in LogIndex stage
  silkworm/node/db/bitmap.cpp
  silkworm/node/db/bitmap.hpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
Labels: maintenance

#1487 node: remove block check in unwind of HistoryIndex stage
  silkworm/node/stagedsync/stages/stage_history_index.cpp
Labels: maintenance

#1488 node: speed up parallel recover in Senders stage for small spans
  silkworm/node/stagedsync/stages/stage_senders.cpp
Labels: maintenance

#1478 rpcdaemon: add checks on no block retrieved from chain
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/account_dumper.cpp
  silkworm/silkrpc/core/block_reader.cpp
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/logs_walker.cpp
Labels: maintenance

#1480 rpcdaemon: add "don't care" expected response in integration tests
  tests/integration/goerly/eth_callBundle/test_8.json
  tests/integration/goerly/eth_createAccessList/test_4.json
  tests/integration/run_tests.py
Labels: integration-test

#1489 node: improve staged sync logging
  silkworm/node/db/stages.hpp
  silkworm/node/db/tables.hpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_finish.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
Labels: maintenance

#1484 sentry: refactor client factory from silkworm.cpp to sentry lib
  cmd/sentry.cpp
  cmd/silkworm.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/infra/grpc/common/grpc_context_pool.hpp
  silkworm/sentry/sentry_client_factory.cpp
  silkworm/sentry/sentry_client_factory.hpp
Labels: maintenance

#1472 core: EIP-4788: Beacon block root in the EVM
  cmd/test/ethereum.cpp
  silkworm/core/common/test_util.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/blockchain.cpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/merge_rule_set.hpp
  silkworm/core/protocol/merge_rule_set_test.cpp
  silkworm/core/protocol/param.hpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/core/types/block_test.cpp
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/silkrpc/core/fee_history_oracle.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
Labels: cancun

#1485 infra: setup GRPC logging in log::init
  cmd/dev/backend_kv_server.cpp
  cmd/sentry.cpp
  cmd/test/backend_kv_test.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/infra/common/log.cpp
  silkworm/infra/common/log.hpp
Labels: maintenance

#1490 rpcdaemon: make trace_block and trace_filter work not only with Ethash
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/base_rule_set.hpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/merge_rule_set.hpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
  tests/integration/README.md
  tests/integration/goerly/trace_block/test_01.tar
  tests/integration/goerly/trace_block/test_02.tar
  tests/integration/goerly/trace_block/test_03.tar
  tests/integration/goerly/trace_block/test_04.tar
  tests/integration/goerly/trace_block/test_05.tar
  tests/integration/goerly/trace_block/test_06.tar
  tests/integration/goerly/trace_block/test_07.tar
  tests/integration/goerly/trace_block/test_08.json
  tests/integration/goerly/trace_block/test_09.tar
  tests/integration/goerly/trace_block/test_10.json
  tests/integration/goerly/trace_block/test_11.json
  tests/integration/goerly/trace_block/test_12.json
  tests/integration/goerly/trace_block/test_13.json
  tests/integration/goerly/trace_block/test_14.json
  tests/integration/goerly/trace_filter/test_01.tar
  tests/integration/goerly/trace_filter/test_02.tar
  tests/integration/goerly/trace_filter/test_03.json
  tests/integration/goerly/trace_filter/test_04.json
  tests/integration/goerly/trace_filter/test_05.tar
  tests/integration/goerly/trace_filter/test_06.tar
  tests/integration/goerly/trace_filter/test_07.tar
  tests/integration/goerly/trace_filter/test_08.json
  tests/integration/goerly/trace_filter/test_09.tar
  tests/integration/goerly/trace_filter/test_1.tar
  tests/integration/goerly/trace_filter/test_2.tar
  tests/integration/goerly/trace_filter/test_5.tar
  tests/integration/goerly/trace_filter/test_6.tar
  tests/integration/goerly/trace_filter/test_7.tar
Labels: maintenance, rpcdaemon

#1492 rpcdaemon: refactor JWT request authorization check
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/request_handler.hpp
Labels: maintenance

#1493 node: lower_bound and move implementation in memory mutation
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
Labels: maintenance, memory mutation

#1482 rpcdaemon: implementing HTTP CORS for RPC API
  cmd/common/rpcdaemon_options.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/http/connection.cpp
  silkworm/silkrpc/http/connection.hpp
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/request_handler.hpp
  silkworm/silkrpc/http/request_parser.cpp
  silkworm/silkrpc/http/request_parser_test.cpp
  silkworm/silkrpc/http/server.cpp
  silkworm/silkrpc/http/server.hpp
  silkworm/silkrpc/settings.hpp
Labels: enhancement

#1495 rpcademon: fix startup crash when CORS domain option is not set
  silkworm/silkrpc/http/request_handler.cpp
Labels: maintenance

#1497 rpcdaemon: slightly improve HTTP CORS handling
  cmd/common/rpcdaemon_options.cpp
  silkworm/silkrpc/http/request_handler.cpp
Labels: maintenance

#1502 node: skip non-address and non-topic data in LogIndex stage
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_log_index.hpp
  silkworm/node/types/log_cbor.cpp
  silkworm/node/types/log_cbor.hpp
  silkworm/node/types/log_cbor_test.cpp
Labels: maintenance

#1498 rpcdaemon: remove unnecessary hash calculation in cached chain
  silkworm/node/snapshot/repository.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/daemon.cpp
Labels: maintenance

#1504 cmd: add tool check_log_indices
  cmd/dev/CMakeLists.txt
  cmd/dev/README.md
  cmd/dev/check_log_indices.cpp
  cmd/dev/check_senders.cpp
  silkworm/node/db/bitmap.cpp
  silkworm/node/db/bitmap.hpp
  silkworm/node/db/util.cpp
  silkworm/node/db/util.hpp
Labels: enhancement

#1500 rpcdaemon: modify base class of clique consensus
  silkworm/core/protocol/clique_rule_set.hpp
  silkworm/silkrpc/core/evm_trace_test.cpp
Labels: maintenance

#1501 rpcdaemon: enable erigon_getLatestLogs in integration tests
  tests/integration/run_tests.py
Labels: integration-test

#1506 rpcdaemon: fix payloadId serialization in ForkChoiceUpdateReply
  silkworm/silkrpc/json/fork_choice.cpp
  silkworm/silkrpc/json/fork_choice_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1503 rpcdaemon: improve LogsWalker::get_logs
  silkworm/silkrpc/core/logs_walker.cpp
  tests/integration/goerly/erigon_getLatestLogs/test_01.json
  tests/integration/goerly/erigon_getLatestLogs/test_02.json
  tests/integration/goerly/erigon_getLatestLogs/test_03.json
  tests/integration/goerly/erigon_getLatestLogs/test_04.json
  tests/integration/goerly/erigon_getLatestLogs/test_05.json
  tests/integration/goerly/erigon_getLatestLogs/test_06.json
  tests/integration/goerly/erigon_getLatestLogs/test_07.json
  tests/integration/goerly/erigon_getLatestLogs/test_08.json
  tests/integration/goerly/erigon_getLatestLogs/test_09.json
  tests/integration/goerly/erigon_getLatestLogs/test_10.json
  tests/integration/goerly/erigon_getLatestLogs/test_11.json
  tests/integration/goerly/erigon_getLatestLogs/test_12.json
Labels: maintenance

#1509 rpcdaemon: adjust log level for traces
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/parity_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/block_reader.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/filter_storage.cpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/ethdb/kv/state_changes_stream.cpp
Labels: maintenance

#1511 node: revalidate canonical chain with one forward cycle at startup
  silkworm/node/common/settings.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
  silkworm/node/stagedsync/local_client.cpp
  silkworm/node/stagedsync/server.cpp
  silkworm/node/stagedsync/stages/stage.hpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
Labels: maintenance

#1510 cmake: use Boost::headers for asio
  CMakeLists.txt
  cmd/api/CMakeLists.txt
  cmd/dev/CMakeLists.txt
  cmd/state-transition/CMakeLists.txt
  silkworm/infra/CMakeLists.txt
  silkworm/infra/test_util/CMakeLists.txt
  silkworm/node/CMakeLists.txt
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/common/CMakeLists.txt
  silkworm/sentry/discovery/disc_v4/CMakeLists.txt
  silkworm/sentry/discovery/node_db/CMakeLists.txt
  silkworm/silkrpc/CMakeLists.txt
Labels: maintenance

#1512 cmake: remove GRPC sanitizer defines
  cmake/compiler_settings.cmake
  cmake/toolchain/wasi.cmake
  cmd/test/CMakeLists.txt
  silkworm/infra/CMakeLists.txt
  silkworm/interfaces/CMakeLists.txt
  silkworm/node/CMakeLists.txt
  silkworm/sentry/CMakeLists.txt
  silkworm/silkrpc/CMakeLists.txt
Labels: maintenance

#1516 core: add collection of execution call traces
  silkworm/core/execution/call_tracer.cpp
  silkworm/core/execution/call_tracer.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/types/call_traces.hpp
Labels: enhancement

#1518 node: insert call traces in state buffer
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/state/in_memory_state.hpp
  silkworm/core/state/state.hpp
  silkworm/core/types/call_traces.hpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/buffer.hpp
  silkworm/silkrpc/core/local_state.hpp
  silkworm/silkrpc/core/override_state.hpp
  silkworm/silkrpc/core/remote_state.hpp
Labels: enhancement

#1520 wasm: fix missing includes after PR 1513
  silkworm/wasm/silkworm_wasm_api.cpp
Labels: maintenance

#1519 api: implement block execution flags for state changes and call traces
  silkworm/api/silkworm_api.cpp
  silkworm/core/execution/execution.hpp
Labels: c-api

#1521 node: fix snapshot max block after index building
  silkworm/node/db/buffer_test.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
Labels: maintenance

#1499 rpcdaemon: resolve errors found while browsing otterscan
  silkworm/silkrpc/commands/ots_api.cpp
Labels: maintenance

#1525 rpcdaemon: fix expected result in erigon_getLatestLogs integration test
  tests/integration/goerly/erigon_getLatestLogs/test_12.json
Labels: integration-test

#1508 tests: add custom port in integration test runner
  tests/integration/run_tests.py
Labels: maintenance

#1522 node: increase progress log interval during snapshot sync
  silkworm/node/snapshot/settings.hpp
  silkworm/node/snapshot/sync.cpp
Labels: maintenance

#1523 cmd: add more configuration settings for snapshot sync
  cmd/common/snapshot_options.cpp
Labels: enhancement

#1524 node: demote log traces in snapshot index building
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/snapshot/index.cpp
Labels: maintenance

#1533 node: open canonical chain before cleanup forward cycle
  silkworm/node/stagedsync/forks/canonical_chain.cpp
  silkworm/node/stagedsync/forks/canonical_chain.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
Labels: maintenance

#1531 sentry: co_spawn_sw crash in SerialNodeDb (#1530) - workaround
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/concurrency/timeout.hpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.hpp
Labels: maintenance

#1529 tests: configure integration tests to skip in error message comparison
  tests/integration/goerly/eth_callMany/test_09.json
  tests/integration/run_tests.py
Labels: integration-test

#1535 rpcdaemon: fix trace_filter without reward and after != 0
  silkworm/silkrpc/core/evm_trace.cpp
  tests/integration/goerly/trace_filter/test_06.tar
  tests/integration/goerly/trace_filter/test_07.tar
Labels: maintenance

#1537 node: implement historical previous incarnation
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/etl/collector.cpp
Labels: maintenance

#1538 cmd: add termination handler to silkworm executable
  cmd/common/settings.hpp
  cmd/silkworm.cpp
Labels: maintenance

#1540 node: fix for_last_n_headers invariant due to block 0 in db
  silkworm/node/db/access_layer.cpp
Labels: maintenance

#1542 node: use read header with snapshots in execution pipeline
  silkworm/node/stagedsync/execution_pipeline.cpp
Labels: snapshots, maintenance

#1541 api: implement recsplit index build
  cmd/api/execute.cpp
  cmd/api/sample-go-client/README.md
  cmd/api/sample-go-client/go.mod
  cmd/api/sample-go-client/main.go
  cmd/api/sample-go-client/silkworm.go
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
  silkworm/node/snapshot/index.cpp
  silkworm/node/snapshot/index.hpp
Labels: c-api

#1544 node: fix main chain initialization from snapshots
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
Labels: maintenance

#1546 snapshot: increase index bucket size
  silkworm/node/snapshot/index.hpp
Labels: snapshots, maintenance

#1543 rpcdaemon: ensure chain configuration is valid
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/core/call_many.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_trace.cpp
Labels: maintenance

#1549 tests: update README for performance tests
  tests/perf/README.md
Labels: documentation, perf-test

#1545 core: introduce hex_to_address
  cmd/dev/backend_kv_server.cpp
  cmd/dev/check_log_indices.cpp
  cmd/dev/snapshots.cpp
  cmd/state-transition/state_transition.cpp
  cmd/test/ethereum.cpp
  silkworm/core/chain/genesis_test.cpp
  silkworm/core/execution/address.cpp
  silkworm/core/execution/address.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/node/db/buffer_test.cpp
  silkworm/node/db/genesis.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/commands/txpool_api.cpp
  silkworm/silkrpc/core/account_dumper.cpp
  silkworm/silkrpc/core/block_reader.cpp
  silkworm/silkrpc/core/cached_chain_test.cpp
  silkworm/silkrpc/core/evm_access_list_tracer.cpp
  silkworm/silkrpc/core/evm_access_list_tracer.hpp
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/storage_walker.cpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/json/call.cpp
  silkworm/silkrpc/json/log.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/types/dump_account.cpp
  silkworm/wasm/silkworm_wasm_api.cpp
Labels: maintenance

#1539 cmd: add snapshots in check_changes tool
  cmd/dev/check_changes.cpp
  cmd/dev/toolbox.cpp
  silkworm/node/db/util.hpp
Labels: enhancement

#1550 tests: reorganize run_perf_test activation options
  tests/perf/run_perf_tests.py
Labels: perf-test

#1555 fix: typos
  silkworm/sync/README.md
  tests/perf/README.md
Labels: documentation

#1558 rpcdaemon: update API doc with integration and perf test coverage
  docs/JSON-RPC-API.md
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_08_30_eth_call.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_08_30_eth_getLogs.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_09_09_eth_call.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_09_09_eth_getLogs.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_09_24_eth_getBalance.txt
  tests/perf/reports/goerli/dell_g55587/PerfReport_2023_09_25_eth_getBlockByHash.txt
Labels: documentation

#1559 api: add termination signal handling in block execution
  silkworm/api/silkworm_api.cpp
  silkworm/api/silkworm_api.h
  silkworm/infra/common/log.cpp
  silkworm/infra/common/log.hpp
  silkworm/infra/concurrency/signal_handler.cpp
  silkworm/infra/concurrency/signal_handler.hpp
Labels: c-api

#1563 third_party: fix MDBX issues in UBSAN build
  .circleci/config.yml
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
  third_party/libmdbx/CMakeLists.txt
Labels: maintenance

#1556 cmake: common library targets
  CMakeLists.txt
  README.md
  cmake/cmake_format.yaml
  cmake/common/get_all_targets.cmake
  cmake/common/targets.cmake
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/common/CMakeLists.txt
  silkworm/sentry/discovery/common/CMakeLists.txt
  silkworm/sentry/discovery/disc_v4/CMakeLists.txt
  silkworm/sentry/discovery/enr/CMakeLists.txt
  silkworm/sentry/discovery/node_db/CMakeLists.txt
Labels: maintenance
