Repository erigontech/silkworm, pull requests merged in 2023-07, with the labels that each got.

#1305 node: fix highest_block_number
  silkworm/node/db/access_layer.cpp
Labels: bug, snapshot-sync

#1307 infra: fix silkworm_infra_test_util build on macOS
  silkworm/infra/test_util/dummy.cpp
Labels: maintenance

#1308 node: fix mask computation in EF decoding of snapshot index offsets
  silkworm/node/recsplit/encoding/elias_fano.hpp
  silkworm/node/recsplit/encoding/elias_fano_test.cpp
Labels: maintenance

#1309 node: add range check in header snapshot access by number
  silkworm/infra/common/ensure.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: maintenance

#1310 node: fix Elias-Fano 32-bit compressed list on MSVC
  silkworm/node/recsplit/encoding/elias_fano.hpp
Labels: maintenance

#1311 node: fix header numbers update after snapshot sync
  silkworm/node/snapshot/sync.cpp
Labels: bug, snapshot-sync

#1314 rpcdaemon: snapshot support in JSON RPC API [WIP]
  silkworm/core/chain/config.hpp
  silkworm/core/types/block.hpp
  silkworm/infra/concurrency/task.hpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/storage/chain_storage.hpp
  silkworm/node/storage/local_chain_storage.cpp
  silkworm/node/storage/local_chain_storage.hpp
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/account_walker_test.cpp
  silkworm/silkrpc/core/estimate_gas_oracle_test.cpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethdb/file/local_transaction.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/silkrpc/ethdb/kv/remote_database.cpp
  silkworm/silkrpc/ethdb/kv/remote_database.hpp
  silkworm/silkrpc/ethdb/kv/remote_database_test.cpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.cpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.hpp
  silkworm/silkrpc/ethdb/kv/state_changes_stream.hpp
  silkworm/silkrpc/ethdb/transaction.hpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
  silkworm/silkrpc/storage/remote_chain_storage.hpp
  silkworm/silkrpc/test/dummy_transaction.hpp
  silkworm/silkrpc/test/mock_transaction.hpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
Labels: snapshot-sync

#1313 cmd: add open_index command to snapshots tool
  cmd/dev/snapshots.cpp
  silkworm/core/common/assert.cpp
Labels: snapshot-sync

#1312 cmd: avoid unnecessary broken mdbx::env close in toolbox
  cmd/dev/toolbox.cpp
Labels: maintenance

#1315 rpcdaemon: refactoring DebugExecutor unit test step 1
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_debug_test.cpp
Labels: maintenance

#1320 node: add check prefix in huffman decompressor
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/huffman/decompressor_test.cpp
Labels: snapshots

#1321 node: add hash prefix check in lookup from snapshots
  cmd/dev/snapshots.cpp
  silkworm/node/snapshot/index_test.cpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/test/snapshots.hpp
Labels: snapshots

#1323 move block cache from rpcdaemon to core
  silkworm/core/common/block_cache.hpp
  silkworm/core/common/block_cache_test.cpp
  silkworm/core/types/block_test.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/erigon_api.hpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/parity_api.hpp
  silkworm/silkrpc/commands/trace_api.hpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/core/call_many.hpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/daemon.hpp
  silkworm/silkrpc/http/request_handler.cpp
  silkworm/silkrpc/http/server.cpp
  silkworm/silkrpc/test/context_test_base.cpp
Labels: maintenance

#1324 rpcdaemon: make eth_getBlockByNumber and eth_call work with snapshots
  cmd/README.md
  silkworm/infra/common/ensure.hpp
  silkworm/node/snapshot/index_test.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
  silkworm/sync/sync.cpp
Labels: snapshots, maintenance

#1325 node: refactor ROTxn commit
  cmd/common/db_checklist.cpp
  cmd/dev/toolbox.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/stagedsync/stages/_test.cpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_finish.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/sync/internals/body_sequence_test.cpp
Labels: maintenance

#1326 node: exclude snapshots tests in Windows build
  silkworm/node/snapshot/index_test.cpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: maintenance

#1327 node: refactor database ROTxn/RWTxn hierarchy
  cmd/common/db_checklist.cpp
  cmd/dev/backend_kv_server.cpp
  cmd/dev/check_changes.cpp
  cmd/dev/check_pow.cpp
  cmd/dev/check_senders.cpp
  cmd/dev/scan_txs.cpp
  cmd/dev/toolbox.cpp
  silkworm/node/backend/remote/grpc/kv_calls.cpp
  silkworm/node/backend/remote/grpc/kv_calls.hpp
  silkworm/node/db/db_utils_test.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation.hpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
  silkworm/node/db/memory_mutation_test.cpp
  silkworm/node/node.cpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/fork_test.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/stages/_test.cpp
  silkworm/node/stagedsync/stages/stage_bodies_test.cpp
  silkworm/node/stagedsync/stages/stage_headers_test.cpp
  silkworm/node/test/context.cpp
  silkworm/silkrpc/core/local_state.cpp
  silkworm/silkrpc/core/local_state.hpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/sync/internals/body_retrieval.hpp
  silkworm/sync/internals/body_sequence_test.cpp
  silkworm/sync/internals/header_retrieval.hpp
Labels: maintenance

#1329 node: fix Windows build after ROTxn/RWTxn refactoring
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
Labels: maintenance

#1334 node: more ROTxn/RWTxn refactoring
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
Labels: maintenance

#1328 node: fix block body txn counters in access layer
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/stages/_test.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
Labels: shanghai, maintenance

#1331 rpcdaemon: get block by hash with snapshot
  silkworm/silkrpc/commands/eth_api.cpp
  tests/integration/goerly/eth_getBlockByNumber/test_12.json
Labels: snapshots

#1339 snapshots: fix TemporaryFile for unit tests on Windows
  silkworm/node/snapshot/index_test.cpp
  silkworm/node/snapshot/repository_test.cpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/test/files.hpp
Labels: snapshots, maintenance

#1338 logging: adjust log levels
  cmd/common/db_checklist.cpp
  cmd/silkworm.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/server/server.hpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/node/backend/remote/backend_kv_server.cpp
  silkworm/node/bittorrent/client.cpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/sync.cpp
  silkworm/sentry/message_receiver.cpp
  silkworm/sentry/peer_manager_api.cpp
  silkworm/sync/block_exchange.cpp
Labels: maintenance

#1330 rpcdaemon: add ots_searchTransactionsAfter and ots_searchTransactionsBefore API
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/account_walker_test.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethdb/cursor.hpp
  silkworm/silkrpc/ethdb/file/local_cursor.cpp
  silkworm/silkrpc/ethdb/file/local_cursor.hpp
  silkworm/silkrpc/ethdb/kv/remote_cursor.cpp
  silkworm/silkrpc/ethdb/kv/remote_cursor.hpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/test/mock_cursor.hpp
  silkworm/silkrpc/types/block.hpp
  tests/integration/goerly/ots_searchTransactionsAfter/test_1.json
  tests/integration/goerly/ots_searchTransactionsBefore/test_1.json
Labels: rpc-api

#1345 rpcdaemon: enable block cache insertion in APIs supporting snapshots
  silkworm/silkrpc/commands/eth_api.cpp
Labels: snapshots

#1319 rpcdaemon: debug_accountAt API
  docs/JSON-RPC-API.md
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_executor.hpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/debug_accountAt/test_01.tar
  tests/integration/goerly/debug_accountAt/test_02.tar
  tests/integration/goerly/debug_accountAt/test_03.tar
  tests/integration/goerly/debug_accountAt/test_04.json
  tests/integration/goerly/debug_accountAt/test_05.json
  tests/integration/goerly/debug_accountAt/test_06.json
  tests/integration/goerly/debug_accountAt/test_07.json
  tests/integration/goerly/debug_accountAt/test_08.tar
  tests/integration/goerly/debug_accountAt/test_09.json
  tests/integration/goerly/debug_accountAt/test_10.json
  tests/integration/goerly/debug_accountAt/test_11.json
  tests/integration/run_tests.py
Labels: rpc-api

#1347 rpcdaemon: fix compilation on macOS broken after PR 1319
  silkworm/silkrpc/commands/debug_api.cpp
Labels: maintenance

#1349 rpcdaemon: move chain storage from node
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/account_walker_test.cpp
  silkworm/silkrpc/core/storage_walker_test.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.cpp
  silkworm/silkrpc/ethdb/file/local_transaction.hpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.cpp
  silkworm/silkrpc/ethdb/kv/remote_transaction.hpp
  silkworm/silkrpc/ethdb/transaction.hpp
  silkworm/silkrpc/storage/chain_storage.hpp
  silkworm/silkrpc/storage/local_chain_storage.cpp
  silkworm/silkrpc/storage/local_chain_storage.hpp
  silkworm/silkrpc/storage/remote_chain_storage.hpp
  silkworm/silkrpc/test/dummy_transaction.hpp
  silkworm/silkrpc/test/mock_transaction.hpp
Labels: maintenance

#1342 rpcdaemon: eth_getBlockTransactionCountBy* rework for snapshots
  silkworm/silkrpc/commands/eth_api.cpp
  tests/integration/goerly/eth_getBlockTransactionCountByHash/test_2.json
  tests/integration/goerly/eth_getBlockTransactionCountByNumber/test_8.json
Labels: snapshots

#1350 sync: make chain sync run onto the Engine RPC unique context
  silkworm/silkrpc/daemon.hpp
  silkworm/sync/internals/chain_fork_view.cpp
  silkworm/sync/internals/chain_fork_view.hpp
  silkworm/sync/sentry_client.cpp
  silkworm/sync/sync.cpp
Labels: maintenance

#1346 rpcdaemon: handle incomplete request buffers using picohttpparse
  silkworm/silkrpc/http/connection.cpp
  silkworm/silkrpc/http/request.hpp
  silkworm/silkrpc/http/request_parser.cpp
  silkworm/silkrpc/http/request_parser.hpp
  silkworm/silkrpc/http/request_parser_test.cpp
  silkworm/silkrpc/http/request_test.cpp
Labels: enhancement

#1351 rpcdaemon: extract block cache for chain storage access
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
Labels: maintenance

#1356 node: remove index file when created before snapshot file
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot_test.cpp
Labels: snapshots

#1354 rpcdaemon: rework on eth_getUncleByBlockHashAndIndex and eth_getUncleByBlockNumberAndIndex for snapshot
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  tests/integration/goerly/eth_getUncleByBlockHashAndIndex/test_2.json
  tests/integration/goerly/eth_getUncleByBlockNumberAndIndex/test_4.json
Labels: maintenance

#1358 rpcdaemon: rework on eth_gasPrice and eth_createAccessList for snapshots
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  tests/integration/goerly/eth_createAccessList/test_5.json
Labels: snapshots

#1359 node: last N headers from snapshots
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/node/db/db_utils.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
Labels: snapshots

#1362 rpcdaemon: trace_call trace_block trace_callMany traceRawTransaction trace_replayBlockTransaction w/ snapshots
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/commands/trace_api.hpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
Labels: maintenance

#1361 sync: fix prefetch of block headers in PoS downloader
  silkworm/sync/sync_pos.cpp
Labels: maintenance

#1360 cmd: improve dump in snapshots tool
  cmd/README.md
  cmd/dev/snapshots.cpp
Labels: snapshots

#1363 rpcdaemon: debug_accountAt debug_traceCall debug_traceCallMany debug_traceBlockByNumber debug_traceBlockByHash w/ snapshots
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_debug.hpp
Labels: snapshots

#1364 node: commit on db once every inserted block batch
  silkworm/node/stagedsync/forks/main_chain.cpp
Labels: pos-sync

#1374 build: enable position-independent code for all builds
  .circleci/config.yml
  cmake/compiler_settings.cmake
Labels: c-api

#1375 node: fix reading zero transactions from snapshot
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
Labels: snapshots

#1376 node: fix spurious txns reading from snapshot
  silkworm/node/snapshot/snapshot.cpp
Labels: snapshots

#1365 tests: cleanup unit test loop launcher and add some doc
  tests/unit/README.md
  tests/unit/run_unit_test_loop.py
Labels: documentation, unit-test

#1368 rpcdaemon: eth_getUncleCountByBlockHash eth_getUncleCountByBlockNumber debug_accountRanges w/ snapshots
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/core/account_dumper.cpp
  silkworm/silkrpc/core/account_dumper.hpp
  silkworm/silkrpc/core/account_dumper_test.cpp
Labels: snapshots

#1369 rpcdaemon: adapt some erigon API to snapshots
  silkworm/silkrpc/commands/erigon_api.cpp
Labels: snapshots

#1377 rpcdaemon: add 4 missing erigon API (empty implementation)
  silkworm/silkrpc/commands/erigon_api.cpp
  silkworm/silkrpc/commands/erigon_api.hpp
Labels: json-rpc-api

#1372 rpcdaemon: adapt eth_getRawTransactionByBlock... and eth_getTransactionByBlock to snapshots
  silkworm/silkrpc/commands/eth_api.cpp
Labels: snapshots

#1373 tests: add option -f to show only failed test in integration test runner
  tests/integration/run_tests.py
Labels: integration-test

#1366 doc: upgrade contributing guide
  docs/CONTRIBUTING.md
Labels: documentation

#1381 cmd: add command-line parameters in C API execute tool
  cmd/api/CMakeLists.txt
  cmd/api/execute.cpp
  silkworm/api/silkworm_api.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
Labels: c-api

#1370 rpcdaemon: implement debug_getRaw* endpoints
  docs/JSON-RPC-API.md
  silkworm/core/common/util.hpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/access_layer.hpp
  silkworm/silkrpc/commands/debug_api.cpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/commands/rpc_api_test.cpp
  silkworm/silkrpc/core/blocks.cpp
  silkworm/silkrpc/core/blocks_test.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/storage/chain_storage.hpp
  silkworm/silkrpc/storage/local_chain_storage.cpp
  silkworm/silkrpc/storage/local_chain_storage.hpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
  silkworm/silkrpc/storage/remote_chain_storage.hpp
Labels: json-rpc-api

#1383 cmd: reset PlainState in toolbox by clearing and reapplying genesis allocations
  cmd/dev/toolbox.cpp
  silkworm/node/db/genesis.cpp
  silkworm/node/db/genesis.hpp
Labels: maintenance

#1384 node: fix state buffer for usage with snapshots
  silkworm/node/db/buffer.cpp
  silkworm/node/db/buffer.hpp
Labels: snapshots

#1385 rpcdaemon: add senders into block cache
  silkworm/silkrpc/core/cached_chain.cpp
Labels: snapshots, maintenance

#1386 tests: improve usage in integration test runner and expand readme
  tests/integration/README.md
  tests/integration/run_tests.py
Labels: documentation, integration-test

#1387 cmd: fix snapshot segment and index paths in C API execute tool
  cmd/api/CMakeLists.txt
  cmd/api/execute.cpp
  silkworm/api/silkworm_api.cpp
Labels: c-api

#1388 rpcdaemon: remove tx database from get_block_by_number in cached_chain
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/core/blocks.cpp
  silkworm/silkrpc/core/cached_chain.cpp
  silkworm/silkrpc/core/cached_chain.hpp
  silkworm/silkrpc/core/evm_debug.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/storage/remote_chain_storage.cpp
Labels: maintenance
