Repository erigontech/silkworm, pull requests merged in 2023-05, with the labels that each got.

#1037 core: fix multi-thread access in lru_cache
  silkworm/core/common/lru_cache.hpp
  silkworm/core/execution/evm.cpp
Labels: maintenance

#1041 node: add snapshot index reopening
  silkworm/node/db/tables.hpp
  silkworm/node/huffman/decompressor.hpp
  silkworm/node/snapshot/path.cpp
  silkworm/node/snapshot/path.hpp
  silkworm/node/snapshot/repository.cpp
  silkworm/node/snapshot/repository.hpp
  silkworm/node/snapshot/settings.hpp
  silkworm/node/snapshot/snapshot.cpp
  silkworm/node/snapshot/snapshot.hpp
  silkworm/node/snapshot/snapshot_test.cpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/snapshot/sync.hpp
  silkworm/node/snapshot/sync_test.cpp
Labels: snapshot-sync

#1044 rpcdaemon: add eth_getTransactionReceiptsByBlock API
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/http/methods.hpp
Labels: rpc-api

#1048 rpcdaemon: separate payload attributes json module
  silkworm/silkrpc/json/payload_attributes.cpp
  silkworm/silkrpc/json/payload_attributes.hpp
  silkworm/silkrpc/json/payload_attributes_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1042 sentry: rename rpc folder as grpc
  cmd/backend_kv_server.cpp
  cmd/silkworm.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/infra/concurrency/context_pool_test.cpp
  silkworm/node/backend/remote/grpc/backend_calls.cpp
  silkworm/sentry/grpc/client/sentry_client.cpp
  silkworm/sentry/grpc/client/sentry_client.hpp
  silkworm/sentry/grpc/interfaces/eth_version.cpp
  silkworm/sentry/grpc/interfaces/eth_version.hpp
  silkworm/sentry/grpc/interfaces/message.cpp
  silkworm/sentry/grpc/interfaces/message.hpp
  silkworm/sentry/grpc/interfaces/node_info.cpp
  silkworm/sentry/grpc/interfaces/node_info.hpp
  silkworm/sentry/grpc/interfaces/peer_event.cpp
  silkworm/sentry/grpc/interfaces/peer_event.hpp
  silkworm/sentry/grpc/interfaces/peer_id.cpp
  silkworm/sentry/grpc/interfaces/peer_id.hpp
  silkworm/sentry/grpc/interfaces/peer_info.cpp
  silkworm/sentry/grpc/interfaces/peer_info.hpp
  silkworm/sentry/grpc/interfaces/sent_peer_ids.cpp
  silkworm/sentry/grpc/interfaces/sent_peer_ids.hpp
  silkworm/sentry/grpc/interfaces/status_data.cpp
  silkworm/sentry/grpc/interfaces/status_data.hpp
  silkworm/sentry/grpc/server/server.cpp
  silkworm/sentry/grpc/server/server.hpp
  silkworm/sentry/grpc/server/server_calls.hpp
  silkworm/sentry/sentry.cpp
Labels: maintenance

#1049 build: fix interface symlinks when switching Conan/Hunter
  silkworm/interfaces/generate_grpc.cmake
Labels: maintenance

#1047 core: extract UnsignedTransaction
  silkworm/core/common/test_util.cpp
  silkworm/core/execution/execution_test.cpp
  silkworm/core/execution/processor_test.cpp
  silkworm/core/protocol/intrinsic_gas.cpp
  silkworm/core/protocol/intrinsic_gas.hpp
  silkworm/core/protocol/intrinsic_gas_test.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/trie/vector_root_test.cpp
  silkworm/core/types/block_test.cpp
  silkworm/core/types/receipt.cpp
  silkworm/core/types/receipt.hpp
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/core/types/transaction_test.cpp
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/snapshot/index.cpp
  silkworm/node/stagedsync/stages/_test.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/common/util.cpp
  silkworm/silkrpc/common/util.hpp
  silkworm/silkrpc/common/util_test.cpp
  silkworm/silkrpc/core/cached_chain_test.cpp
  silkworm/silkrpc/core/evm_trace_test.cpp
  silkworm/silkrpc/core/rawdb/chain_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/transaction_test.cpp
Labels: maintenance

#1053 infra: add gRPC client context pool and services
  silkworm/infra/concurrency/base_service.hpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/private_service.hpp
  silkworm/infra/concurrency/private_service_test.cpp
  silkworm/infra/concurrency/shared_service.hpp
  silkworm/infra/concurrency/shared_service_test.cpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/infra/grpc/client/client_context_pool_test.cpp
Labels: maintenance

#1058 rpcdaemon: separete transaction configuration json module
  silkworm/silkrpc/json/transition_configuration.cpp
  silkworm/silkrpc/json/transition_configuration.hpp
  silkworm/silkrpc/json/transition_configuration_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1066 sync: update docs, do cleanup and fix
  docs/imgs/blockexchange_structure.png
  docs/imgs/downloader_structure.png
  docs/imgs/sync_execution_structure.png
  silkworm/node/db/memory_mutation.cpp
  silkworm/node/db/memory_mutation.hpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
  silkworm/node/db/memory_mutation_test.cpp
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/extending_fork.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/local_client.hpp
  silkworm/node/stagedsync/remote_client.hpp
  silkworm/node/stagedsync/server.hpp
  silkworm/node/stagedsync/types.hpp
  silkworm/sync/README.md
Labels: pos-sync

#1069 infra: use raw pointers for context services
  silkworm/infra/concurrency/private_service.hpp
  silkworm/infra/concurrency/private_service_test.cpp
  silkworm/infra/concurrency/shared_service.hpp
  silkworm/infra/concurrency/shared_service_test.cpp
  silkworm/silkrpc/commands/admin_api.hpp
  silkworm/silkrpc/commands/debug_api.hpp
  silkworm/silkrpc/commands/debug_api_test.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/erigon_api.hpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/commands/eth_api_test.cpp
  silkworm/silkrpc/commands/net_api.hpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/parity_api.hpp
  silkworm/silkrpc/commands/parity_api_test.cpp
  silkworm/silkrpc/commands/trace_api.hpp
  silkworm/silkrpc/commands/trace_api_test.cpp
  silkworm/silkrpc/commands/txpool_api.hpp
  silkworm/silkrpc/commands/web3_api.hpp
  silkworm/silkrpc/commands/web3_api_test.cpp
  silkworm/silkrpc/ethdb/kv/state_changes_stream.cpp
  silkworm/silkrpc/test/context_test_base.cpp
Labels: maintenance

#1070 fix: avoid startup crash in backend_kv_server
  cmd/backend_kv_server.cpp
Labels: maintenance

#1075 node: improve execution client and server
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/local_client.hpp
  silkworm/node/stagedsync/local_client_test.cpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/remote_client.hpp
  silkworm/node/stagedsync/remote_client_test.cpp
  silkworm/node/stagedsync/server.hpp
Labels: maintenance

#1079 sync : add Engine API RPC server
  cmd/silkworm.cpp
  silkworm/silkrpc/ethdb/kv/state_changes_stream.cpp
  silkworm/sync/CMakeLists.txt
  silkworm/sync/chain_sync.cpp
  silkworm/sync/chain_sync.hpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/engine_apis/structs.cpp
  silkworm/sync/engine_apis/structs.hpp
  silkworm/sync/internals/types.hpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
  silkworm/sync/sync_pow.cpp
  silkworm/sync/sync_pow.hpp
Labels: pos-sync

#1083 sync: fix startup sequence
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1084 rpcdaemon: enable KV protocol check also with local file
  silkworm/silkrpc/daemon.cpp
Labels: maintenance

#1085 rpcdaemon: separate node info json module
  silkworm/silkrpc/json/node_info.cpp
  silkworm/silkrpc/json/node_info.hpp
  silkworm/silkrpc/json/node_info_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
Labels: maintenance

#1087 adjust thread name size in log traces
  cmd/silkworm.cpp
  silkworm/infra/common/log.cpp
  silkworm/node/snapshot/sync.cpp
  silkworm/sync/block_exchange.cpp
Labels: maintenance

#1092 rpcdaemon: improve Engine API error handling
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/protocol/errors.hpp
Labels: rpc-api

#1094 rpcdaemon: add engine_exchangeCapabilities API
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/types/execution_payload.hpp
  tests/integration/goerly/engine_exchangeCapabilities/test_1.json
Labels: rpc-api

#1113 build: link `mimalloc` as shared library
  cmd/rpcdaemon/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: maintenance

#1114 rpcdaemon: enable admin API namespace by default
  silkworm/silkrpc/common/constants.hpp
Labels: maintenance

#1115 rpcdaemon: fix usage of daemon settings
  silkworm/silkrpc/daemon.cpp
Labels: maintenance

#1116 test: add missing python modules for integration test runner
  requirements.txt
  tests/integration/README.md
Labels: maintenance

#1093 infra: move gRPC version check
  cmd/test/CMakeLists.txt
  silkworm/infra/grpc/common/version.cpp
  silkworm/infra/grpc/common/version.hpp
  silkworm/infra/grpc/common/version_test.cpp
  silkworm/silkrpc/daemon.hpp
Labels: maintenance

#1076 build: explicit SILKWORM_CORE_USE_ABSEIL
  .circleci/config.yml
  CMakeLists.txt
  cmd/test/CMakeLists.txt
  silkworm/core/CMakeLists.txt
  silkworm/core/common/hash_maps.hpp
  silkworm/sentry/CMakeLists.txt
Labels: maintenance

#1118 rpcdaemon, sync: rename existing Engine API with suffix V1
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/core/filter_storage.cpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend_test.cpp
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload.hpp
  silkworm/silkrpc/json/execution_payload_test.cpp
  silkworm/silkrpc/json/fork_choice.cpp
  silkworm/silkrpc/json/fork_choice.hpp
  silkworm/silkrpc/json/fork_choice_test.cpp
  silkworm/silkrpc/json/payload_attributes.cpp
  silkworm/silkrpc/json/payload_attributes.hpp
  silkworm/silkrpc/json/payload_attributes_test.cpp
  silkworm/silkrpc/json/transition_configuration.cpp
  silkworm/silkrpc/json/transition_configuration.hpp
  silkworm/silkrpc/json/transition_configuration_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/execution_payload.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
Labels: maintenance

#1121 cmd: add temporary switch to force PoW (will be removed)
  cmd/common/settings.hpp
  cmd/silkworm.cpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1125 rpcdaemon: avoid unnecessary bitmap include leak
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api.hpp
  silkworm/silkrpc/ethdb/bitmap.cpp
  silkworm/silkrpc/ethdb/bitmap.hpp
Labels: maintenance

#1123 cmd: refactor structure to separate dev tools from key components
  cmd/CMakeLists.txt
  cmd/common/CMakeLists.txt
  cmd/common/db_checklist.cpp
  cmd/common/db_checklist.hpp
  cmd/dev/CMakeLists.txt
  cmd/dev/backend_kv_server.cpp
  cmd/dev/check_blockhashes.cpp
  cmd/dev/check_changes.cpp
  cmd/dev/check_hashstate.cpp
  cmd/dev/check_pow.cpp
  cmd/dev/check_senders.cpp
  cmd/dev/check_tx_lookup.cpp
  cmd/dev/embed.cpp
  cmd/dev/genesistool.cpp
  cmd/dev/grpc_toolbox.cpp
  cmd/dev/scan_txs.cpp
  cmd/dev/snapshots.cpp
  cmd/dev/toolbox.cpp
  cmd/rpcdaemon.cpp
  cmd/rpcdaemon/CMakeLists.txt
  cmd/rpcdaemon/ethbackend.cpp
  cmd/rpcdaemon/ethbackend_async.cpp
  cmd/rpcdaemon/ethbackend_coroutines.cpp
  cmd/rpcdaemon/kv_seek.cpp
  cmd/rpcdaemon/kv_seek_async.cpp
  cmd/rpcdaemon/kv_seek_async_callback.cpp
  cmd/rpcdaemon/kv_seek_async_coroutines.cpp
  cmd/rpcdaemon/kv_seek_both.cpp
  cmd/rpcdaemon/silkrpc_toolbox.cpp
  cmd/silkworm.cpp
  silkworm/node/CMakeLists.txt
Labels: maintenance

#1128 node: withdrawals in BlockBodyForStorage::encode
  silkworm/node/db/util.cpp
  silkworm/node/db/util.hpp
  silkworm/node/db/util_test.cpp
Labels: shanghai

#1127 rpcdaemon, sync: Engine API versioning
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend_test.cpp
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload.hpp
  silkworm/silkrpc/json/execution_payload_test.cpp
  silkworm/silkrpc/json/fork_choice.cpp
  silkworm/silkrpc/json/fork_choice.hpp
  silkworm/silkrpc/json/fork_choice_test.cpp
  silkworm/silkrpc/json/payload_attributes.cpp
  silkworm/silkrpc/json/payload_attributes.hpp
  silkworm/silkrpc/json/payload_attributes_test.cpp
  silkworm/silkrpc/json/transition_configuration.cpp
  silkworm/silkrpc/json/transition_configuration.hpp
  silkworm/silkrpc/json/transition_configuration_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/types_test.cpp
  silkworm/silkrpc/types/execution_payload.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
Labels: maintenance

#1132 rpc: add JSON codec for engine_newPayloadV2 types
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload_test.cpp
  silkworm/silkrpc/json/transition_configuration.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/json/withdrawal.cpp
  silkworm/silkrpc/json/withdrawal.hpp
  silkworm/silkrpc/json/withdrawal_test.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
Labels: shanghai, pos-sync, rpc-api

#1133 node, sync: fix verification at head in execution
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/sync/internals/body_sequence.cpp
  silkworm/sync/internals/body_sequence.hpp
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/internals/header_chain.hpp
Labels: bug

#1134 rpcdaemon: add withdrawals in returned blocks
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/types/block.cpp
Labels: shanghai

#1135 node: fix pipeline state using stop_at_block env var
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/stages/stage_finish.cpp
Labels: bug

#1136 core: extract withdrawals root computation
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/protocol/validation_test.cpp
Labels: shanghai

#1138 rpcdaemon, sync: add engine_newPayloadV2 API
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend_test.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/sync/sync_pos.cpp
  tests/integration/goerly/engine_newPayloadV2/test_1.json
Labels: shanghai, pos-sync

#1139 rpcdaemon: optimisation in read body
  silkworm/silkrpc/core/rawdb/chain.cpp
Labels: maintenance

#1141 rpcdaemon, sync: add engine_getPayloadV2 API
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend_test.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload.hpp
  silkworm/silkrpc/json/execution_payload_test.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/types/execution_payload.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
  tests/integration/goerly/engine_getPayloadV2/test_1.json
Labels: shanghai, pos-sync

#1144 rpcdaemon: separate access_list_entry json module
  silkworm/silkrpc/json/access_list_entry.cpp
  silkworm/silkrpc/json/access_list_entry.hpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
Labels: maintenance

#1151 infra: move awaitable timeout from sentry
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/concurrency/timeout.hpp
  silkworm/infra/concurrency/timeout_test.cpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/rlpx/auth/auth_initiator.cpp
  silkworm/sentry/rlpx/auth/auth_recipient.cpp
  silkworm/sentry/rlpx/auth/handshake.cpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1149 rpcdaemon, sync: add engine_forkchoiceUpdatedV2 API
  .circleci/config.yml
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/protocol/errors.hpp
  silkworm/silkrpc/types/execution_payload.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
  tests/integration/goerly/engine_forkchoiceUpdatedV2/test_1.json
Labels: shanghai, pos-sync

#1152 infra, sentry: fix wrong timeout namespace
  silkworm/infra/concurrency/timeout.cpp
  silkworm/infra/concurrency/timeout.hpp
  silkworm/infra/concurrency/timeout_test.cpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/rlpx/auth/auth_initiator.cpp
  silkworm/sentry/rlpx/auth/auth_recipient.cpp
  silkworm/sentry/rlpx/auth/handshake.cpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1154 Fix conversion warnings
  CMakeLists.txt
  cmake/compiler_settings.cmake
  cmake/compiler_warnings.cmake
  cmd/test/backend_kv_test.cpp
  silkworm/core/common/util.cpp
  silkworm/core/common/util.hpp
  silkworm/core/common/util_test.cpp
  silkworm/core/crypto/rmd160.c
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/precompile.cpp
  silkworm/core/protocol/blockchain.cpp
  silkworm/core/rlp/encode.cpp
  silkworm/core/state/intra_block_state_test.cpp
  silkworm/core/trie/hash_builder.cpp
  silkworm/core/trie/hash_builder_test.cpp
  silkworm/core/trie/nibbles.cpp
  silkworm/infra/common/measure.hpp
  silkworm/infra/concurrency/signal_handler.cpp
  silkworm/node/db/bitmap.hpp
  silkworm/node/huffman/decompressor.cpp
  silkworm/node/recsplit/rec_split.hpp
  silkworm/sentry/common/random.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/common/util.cpp
  silkworm/silkrpc/common/util.hpp
  silkworm/silkrpc/core/account_dumper_test.cpp
  silkworm/silkrpc/core/evm_debug.hpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/core/evm_trace_test.cpp
  silkworm/silkrpc/core/fee_history_oracle.cpp
  silkworm/silkrpc/core/rawdb/chain.cpp
  silkworm/silkrpc/core/storage_walker.cpp
  silkworm/silkrpc/core/storage_walker.hpp
  silkworm/silkrpc/ethdb/bitmap.cpp
  silkworm/silkrpc/ethdb/bitmap.hpp
  silkworm/silkrpc/ethdb/cursor.cpp
  silkworm/silkrpc/ethdb/transaction_database.cpp
  silkworm/silkrpc/http/request_parser.cpp
  silkworm/silkrpc/json/types.cpp
  silkworm/silkrpc/json/types.hpp
  silkworm/silkrpc/types/error.hpp
  third_party/CMakeLists.txt
Labels: maintenance

#1155 rpcdaemon, sync: add engine_getPayloadBodiesByHashV1 API
  silkworm/infra/grpc/common/conversion.cpp
  silkworm/infra/grpc/common/conversion.hpp
  silkworm/silkrpc/commands/engine_api.cpp
  silkworm/silkrpc/commands/engine_api.hpp
  silkworm/silkrpc/commands/engine_api_test.cpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/ethbackend/backend.hpp
  silkworm/silkrpc/ethbackend/remote_backend.cpp
  silkworm/silkrpc/ethbackend/remote_backend.hpp
  silkworm/silkrpc/http/methods.hpp
  silkworm/silkrpc/json/execution_payload.cpp
  silkworm/silkrpc/json/execution_payload.hpp
  silkworm/silkrpc/json/execution_payload_test.cpp
  silkworm/silkrpc/types/execution_payload.cpp
  silkworm/silkrpc/types/execution_payload.hpp
  silkworm/silkrpc/types/execution_payload_test.cpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
  tests/integration/goerly/engine_getPayloadBodiesByHashV1/test_1.json
  tests/integration/goerly/engine_getPayloadBodiesByHashV1/test_2.json
Labels: shanghai, pos-sync

#1163 interfaces: remove 3.14.0
  silkworm/interfaces/3.14.0/execution/execution.grpc.pb.cc
  silkworm/interfaces/3.14.0/execution/execution.grpc.pb.h
  silkworm/interfaces/3.14.0/execution/execution.pb.cc
  silkworm/interfaces/3.14.0/execution/execution.pb.h
  silkworm/interfaces/3.14.0/execution/execution_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/p2psentry/sentry.grpc.pb.cc
  silkworm/interfaces/3.14.0/p2psentry/sentry.grpc.pb.h
  silkworm/interfaces/3.14.0/p2psentry/sentry.pb.cc
  silkworm/interfaces/3.14.0/p2psentry/sentry.pb.h
  silkworm/interfaces/3.14.0/p2psentry/sentry_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/remote/ethbackend.grpc.pb.cc
  silkworm/interfaces/3.14.0/remote/ethbackend.grpc.pb.h
  silkworm/interfaces/3.14.0/remote/ethbackend.pb.cc
  silkworm/interfaces/3.14.0/remote/ethbackend.pb.h
  silkworm/interfaces/3.14.0/remote/ethbackend_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/remote/kv.grpc.pb.cc
  silkworm/interfaces/3.14.0/remote/kv.grpc.pb.h
  silkworm/interfaces/3.14.0/remote/kv.pb.cc
  silkworm/interfaces/3.14.0/remote/kv.pb.h
  silkworm/interfaces/3.14.0/remote/kv_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/txpool/mining.grpc.pb.cc
  silkworm/interfaces/3.14.0/txpool/mining.grpc.pb.h
  silkworm/interfaces/3.14.0/txpool/mining.pb.cc
  silkworm/interfaces/3.14.0/txpool/mining.pb.h
  silkworm/interfaces/3.14.0/txpool/mining_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/txpool/txpool.grpc.pb.cc
  silkworm/interfaces/3.14.0/txpool/txpool.grpc.pb.h
  silkworm/interfaces/3.14.0/txpool/txpool.pb.cc
  silkworm/interfaces/3.14.0/txpool/txpool.pb.h
  silkworm/interfaces/3.14.0/txpool/txpool_mock.grpc.pb.h
  silkworm/interfaces/3.14.0/types/types.pb.cc
  silkworm/interfaces/3.14.0/types/types.pb.h
Labels: maintenance

#1164 rpcdaemon: add flag to skip gRPC protocol check
  cmd/rpcdaemon.cpp
  silkworm/silkrpc/daemon.cpp
  silkworm/silkrpc/daemon.hpp
Labels: maintenance

#1168 infra: update thread pool
  cmd/test/ethereum.cpp
  silkworm/infra/concurrency/thread_pool.hpp
  silkworm/node/snapshot/sync.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
Labels: maintenance

#1167 execution: implement remaining getters
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/server.cpp
Labels: pos-sync

#1169 execution: some fixes
  docs/imgs/sync_execution_structure.png
  silkworm/infra/common/directories.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/extending_fork.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
Labels: bug, pos-sync

#1170 db: create cursors polymorphically
  silkworm/node/db/access_layer.cpp
Labels: pos-sync

#1173 CI: move format check from integration to light
  .circleci/config.yml
  cmd/CMakeLists.txt
Labels: maintenance

#1175 execution: some fixes
  cmd/common/common.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/fork.cpp
Labels: bug, pos-sync

#1181 infra: add awaitable promise test for cancellation after read
  silkworm/infra/concurrency/awaitable_future_test.cpp
Labels: maintenance

#1182 cmd: fix validation for --api rpcdaemon option
  cmd/common/rpcdaemon_options.cpp
Labels: maintenance

#1174 core: prohibit leftover input after RLP decoding by default
  cmd/test/ethereum.cpp
  silkworm/core/common/decoding_result.hpp
  silkworm/core/execution/address.cpp
  silkworm/core/rlp/decode.cpp
  silkworm/core/rlp/decode.hpp
  silkworm/core/rlp/decode_test.cpp
  silkworm/core/rlp/decode_vector.hpp
  silkworm/core/rlp/encode.cpp
  silkworm/core/rlp/encode.hpp
  silkworm/core/types/account.cpp
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/core/types/transaction.cpp
  silkworm/core/types/transaction.hpp
  silkworm/core/types/transaction_test.cpp
  silkworm/core/types/withdrawal.cpp
  silkworm/core/types/withdrawal.hpp
  silkworm/node/db/util.cpp
  silkworm/sentry/eth/fork_id.cpp
  silkworm/sentry/eth/fork_id.hpp
  silkworm/sentry/eth/status_message.cpp
  silkworm/sentry/rlpx/auth/auth_ack_message.cpp
  silkworm/sentry/rlpx/auth/auth_message.cpp
  silkworm/sentry/rlpx/auth/hello_message.cpp
  silkworm/sentry/rlpx/rlpx_common/disconnect_message.cpp
  silkworm/silkrpc/commands/eth_api.cpp
  silkworm/silkrpc/commands/eth_api_test.cpp
  silkworm/silkrpc/commands/trace_api.cpp
  silkworm/silkrpc/commands/txpool_api.cpp
  silkworm/silkrpc/common/util.cpp
  silkworm/silkrpc/common/util_test.cpp
  silkworm/sync/messages/inbound_new_block_hashes.cpp
  silkworm/sync/packets/block_bodies_packet.hpp
  silkworm/sync/packets/block_headers_packet.hpp
  silkworm/sync/packets/get_block_bodies_packet.hpp
  silkworm/sync/packets/get_block_headers_packet.hpp
  silkworm/sync/packets/hash_or_number.hpp
  silkworm/sync/packets/new_block_hashes_packet.hpp
  silkworm/sync/packets/new_block_packet.hpp
  silkworm/sync/packets/packet_coding_test.cpp
  silkworm/sync/packets/rlp_decoding.cpp
  silkworm/sync/packets/rlp_eth66_packet_coding.hpp
  silkworm/wasm/silkworm_wasm_api.cpp
Labels: maintenance

#1185 infra: handle cancellation in awaitable promise and future
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/infra/concurrency/awaitable_future_test.cpp
Labels: maintenance

#1186 sentry: set value in Peer handshake promise only once
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1189 rpcdaemon: add ots_getTransactionError API
  silkworm/silkrpc/API.md
  silkworm/silkrpc/commands/ots_api.cpp
  silkworm/silkrpc/commands/ots_api.hpp
  silkworm/silkrpc/commands/rpc_api_table.cpp
  silkworm/silkrpc/core/evm_trace.cpp
  silkworm/silkrpc/core/evm_trace.hpp
  silkworm/silkrpc/http/methods.hpp
  tests/integration/goerly/ots_getTransactionError/test_1.json
Labels: rpc-api

#1190 rpcdaemon: LocalState transaction must be created on worker thread
  silkworm/silkrpc/core/local_state.cpp
  silkworm/silkrpc/core/local_state.hpp
  silkworm/silkrpc/ethdb/file/local_transaction.cpp
Labels: maintenance

#1156 core: drop support of evmone advanced interpreter
  CMakeLists.txt
  cmake/compiler_settings.cmake
  cmd/CMakeLists.txt
  cmd/dev/check_changes.cpp
  cmd/dev/scan_txs.cpp
  cmd/test/ethereum.cpp
  examples/CMakeLists.txt
  silkworm/core/execution/analysis_cache.cpp
  silkworm/core/execution/analysis_cache.hpp
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/execution.hpp
  silkworm/core/protocol/blockchain.hpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_execution.hpp
  silkworm/silkrpc/core/evm_executor.cpp
  silkworm/silkrpc/core/evm_executor.hpp
Labels: maintenance

#1198 cmake: secp256k1 - remove obsolete flags
  cmake/cmake_format.cmake
  third_party/CMakeLists.txt
Labels: maintenance

#1192 rpcdaemon: add net in list of all API namespaces
  cmd/common/rpcdaemon_options.cpp
  silkworm/silkrpc/common/constants.hpp
Labels: maintenance

#1197 node: fix search logic in memory mutation cursor find
  silkworm/node/db/memory_mutation_cursor.cpp
  silkworm/node/db/memory_mutation_cursor_test.cpp
Labels: maintenance, memory-mutation

#1067 cmd: add state transition tool
  cmd/CMakeLists.txt
  cmd/state-transition/CMakeLists.txt
  cmd/state-transition/expected_state.cpp
  cmd/state-transition/expected_state.hpp
  cmd/state-transition/runner.cpp
  cmd/state-transition/state_transition.cpp
  cmd/state-transition/state_transition.hpp
  cmd/state-transition/state_transition_sample1.json
  cmd/state-transition/state_transition_sample2.json
  cmd/state-transition/state_transition_sample3.json
  cmd/state-transition/state_transition_sample4.json
  cmd/test/ethereum.cpp
  silkworm/core/common/test_util.hpp
Labels: enhancement
