Repository erigontech/silkworm, pull requests merged in 2024-06, with the labels that each got.

#2066 rpcdaemon: temporal KV server-side stubbed implementation
  silkworm/node/remote/kv/grpc/server/backend_kv_server.cpp
  silkworm/node/remote/kv/grpc/server/backend_kv_server_test.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.hpp
Labels: temporal kv

#2068 rpcdaemon: tx ID in client-side local/remote transaction
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/ethdb/file/local_transaction.hpp
  silkworm/rpc/ethdb/kv/remote_transaction.cpp
  silkworm/rpc/ethdb/kv/remote_transaction.hpp
  silkworm/rpc/ethdb/kv/remote_transaction_test.cpp
  silkworm/rpc/ethdb/transaction.hpp
  silkworm/rpc/test_util/dummy_transaction.hpp
  silkworm/rpc/test_util/mock_transaction.hpp
Labels: temporal kv

#2075 cmd: fix clang tidy after PR 2056
  cmd/dev/snapshots.cpp
Labels: maintenance

#2065 snapshots: move DAL code and tests
  cmd/dev/snapshots.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/db/access_layer.cpp
  silkworm/db/bodies/body_index.cpp
  silkworm/db/bodies/body_index.hpp
  silkworm/db/bodies/body_queries.hpp
  silkworm/db/bodies/body_snapshot.cpp
  silkworm/db/bodies/body_snapshot.hpp
  silkworm/db/bodies/body_txs_amount_query.cpp
  silkworm/db/bodies/body_txs_amount_query.hpp
  silkworm/db/bodies/body_txs_amount_query_test.cpp
  silkworm/db/headers/header_index.cpp
  silkworm/db/headers/header_index.hpp
  silkworm/db/headers/header_queries.hpp
  silkworm/db/headers/header_snapshot.cpp
  silkworm/db/headers/header_snapshot.hpp
  silkworm/db/snapshot_benchmark.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_decompressor_test.cpp
  silkworm/db/snapshot_index_builder_test.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshot_test.cpp
  silkworm/db/test_util/temp_snapshots.hpp
  silkworm/db/transactions/txn_index.cpp
  silkworm/db/transactions/txn_index.hpp
  silkworm/db/transactions/txn_queries.hpp
  silkworm/db/transactions/txn_snapshot.hpp
  silkworm/db/transactions/txn_snapshot_word_serializer.cpp
  silkworm/db/transactions/txn_snapshot_word_serializer.hpp
  silkworm/db/transactions/txn_to_block_index.cpp
  silkworm/db/transactions/txn_to_block_index.hpp
  silkworm/db/transactions/txs_and_bodies_query.cpp
  silkworm/db/transactions/txs_and_bodies_query.hpp
Labels: snapshots, maintenance

#2077 snapshots: fix build on Apple clang 14
  silkworm/db/snapshots/common/iterator/map_values_view.hpp
Labels: maintenance

#2082 rpcdaemon: fix ots_getContractCreator
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance

#2086 rpcdaemon: fix TSAN build after PR 2084
  .github/workflows/windows.yml
  silkworm/rpc/core/remote_state_test.cpp
Labels: maintenance

#2080 qa-tests: add Change Point analysis to perf tests
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#2087 rpcdaemon: walk/for_prefix as functions
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/ethdb/base_transaction.cpp
  silkworm/rpc/ethdb/base_transaction.hpp
  silkworm/rpc/ethdb/bitmap.cpp
  silkworm/rpc/ethdb/transaction.hpp
  silkworm/rpc/ethdb/walk.cpp
  silkworm/rpc/ethdb/walk.hpp
  silkworm/rpc/test_util/mock_transaction.hpp
Labels: maintenance

#2085 rpcdaemon: fix eth_getStorageAt location as hex string index
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance, json rpc api

#2088 rpcdaemon: support splitted BackEnd and KV servers
  cmd/dev/backend_kv_server.cpp
  silkworm/node/backend/ethereum_backend.hpp
  silkworm/node/node.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_kv_server.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_kv_server.hpp
  silkworm/node/remote/ethbackend/grpc/server/backend_server.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_server.hpp
  silkworm/node/remote/ethbackend/grpc/server/backend_server_test.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.hpp
  silkworm/node/remote/kv/grpc/server/kv_calls_test.cpp
  silkworm/node/remote/kv/grpc/server/kv_server.cpp
  silkworm/node/remote/kv/grpc/server/kv_server.hpp
  silkworm/node/remote/kv/grpc/server/kv_server_test.cpp
  silkworm/node/remote/kv/grpc/server/state_change_collection.cpp
  silkworm/node/remote/kv/grpc/server/state_change_collection.hpp
  silkworm/node/remote/kv/grpc/server/state_change_collection_test.cpp
  silkworm/rpc/ethdb/file/local_cursor.cpp
Labels: maintenance

#2089 node: move KV API client/server to db
  silkworm/db/remote/kv/api/client.hpp
  silkworm/db/remote/kv/api/direct_client.cpp
  silkworm/db/remote/kv/api/direct_client.hpp
  silkworm/db/remote/kv/api/direct_service.cpp
  silkworm/db/remote/kv/api/direct_service.hpp
  silkworm/db/remote/kv/api/endpoint/common.hpp
  silkworm/db/remote/kv/api/endpoint/temporal_point.hpp
  silkworm/db/remote/kv/api/endpoint/temporal_range.hpp
  silkworm/db/remote/kv/api/service.hpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_point.cpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_point.hpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_point_test.cpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_range.cpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_range.hpp
  silkworm/db/remote/kv/grpc/client/endpoint/temporal_range_test.cpp
  silkworm/db/remote/kv/grpc/client/remote_client.cpp
  silkworm/db/remote/kv/grpc/client/remote_client.hpp
  silkworm/db/remote/kv/grpc/client/remote_client_test.cpp
  silkworm/db/remote/kv/grpc/server/kv_calls.cpp
  silkworm/db/remote/kv/grpc/server/kv_calls.hpp
  silkworm/db/remote/kv/grpc/server/kv_calls_test.cpp
  silkworm/db/remote/kv/grpc/server/kv_server.cpp
  silkworm/db/remote/kv/grpc/server/kv_server.hpp
  silkworm/db/remote/kv/grpc/server/kv_server_test.cpp
  silkworm/db/remote/kv/grpc/server/state_change_collection.cpp
  silkworm/db/remote/kv/grpc/server/state_change_collection.hpp
  silkworm/db/remote/kv/grpc/server/state_change_collection_test.cpp
  silkworm/db/remote/kv/grpc/test_util/sample_protos.hpp
  silkworm/infra/test_util/fixture.hpp
  silkworm/node/backend/ethereum_backend.hpp
  silkworm/node/execution/grpc/client/endpoint/checkers_test.cpp
  silkworm/node/execution/grpc/client/endpoint/getters_test.cpp
  silkworm/node/execution/grpc/client/endpoint/insertion_test.cpp
  silkworm/node/execution/grpc/common/block_test.cpp
  silkworm/node/execution/grpc/server/endpoint/checkers_test.cpp
  silkworm/node/execution/grpc/server/endpoint/getters_test.cpp
  silkworm/node/execution/grpc/server/endpoint/insertion_test.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_kv_server.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_kv_server.hpp
Labels: maintenance

#2093 rpcdaemon: update ignore list and add subtest ignore list in I/O tests
  silkworm/rpc/commands/rpc_api_test.cpp
Labels: maintenance

#2094 rpcdaemon: restore effective gas price computation in EVMExecutor::call
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance

#2091 qa-tests: fix commit sha, add branch name and chain/network to uploaded results
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing, integration testing

#2099 rpcdaemon: fix clang tidy after PR 2098
  silkworm/rpc/ethdb/kv/remote_transaction.cpp
Labels: maintenance

#2100 rpcdaemon: extract receipts out from chain
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain.hpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/receipts.hpp
  silkworm/rpc/core/receipts_test.cpp
Labels: maintenance

#2104 rpcdaemon: move read_chain_config to chain storage
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain.hpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/json/types_test.cpp
  silkworm/rpc/storage/chain_storage.hpp
  silkworm/rpc/storage/local_chain_storage.cpp
  silkworm/rpc/storage/local_chain_storage.hpp
  silkworm/rpc/storage/remote_chain_storage.cpp
  silkworm/rpc/storage/remote_chain_storage.hpp
  silkworm/rpc/storage/remote_chain_storage_test.cpp
  silkworm/rpc/types/chain_config.cpp
  silkworm/rpc/types/chain_config.hpp
  silkworm/rpc/types/chain_config_test.cpp
Labels: maintenance

#2081 execution: fix OOM crash due to db::Buffer::accounts realloc (#2064)
  cmd/dev/check_changes.cpp
  cmd/dev/scan_txs.cpp
  silkworm/capi/silkworm.cpp
  silkworm/core/execution/execution.hpp
  silkworm/core/execution/execution_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
  silkworm/core/protocol/blockchain.cpp
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/state/in_memory_state.hpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/core/state/state.hpp
  silkworm/db/buffer.cpp
  silkworm/db/buffer.hpp
  silkworm/db/buffer_test.cpp
  silkworm/db/test_util/test_database_context.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages_test.cpp
  silkworm/rpc/core/local_state.hpp
  silkworm/rpc/core/override_state.hpp
  silkworm/rpc/core/remote_state.hpp
  silkworm/rpc/core/remote_state_test.cpp
Labels: maintenance

#2063 rpcdaemon: post EIP1559 balance check done on max_fee_per_gas and max_blob_per_gas
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/json/call.cpp
  silkworm/rpc/types/call.hpp
Labels: maintenance

#2102 qa-tests: record the db version used for test
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#2109 rpcademon: remove erigon_cumulativeChainTraffic
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain.hpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/json_rpc/methods.hpp
  silkworm/rpc/storage/chain_storage.hpp
Labels: json rpc api

#2095 execution: add ExecutionEngine tests
  silkworm/capi/silkworm_test.cpp
  silkworm/db/test_util/test_database_context.cpp
  silkworm/db/test_util/test_database_context.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/test_util/api_test_database.hpp
Labels: execution at tip

#2112 node: main chain db txn management
  silkworm/node/common/node_settings.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
Labels: enhancement

#2111 rpcdaemon: SuicideAction implementation in trace API
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: json rpc api

#2110 rpcdaemon: remove erigon_watchTheBurn
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain.hpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/storage/chain_storage.hpp
Labels: json rpc api

#2114 rpcdaemon: rename json_rpc::JsonRpcValidator
  docs/fuzzer.md
  silkworm/rpc/daemon.cpp
  silkworm/rpc/json_rpc/request_handler.cpp
  silkworm/rpc/json_rpc/request_handler.hpp
  silkworm/rpc/json_rpc/validator.cpp
  silkworm/rpc/json_rpc/validator.hpp
  silkworm/rpc/json_rpc/validator_benchmark.cpp
  silkworm/rpc/json_rpc/validator_test.cpp
  silkworm/rpc/test_util/api_test_database.hpp
Labels: maintenance

#2116 rpcdaemon: refactoring to use db::storage_prefix utility
  silkworm/db/util.cpp
  silkworm/db/util_test.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/core/rawdb/chain.hpp
  silkworm/rpc/core/rawdb/util.cpp
  silkworm/rpc/core/rawdb/util_test.cpp
  silkworm/rpc/core/state_reader.cpp
  silkworm/rpc/ethdb/kv/state_cache.cpp
  silkworm/rpc/ethdb/kv/state_cache.hpp
  silkworm/rpc/ethdb/kv/state_cache_test.cpp
  silkworm/rpc/ethdb/kv/util.cpp
  silkworm/rpc/ethdb/kv/util.hpp
  silkworm/rpc/ethdb/kv/util_test.cpp
Labels: maintenance

#2125 rpcdaemon: refactoring to separate SplitCursor from Cursor
  silkworm/db/util_test.cpp
  silkworm/rpc/core/account_walker.hpp
  silkworm/rpc/core/storage_walker.cpp
  silkworm/rpc/core/storage_walker.hpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/ethdb/cursor.hpp
  silkworm/rpc/ethdb/split_cursor.cpp
  silkworm/rpc/ethdb/split_cursor.hpp
  silkworm/rpc/ethdb/split_cursor_test.cpp
Labels: maintenance

#2126 qa-tests: fix missing result upload in performance tests
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#2128 fuzzer: fix build after PR 2127
  cmd/test/CMakeLists.txt
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_test.cpp
Labels: maintenance

#2129 rpcdaemon: refactoring state access
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/ethdb/file/local_transaction.cpp
  silkworm/rpc/ethdb/kv/remote_transaction.cpp
  silkworm/rpc/state/local_state.cpp
  silkworm/rpc/state/local_state.hpp
  silkworm/rpc/state/remote_state.cpp
  silkworm/rpc/state/remote_state.hpp
  silkworm/rpc/state/remote_state_test.cpp
  silkworm/rpc/state/state_reader.cpp
  silkworm/rpc/state/state_reader.hpp
  silkworm/rpc/state/state_reader_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: maintenance

#2115 rpcdaemon: fix eth_feeHistory
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
Labels: maintenance, json rpc api

#2130 rpcdaemon: remove optional in read chain config
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/json/types.hpp
  silkworm/rpc/storage/chain_storage.hpp
  silkworm/rpc/storage/local_chain_storage.cpp
  silkworm/rpc/storage/local_chain_storage.hpp
  silkworm/rpc/storage/remote_chain_storage.cpp
  silkworm/rpc/storage/remote_chain_storage.hpp
  silkworm/rpc/storage/remote_chain_storage_test.cpp
  silkworm/rpc/test_util/mock_chain_storage.hpp
Labels: maintenance

#2132 qa-tests: add latency percentile analysis
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#2134 fix unit tests to not write in cwd
  cmd/dev/db_toolbox.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
  silkworm/infra/common/directories.cpp
  silkworm/infra/common/directories.hpp
  silkworm/infra/common/directories_test.cpp
Labels: maintenance

#2135 rpcademon: fix is_replay_protected and parse raw transaction
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/common/util.cpp
  silkworm/rpc/common/util_test.cpp
Labels: maintenance

#2137 infra: remove test_util/dummy.cpp
  silkworm/infra/test_util/dummy.cpp
Labels: maintenance

#2138 third_party: silent blst build
  third_party/blst/CMakeLists.txt
Labels: maintenance

#2139 qa-tests: fix rpc perf test workflow
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#2141 db: use ByteView in KV StateCache
  silkworm/db/kv/api/base_transaction.cpp
  silkworm/db/kv/api/state_cache.cpp
  silkworm/db/kv/api/state_cache.hpp
Labels: maintenance

#2143 db: remove duplicated KV API utilities
  cmd/dev/grpc_toolbox.cpp
  silkworm/core/common/bytes_to_string.hpp
  silkworm/core/common/util.hpp
  silkworm/core/common/util_test.cpp
  silkworm/core/test_util/null_stream.hpp
  silkworm/db/chain/chain.cpp
  silkworm/db/kv/api/local_cursor.cpp
  silkworm/db/kv/api/local_cursor.hpp
  silkworm/db/kv/api/state_cache.cpp
  silkworm/db/kv/api/state_cache.hpp
  silkworm/db/kv/api/util.hpp
  silkworm/db/kv/api/util_test.cpp
  silkworm/db/kv/grpc/client/remote_cursor.cpp
  silkworm/db/kv/grpc/client/remote_cursor.hpp
  silkworm/db/kv/grpc/client/remote_cursor_test.cpp
  silkworm/db/state/state_reader.cpp
  silkworm/db/state/state_reader_test.cpp
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/common/util.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/account_walker.cpp
  silkworm/rpc/core/blocks.cpp
  silkworm/rpc/core/blocks_test.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/override_state.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/storage_walker.cpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/ethdb/bitmap.cpp
  silkworm/rpc/ethdb/walk.cpp
  silkworm/rpc/stagedsync/stages.hpp
  silkworm/rpc/txpool/miner.cpp
  silkworm/rpc/types/execution_payload.cpp
  silkworm/rpc/types/receipt.cpp
  silkworm/sync/internals/types.hpp
Labels: maintenance

#2145 db: fix clang tidy after PR 2142
  silkworm/db/snapshots/snapshot_writer.cpp
  silkworm/db/snapshots/snapshot_writer.hpp
Labels: maintenance

#2146 rpcdaemon: enum values for protocol error codes
  silkworm/rpc/commands/admin_api.cpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/net_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/rpc_api_table_test.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/commands/txpool_api.cpp
  silkworm/rpc/commands/web3_api.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/json_rpc/request_handler_test.cpp
Labels: maintenance, json rpc api

#2149 integration test: temporary disable debug_storageRangeAt test 6 and 7
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance

#2151 rpcdaemon: fix clang tidy after PR 2147
  silkworm/rpc/core/receipts.cpp
Labels: maintenance

#2152 capi: depend on silkworm_db rather than silkworm_node
  silkworm/capi/CMakeLists.txt
Labels: maintenance

#2153 rpcdaemon: fix debug/trace API family gas cost
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2155 rpcdaemon: fix debug_storageRangeAt
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/storage_walker.cpp
Labels: maintenance
