Repository erigontech/silkworm, pull requests merged in 2024-05, with the labels that each got.

#1994 fuzzer: extend timeout to 24 hours
  .github/workflows/rpc-fuzzer-tests.yml
Labels: fuzzy testing

#1993 ci: remove Fuzzer test runner from CircleCI
  .circleci/config.yml
Labels: maintenance, fuzzy testing

#1996 rpcdaemon: erigon_getLatestLogs fix retrieving latest block
  silkworm/rpc/core/logs_walker.cpp
Labels: maintenance

#1997 rpcdaemon: fix JSON for empty logs in erigon_getLogsByHash
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/json/log.cpp
  silkworm/rpc/json/log.hpp
Labels: maintenance

#1995 rpcdaemon: fix crash in trace_replay* API
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#1990 rpcdaemon: add blob check on evm executor
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance

#1991 rpcdaemon: fix retry logic in eth_estimateGas
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/types/call.hpp
  silkworm/rpc/types/call_test.cpp
Labels: maintenance

#2000 db: fix block number values in HeaderNumber table after snapshot sync
  cmd/dev/snapshots.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/node/node.cpp
Labels: maintenance

#1998 rpcdaemon: fix check for excess blob gas in EVM executor
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#1999 rpcdaemon: add missing fields in ots_getBlockTransactions
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/types/block.hpp
Labels: maintenance

#2001 db: missing length errors in access layer
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer_test.cpp
  silkworm/db/mdbx/mdbx.hpp
  silkworm/db/test_util/CMakeLists.txt
  silkworm/db/test_util/mock_cursor.hpp
  silkworm/db/test_util/mock_txn.hpp
Labels: maintenance

#2002 rpcdaemon: fix blob gas check in ExecutionPayload
  silkworm/rpc/json/execution_payload.cpp
  silkworm/rpc/json/execution_payload_test.cpp
Labels: maintenance

#2005 rpcdaemon: eth_createAccessList shouldn't modify input Call
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/types/call.hpp
  silkworm/rpc/types/call_test.cpp
Labels: maintenance

#2008 fuzzer: increase available memory
  .github/workflows/rpc-fuzzer-tests.yml
Labels: fuzzy testing

#2007 rpcdameon: fix getLatestLogs with logCount
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/logs_walker.hpp
Labels: maintenance

#2009 rpcademon: add optional blob fields in ots_getBlockDetails
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/json/block.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/types/block.hpp
Labels: maintenance

#2011 rpcdaemon: fix on withdrawals in ots_getBlockDetailsByHash
  silkworm/rpc/commands/ots_api.cpp
Labels: maintenance

#2014 docs: add Erigon++ section in README
  README.md
Labels: documentation

#2010 rpcdaemon: undefined instruction error message in TraceTracer
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2012 rpcdaemon: fix block issuance and upgrade rpc-tests
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/json/types.cpp
Labels: maintenance, integration testing

#2020 rpcdaemon: fix undefined instruction error in trace_call
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2019 rpcdaemon: fix eth_call without sender
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/types/call.hpp
Labels: maintenance

#2021 rpcdaemon: fix on create failure trace
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2023 node: fix Clang Tidy after PR 2004
  silkworm/node/execution/api/endpoint/assembly.hpp
  silkworm/node/execution/api/endpoint/checkers.hpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/server.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
Labels: maintenance

#2024 KV: temporal direct and gRPC client + server skeleton
  cmd/dev/backend_kv_server.cpp
  silkworm/infra/grpc/common/bytes.hpp
  silkworm/node/node.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_calls.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_calls.hpp
  silkworm/node/remote/kv/api/client.hpp
  silkworm/node/remote/kv/api/direct_client.cpp
  silkworm/node/remote/kv/api/direct_client.hpp
  silkworm/node/remote/kv/api/direct_service.cpp
  silkworm/node/remote/kv/api/direct_service.hpp
  silkworm/node/remote/kv/api/endpoint/common.hpp
  silkworm/node/remote/kv/api/endpoint/temporal_point.hpp
  silkworm/node/remote/kv/api/endpoint/temporal_range.hpp
  silkworm/node/remote/kv/api/service.hpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_point.cpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_point.hpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_point_test.cpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_range.cpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_range.hpp
  silkworm/node/remote/kv/grpc/client/endpoint/temporal_range_test.cpp
  silkworm/node/remote/kv/grpc/client/remote_client.cpp
  silkworm/node/remote/kv/grpc/client/remote_client.hpp
  silkworm/node/remote/kv/grpc/server/backend_kv_server.cpp
  silkworm/node/remote/kv/grpc/server/backend_kv_server.hpp
  silkworm/node/remote/kv/grpc/server/backend_kv_server_test.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.cpp
  silkworm/node/remote/kv/grpc/server/kv_calls.hpp
  silkworm/node/remote/kv/grpc/server/kv_calls_test.cpp
  silkworm/node/remote/kv/grpc/test_util/sample_protos.hpp
Labels: enhancement

#2026 node: unit tests for temporal KV gRPC client
  silkworm/infra/grpc/client/call.hpp
  silkworm/infra/grpc/common/version_test.cpp
  silkworm/infra/grpc/test_util/grpc_actions.hpp
  silkworm/infra/grpc/test_util/grpc_matcher.hpp
  silkworm/infra/grpc/test_util/grpc_responder.hpp
  silkworm/infra/grpc/test_util/interfaces/ethbackend_mock_fix24351.grpc.pb.h
  silkworm/infra/grpc/test_util/interfaces/kv_mock_fix24351.grpc.pb.h
  silkworm/infra/grpc/test_util/interfaces/mining_mock_fix24351.grpc.pb.h
  silkworm/infra/grpc/test_util/interfaces/txpool_mock_fix24351.grpc.pb.h
  silkworm/infra/grpc/test_util/test_runner.hpp
  silkworm/infra/test_util/task_runner.hpp
  silkworm/node/execution/grpc/client/remote_client.cpp
  silkworm/node/remote/kv/grpc/client/remote_client.cpp
  silkworm/node/remote/kv/grpc/client/remote_client.hpp
  silkworm/node/remote/kv/grpc/client/remote_client_test.cpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/remote_client.hpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/ethdb/kv/remote_cursor_test.cpp
  silkworm/rpc/ethdb/kv/remote_database_test.cpp
  silkworm/rpc/ethdb/kv/remote_transaction_test.cpp
  silkworm/rpc/ethdb/kv/state_changes_stream_test.cpp
  silkworm/rpc/test_util/context_test_base.hpp
  silkworm/rpc/test_util/kv_test_base.hpp
  silkworm/rpc/txpool/miner_test.cpp
  silkworm/rpc/txpool/transaction_pool_test.cpp
  silkworm/sentry/grpc/client/sentry_client.cpp
Labels: maintenance, unit testing

#2025 rpc_integration_workflow: enable tests on last blocks
  .github/workflows/rpc-integration-tests.yml
Labels: integration testing

#2027 node: move execution gRPC test_util into grpc folder
  silkworm/node/execution/grpc/client/endpoint/checkers_test.cpp
  silkworm/node/execution/grpc/client/endpoint/getters_test.cpp
  silkworm/node/execution/grpc/client/endpoint/insertion_test.cpp
  silkworm/node/execution/grpc/client/remote_client.cpp
  silkworm/node/execution/grpc/common/block_test.cpp
  silkworm/node/execution/grpc/server/endpoint/checkers_test.cpp
  silkworm/node/execution/grpc/server/endpoint/getters_test.cpp
  silkworm/node/execution/grpc/server/endpoint/insertion_test.cpp
  silkworm/node/execution/grpc/test_util/sample_protos.hpp
Labels: maintenance

#2029 sync: fix validity check for zero-difficulty headers
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/internals/header_chain.hpp
  silkworm/sync/internals/header_retrieval_test.cpp
Labels: maintenance

#2030 sync: handle send errors for outbound p2p messages
  silkworm/sync/messages/inbound_block_bodies.cpp
  silkworm/sync/messages/inbound_block_headers.cpp
  silkworm/sync/messages/inbound_get_block_bodies.cpp
  silkworm/sync/messages/inbound_get_block_headers.cpp
  silkworm/sync/messages/inbound_new_block_hashes.cpp
  silkworm/sync/messages/outbound_get_block_bodies.cpp
  silkworm/sync/messages/outbound_get_block_headers.cpp
  silkworm/sync/messages/outbound_new_block.cpp
  silkworm/sync/messages/outbound_new_block_hashes.cpp
Labels: maintenance

#2031 core, rpcdaemon: gas bailout in EVM
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#2032 sentry: add exception handling for main tasks
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/rlpx/server.cpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/status_manager.cpp
Labels: maintenance

#2022 rpcdaemon: fix ots_searchTransactionsBefore + ots_searchTransactionsAfter
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2033 rpcdaemon: get_opcode_name function refactoring
  silkworm/rpc/common/util.cpp
  silkworm/rpc/common/util.hpp
  silkworm/rpc/common/util_test.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2034 rpcdaemon: fix in ots_getTransactionError
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2035 fuzzer: extend job timeout
  .github/workflows/rpc-fuzzer-tests.yml
Labels: fuzzy testing

#2039 infra, node, rpcdaemon: refactor application build info
  cmd/common/common.cpp
  cmd/common/common.hpp
  cmd/rpcdaemon.cpp
  cmd/silkworm.cpp
  silkworm/infra/CMakeLists.txt
  silkworm/infra/common/application_info.cpp
  silkworm/infra/common/application_info.hpp
  silkworm/node/common/node_settings.hpp
  silkworm/node/node.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/daemon.hpp
  silkworm/rpc/settings.hpp
Labels: maintenance

#2040 rpcdaemon: add engine_getClientVersionV1 API
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/engine_api.hpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/commands/rpc_api.hpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/json/client_version.cpp
  silkworm/rpc/json/client_version.hpp
  silkworm/rpc/json_rpc/methods.hpp
Labels: enhancement, json rpc api

#2041 snapshots: support empty words in tx deserializers
  silkworm/db/snapshots/snapshot_test.cpp
  silkworm/db/snapshots/txn_snapshot_word_serializer.cpp
  silkworm/db/snapshots/txn_snapshot_word_serializer.hpp
Labels: maintenance

#2044 node, sync: remove old in-process execution API
  silkworm/node/node.cpp
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/local_client.cpp
  silkworm/node/stagedsync/local_client.hpp
  silkworm/node/stagedsync/local_client_test.cpp
  silkworm/node/stagedsync/remote_client.cpp
  silkworm/node/stagedsync/remote_client.hpp
  silkworm/node/stagedsync/remote_client_test.cpp
  silkworm/node/stagedsync/server.cpp
  silkworm/node/stagedsync/server.hpp
  silkworm/sync/sync_pos.hpp
  silkworm/sync/sync_pos_test.cpp
Labels: maintenance

#2045 snapshots: optimize BodyTxsAmountQuery using skip
  silkworm/db/snapshots/body_txs_amount_query.cpp
  silkworm/db/snapshots/body_txs_amount_query_test.cpp
  silkworm/db/snapshots/index_builder_test.cpp
  silkworm/db/snapshots/snapshot_reader.cpp
  silkworm/db/snapshots/snapshot_reader.hpp
Labels: performance

#2043 rpcdaemon: fix ots_traceTransaction
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2053 rpcdaemon: fix result as error in some ots API
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2055 rpcdaemon: fix clang tidy after PR 2053
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance

#2054 sentry: improve reconnect_channel logging
  silkworm/infra/grpc/client/call.hpp
  silkworm/infra/grpc/client/reconnect.cpp
  silkworm/infra/grpc/client/reconnect.hpp
  silkworm/sentry/grpc/client/sentry_client.cpp
Labels: enhancement

#2060 rpcdaemon: add stub for remote Execution engine
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/engine/remote_execution_engine.cpp
  silkworm/rpc/engine/remote_execution_engine.hpp
  silkworm/rpc/json_rpc/methods.hpp
Labels: maintenance
