Repository erigontech/silkworm, pull requests merged in 2024-03, with the labels that each got.

#1868 rpcdaemon: fix clang-tidy warning after PR 1858
  silkworm/rpc/http/connection.cpp
Labels: maintenance

#1871 core: add missing checks in call tracer
  silkworm/core/execution/call_tracer.cpp
Labels: maintenance

#1874 rpcdaemon: small improvements in HTTP connection
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#1870 snapshots: library target
  cmd/dev/check_senders.cpp
  cmd/dev/check_tx_lookup.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  silkworm/node/CMakeLists.txt
  silkworm/node/common/block_body_for_storage.hpp
  silkworm/node/common/block_body_for_storage_test.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/util.cpp
  silkworm/node/db/util.hpp
  silkworm/node/node.cpp
  silkworm/node/snapshot_sync.cpp
  silkworm/node/snapshot_sync.hpp
  silkworm/node/snapshot_sync_test.cpp
  silkworm/node/snapshots/CMakeLists.txt
  silkworm/node/snapshots/index.cpp
  silkworm/node/snapshots/snapshot.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
  silkworm/rpc/core/rawdb/chain.cpp
  silkworm/rpc/json/types_test.cpp
Labels: maintenance

#1878 node: write call traces in stage Execution
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_execution.hpp
Labels: enhancement

#1876 rpcdaemon: add txHash and transactionHash in debug/trace API like in Erigon
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
Labels: maintenance

#1879 capi: internal/external txn handling in block execution
  cmd/capi/execute.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
  silkworm/infra/common/bounded_buffer.hpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
  silkworm/node/db/test_util/temp_chain_data.hpp
Labels: maintenance, c api

#1882 capi: fix build after PR 1879
  cmake/common/targets.cmake
  cmake/compiler_settings.cmake
  silkworm/capi/CMakeLists.txt
  silkworm/capi/silkworm_test.cpp
Labels: maintenance

#1884 snapshots: support features flag in recsplit index
  silkworm/snapshots/rec_split/encoding/sequence.hpp
  silkworm/snapshots/rec_split/encoding/sequence_test.cpp
  silkworm/snapshots/rec_split/rec_split.hpp
  silkworm/snapshots/rec_split/rec_split_seq_test.cpp
Labels: enhancement, maintenance

#1887 snapshots: read existence filter in recsplit index
  cmd/dev/snapshots.cpp
  silkworm/snapshots/rec_split/rec_split.hpp
Labels: enhancement

#1888 rpcdaemon: fix in http response failed
  silkworm/rpc/http/connection.cpp
Labels: maintenance

#1889 stagedsync: do not share global node_settings with stages
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
  silkworm/node/stagedsync/stages/_test.cpp
  silkworm/node/stagedsync/stages/stage.cpp
  silkworm/node/stagedsync/stages/stage.hpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages/stage_blockhashes.hpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_bodies.hpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_execution.hpp
  silkworm/node/stagedsync/stages/stage_finish.cpp
  silkworm/node/stagedsync/stages/stage_finish.hpp
  silkworm/node/stagedsync/stages/stage_hashstate.hpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_headers.hpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_history_index.hpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.hpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_log_index.hpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
Labels: maintenance

#1891 stagedsync: fix Clang Tidy warnings after PR 1889
  silkworm/node/stagedsync/stages/stage_hashstate.hpp
  silkworm/node/stagedsync/stages/stage_interhashes.hpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
Labels: maintenance

#1892 stagedsync: add CallTraceIndex stage
  silkworm/node/db/tables.hpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/stages/stage.hpp
  silkworm/node/stagedsync/stages/stage_call_trace_index.cpp
  silkworm/node/stagedsync/stages/stage_call_trace_index.hpp
Labels: enhancement

#1886 rpcdaemon: print address on error in execution pre-checks
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#1900 rpcdaemon: fix position of logs folder
  silkworm/rpc/daemon.cpp
Labels: maintenance

#1902 cmake: use absolute path when applying exclude regex
  cmake/common/targets.cmake
  silkworm/node/CMakeLists.txt
  silkworm/node/db/CMakeLists.txt
Labels: maintenance

#1895 stagedsync: unit test for CallTraceIndex stage
  silkworm/node/stagedsync/stages_test.cpp
Labels: maintenance

#1903 node: fix Clang Tidy after PR 1890
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
Labels: maintenance

#1897 sentry: fix unhandled exception in peer handshake close
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1904 sentry: cleanup handshake_promise shutdown handling
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1893 rpcdaemon: fix account state in debug_accountAt
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#1908 evmone: disabled warnings about C++ attributes
  third_party/evmone/CMakeLists.txt
Labels: maintenance

#1910 capi: fix SAN builds
  silkworm/capi/CMakeLists.txt
Labels: maintenance

#1909 rpcdaemon: add HTTP gzip compression (no streaming)
  conanfile.py
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: enhancement

#1913 rpcdaemon: fix Clang Tidy after PR 1909
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#1912 rpcdaemon: add http_compression flag
  cmd/common/rpcdaemon_options.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
  silkworm/rpc/settings.hpp
Labels: enhancement

#1915 cmd: better command options in snapshots tool
  cmd/dev/snapshots.cpp
Labels: maintenance

#1916 snapshots: less false-positives feature in recsplit
  silkworm/db/snapshots/index.cpp
  silkworm/db/snapshots/index.hpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
  silkworm/db/snapshots/rec_split/rec_split_par.hpp
  silkworm/db/snapshots/rec_split/rec_split_par_test.cpp
  silkworm/db/snapshots/rec_split/rec_split_seq.hpp
  silkworm/db/snapshots/rec_split/rec_split_seq_test.cpp
  silkworm/db/snapshots/snapshot.cpp
  silkworm/db/snapshots/test_util/common.hpp
Labels: enhancement

#1918 snapshots: fix unit tests on Windows after PR 1916
  silkworm/db/snapshots/rec_split/rec_split.hpp
Labels: maintenance

#1907 db: replace HeadInfo with ChainHead
  cmd/dev/backend_kv_server.cpp
  cmd/silkworm.cpp
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/core/types/block_id.hpp
  silkworm/core/types/chain_head.hpp
  silkworm/db/chain_head.cpp
  silkworm/db/chain_head.hpp
  silkworm/node/stagedsync/client.hpp
  silkworm/node/stagedsync/forks/canonical_chain.hpp
  silkworm/sentry/eth/status_data_provider.cpp
  silkworm/sentry/eth/status_data_provider.hpp
  silkworm/sync/internals/chain_fork_view.hpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
  silkworm/sync/sync_pow.cpp
Labels: maintenance

#1919 infra, db: fix Clang Tidy and Win build after PR 1911
  silkworm/db/snapshots/index.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/memory_mapped_file.hpp
Labels: maintenance

#1914 rpcdaemon: negotiation and validation of HTTP compression scheme
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: enhancement

#1923 rpcdaemon: simplify HTTP gzip compression handling
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#1921 tests: pause/resume Erigon, save test results
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement

#1926 cmake: no_warn_duplicate_libraries
  cmake/compiler_warnings.cmake
Labels: maintenance

#1927 sync: remove old flag to force PoW consensus
  cmd/common/settings.hpp
  cmd/silkworm.cpp
  silkworm/sync/sync.cpp
  silkworm/sync/sync.hpp
Labels: maintenance

#1928 mdbx-go: no_warn_duplicate_libraries
  cmake/compiler_settings.cmake
  cmake/compiler_warnings.cmake
  third_party/erigon-mdbx-go/CMakeLists.txt
Labels: maintenance

#1930 perf_test_workflow: enable http compression on rpcdaemon startup
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#1933 rpcdaemon: change http compression default value
  silkworm/rpc/settings.hpp
Labels: maintenance

#1934 rpcdaemon: increase max HTTP request body limit
  silkworm/rpc/http/connection.cpp
Labels: maintenance

#1937 snapshots: fix Windows build after PR 1922
  silkworm/db/snapshots/snapshot_decompressor_test.cpp
Labels: maintenance

#1935 perf-workflow: long name options for run_perf_test
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance

#1938 qa-tests: always save the result
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance, integration testing

#1941 core: merge BaseRuleSet with IRuleSet
  silkworm/core/chain/config.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
  silkworm/core/protocol/base_rule_set.cpp
  silkworm/core/protocol/base_rule_set.hpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/clique_rule_set.cpp
  silkworm/core/protocol/clique_rule_set.hpp
  silkworm/core/protocol/ethash_rule_set.cpp
  silkworm/core/protocol/ethash_rule_set.hpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/merge_rule_set.hpp
  silkworm/core/protocol/rule_set.cpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
Labels: maintenance

#1931 rpc, sync: support Engine API V3
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/engine_api.hpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/ethbackend/backend.hpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/ethbackend/remote_backend.hpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/json/execution_payload.cpp
  silkworm/rpc/json/execution_payload_test.cpp
  silkworm/rpc/json/payload_attributes.cpp
  silkworm/rpc/json_rpc/methods.hpp
  silkworm/rpc/json_rpc/request_handler.cpp
  silkworm/rpc/protocol/errors.hpp
  silkworm/rpc/test/mock_back_end.hpp
  silkworm/rpc/types/execution_payload.hpp
  silkworm/sync/engine_api_backend.cpp
  silkworm/sync/engine_api_backend.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
  silkworm/sync/sync_pos_test.cpp
Labels: enhancement, cancun

#1942 tests: add Erigon RpcDaemon in perf workflow
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#1943 infra: setup signal handling with SA_ONSTACK flag
  silkworm/infra/concurrency/signal_handler.cpp
  silkworm/infra/concurrency/signal_handler.hpp
  silkworm/infra/concurrency/signal_handler_test.cpp
Labels: maintenance

#1936 rpcdaemon: compression on separate thread
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
Labels: maintenance

#1948 rpcdaemon: fix debug_storageRangeAt response for non-existent block hash
  silkworm/rpc/commands/debug_api.cpp
Labels: maintenance

#1946 perf_workflow: add eth_createAccessList pattern test
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing

#1950 perf-workflow: fix eth_createAccessList pattern name
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance
