Repository erigontech/silkworm, pull requests merged in 2024-10, with the labels that each got.

#2362 infra: remove context pool wait modes
  cmd/common/common.cpp
  silkworm/infra/concurrency/context_pool.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/context_pool_settings.hpp
  silkworm/infra/concurrency/context_pool_test.cpp
  silkworm/infra/concurrency/idle_strategy.cpp
  silkworm/infra/concurrency/idle_strategy.hpp
  silkworm/infra/concurrency/idle_strategy_test.cpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/infra/grpc/client/client_context_pool_test.cpp
  silkworm/infra/grpc/server/server.hpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/infra/grpc/server/server_context_pool.hpp
  silkworm/infra/grpc/server/server_context_pool_test.cpp
  silkworm/node/node.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/server_test.cpp
  silkworm/sync/settings.hpp
  silkworm/sync/sync.cpp
Labels: maintenance

#2391 infra: fix clang tidy after PR 2362
  silkworm/infra/grpc/client/client_context_pool_test.cpp
  silkworm/rpc/json/log_test.cpp
Labels: maintenance

#2393 code style: SILKWORM_ASSERT
  cmd/dev/backend_kv_server.cpp
  cmd/dev/scan_txs.cpp
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/rlp/decode.cpp
  silkworm/db/freezer.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshots/common/encoding/util.hpp
  silkworm/db/snapshots/index.hpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
  silkworm/db/snapshots/seg/compressor.cpp
  silkworm/db/snapshots/seg/compressor/output_file_transaction.cpp
  silkworm/db/snapshots/seg/compressor/patricia_tree.cpp
  silkworm/db/snapshots/snapshot_bundle.hpp
  silkworm/infra/common/binary_search_test.cpp
  silkworm/infra/concurrency/task_group.cpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_triggers.cpp
  silkworm/rpc/common/util.cpp
  silkworm/rpc/core/evm_access_list_tracer.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/sentry/common/crypto/xor.cpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/discovery/disc_v4/message_codec.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
  silkworm/sentry/eth/message_id.cpp
  silkworm/sentry/grpc/interfaces/message.cpp
  silkworm/sentry/grpc/interfaces/peer_event.cpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/rlpx/auth/ecies_cipher.cpp
  silkworm/sentry/rlpx/crypto/aes.cpp
  silkworm/sentry/rlpx/crypto/hmac.cpp
  silkworm/sentry/rlpx/framing/framing_cipher.cpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/session_sentry_client.cpp
  silkworm/sync/internals/chain_elements.hpp
  silkworm/sync/internals/header_only_state.cpp
Labels: maintenance

#2375 rpcdaemon: generate transaction receipts on-the-fly
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/parity_api.hpp
  silkworm/rpc/commands/rpc_api.hpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/receipts.hpp
  silkworm/rpc/core/receipts_test.cpp
Labels: enhancement, erigon3

#2395 rpcdaemon: fix clang tidy after PR 2375
  silkworm/rpc/core/receipts_test.cpp
Labels: maintenance

#2385 docs: code style RFC amendments
  docs/CONTRIBUTING.md
  docs/code_style.md
Labels: documentation

#2390 db, rpcdaemon: flag to support E3 data storage
  cmd/common/rpcdaemon_options.cpp
  silkworm/db/state/version.cpp
  silkworm/db/state/version.hpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/daemon.hpp
  silkworm/rpc/settings.hpp
Labels: erigon3

#2386 db: Bloom filter and existence index for kv snapshots
  cmd/dev/snapshots.cpp
  silkworm/db/snapshots/CMakeLists.txt
  silkworm/db/snapshots/index/bloom_filter.cpp
  silkworm/db/snapshots/index/bloom_filter.hpp
  silkworm/db/snapshots/index/bloom_filter_test.cpp
  silkworm/db/snapshots/index/existence_index.cpp
  silkworm/db/snapshots/index/existence_index.hpp
  silkworm/db/snapshots/index/existence_index_test.cpp
  silkworm/db/snapshots/test_util/sample_bloom_filter_data.hpp
Labels: snapshots, erigon3

#2399 cmd, db: fix clang tidy and windows after PR 2386
  cmd/dev/CMakeLists.txt
  cmd/dev/snapshots.cpp
  silkworm/db/snapshots/index/bloom_filter.hpp
Labels: maintenance

#2396 seg: PatternAggregator kMaxPatternsSoftLimit
  silkworm/db/snapshots/seg/compressor/pattern_aggregator.cpp
Labels: enhancement, snapshots

#2400 integration tests: enable test on e3 and push bash command on shell script
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  .github/workflows/start_integration_rpcdaemon.sh
  .github/workflows/stop_integration_rpcdaemon.sh
Labels: integration testing, erigon3

#2372 core: replace Mumbai with Amoy testnet
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_test.cpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/chain/genesis_amoy.cpp
  silkworm/core/chain/genesis_amoy.hpp
  silkworm/core/chain/genesis_amoy.json
  silkworm/core/chain/genesis_bor_mainnet.cpp
  silkworm/core/chain/genesis_holesky.cpp
  silkworm/core/chain/genesis_mumbai.cpp
  silkworm/core/chain/genesis_mumbai.json
  silkworm/core/chain/genesis_test.cpp
  silkworm/db/genesis_test.cpp
  silkworm/db/snapshots/config.cpp
  silkworm/db/snapshots/config/amoy.hpp
  silkworm/db/snapshots/config/bor_mainnet.hpp
  silkworm/db/snapshots/config/holesky.hpp
  silkworm/db/snapshots/config/mainnet.hpp
  silkworm/db/snapshots/config/mumbai.hpp
  silkworm/db/snapshots/config/sepolia.hpp
  silkworm/db/snapshots/config_test.cpp
  silkworm/db/snapshots/seg/compressor/pattern_aggregator.hpp
Labels: polygon

#2373 capi: fork validator fixes
  silkworm/capi/silkworm_test.cpp
  silkworm/core/test_util/sample_blocks.hpp
  silkworm/db/access_layer.cpp
  silkworm/node/stagedsync/stages/stage_blockhashes.hpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_call_trace_index.cpp
  silkworm/node/stagedsync/stages/stage_call_trace_index.hpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.hpp
  silkworm/node/stagedsync/stages/stage_history_index.hpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_log_index.hpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.hpp
Labels: maintenance

#2398 rpcdaemon: impl providers for BlockNumberFromBlockHash & BlockHashFromBlockNumber
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client.hpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/receipts_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/ethdb/kv/backend_providers.hpp
  silkworm/rpc/ethdb/kv/remote_database.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
  silkworm/rpc/test_util/mock_back_end.hpp
Labels: erigon3

#2401 performance workflow: fix changed rpcdaemon option
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#2402 rpcdaemon: coinbase in access list for call simulation
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
Labels: maintenance

#2403 rpcdaemon: providers into Providers type
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client.hpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/receipts_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/ethdb/kv/backend_providers.hpp
  silkworm/rpc/ethdb/kv/remote_database.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: erigon3

#2404 rpcdaemon: fix clang tidy after PR 2403
  silkworm/rpc/daemon.cpp
Labels: maintenance

#2405 tests: disable merge corpus option for fuzzer
  .github/workflows/rpc-fuzzer-tests.yml
Labels: fuzzy testing

#2406 clang-tidy: enforce function case
  .clang-tidy
  cmd/dev/snapshots.cpp
  cmd/test/backend_kv_test.cpp
  silkworm/core/common/lru_cache.hpp
  silkworm/core/types/chain_head.hpp
  silkworm/db/kv/grpc/client/endpoint/state_change.cpp
  silkworm/db/kv/grpc/server/state_change_collection.cpp
  silkworm/db/kv/grpc/server/state_change_collection_test.cpp
  silkworm/db/snapshots/rec_split/murmur_hash3.cpp
  silkworm/db/snapshots/rec_split/murmur_hash3.hpp
  silkworm/db/snapshots/rec_split/murmur_hash3_test.cpp
  silkworm/execution/grpc/client/endpoint/assembly.cpp
  silkworm/execution/grpc/client/endpoint/checkers.cpp
  silkworm/execution/grpc/client/endpoint/checkers_test.cpp
  silkworm/execution/grpc/client/endpoint/getters.cpp
  silkworm/execution/grpc/client/endpoint/getters_test.cpp
  silkworm/execution/grpc/client/endpoint/range.cpp
  silkworm/execution/grpc/client/endpoint/validation.cpp
  silkworm/execution/grpc/common/block.cpp
  silkworm/execution/grpc/server/endpoint/checkers.cpp
  silkworm/execution/grpc/server/endpoint/checkers_test.cpp
  silkworm/execution/grpc/server/endpoint/getters.cpp
  silkworm/execution/grpc/server/endpoint/getters_test.cpp
  silkworm/execution/grpc/server/endpoint/insertion_test.cpp
  silkworm/execution/grpc/server/endpoint/range.cpp
  silkworm/execution/grpc/server/endpoint/validation.cpp
  silkworm/execution/grpc/server/server_calls.cpp
  silkworm/execution/grpc/test_util/sample_protos.hpp
  silkworm/infra/common/bounded_buffer_test.cpp
  silkworm/infra/grpc/common/conversion.cpp
  silkworm/infra/grpc/common/conversion.hpp
  silkworm/infra/grpc/common/conversion_test.cpp
  silkworm/node/remote/ethbackend/grpc/server/backend_calls.cpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/txpool/transaction_pool.cpp
  silkworm/sentry/grpc/interfaces/peer_id.cpp
  silkworm/sentry/grpc/interfaces/status_data.cpp
  silkworm/sync/internals/chain_elements.hpp
  silkworm/sync/internals/chain_elements_test.cpp
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/messages/inbound_block_bodies.cpp
  silkworm/sync/messages/inbound_block_bodies.hpp
  silkworm/sync/messages/inbound_block_headers.cpp
  silkworm/sync/messages/inbound_block_headers.hpp
  silkworm/sync/messages/inbound_get_block_bodies.cpp
  silkworm/sync/messages/inbound_get_block_bodies.hpp
  silkworm/sync/messages/inbound_get_block_headers.cpp
  silkworm/sync/messages/inbound_get_block_headers.hpp
  silkworm/sync/messages/inbound_message.cpp
  silkworm/sync/messages/inbound_message.hpp
  silkworm/sync/messages/inbound_new_block.cpp
  silkworm/sync/messages/inbound_new_block.hpp
  silkworm/sync/messages/inbound_new_block_hashes.cpp
  silkworm/sync/messages/inbound_new_block_hashes.hpp
  silkworm/sync/sync_pow.cpp
Labels: maintenance

#2407 code style: scoped_lock
  docs/code_style.md
  silkworm/db/etl/collector.hpp
  silkworm/db/etl/in_memory_collector.hpp
  silkworm/db/kv/api/state_cache.cpp
  silkworm/db/kv/grpc/server/state_change_collection.cpp
  silkworm/db/mdbx/bitmap.cpp
  silkworm/db/mdbx/bitmap.hpp
  silkworm/infra/common/log.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_loader.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/trie_loader.hpp
  silkworm/rpc/core/filter_storage.cpp
Labels: maintenance

#2412 execution: fix silkworm_capi_test on macOS (#2389)
  cmd/test/CMakeLists.txt
  silkworm/capi/silkworm_test.cpp
  silkworm/core/CMakeLists.txt
Labels: maintenance

#2413 infra: log macros with a module name
  silkworm/infra/common/log.hpp
  silkworm/infra/common/log_test.cpp
Labels: maintenance

#2420 tests: extend fuzzer memory limit
  .github/workflows/rpc-fuzzer-tests.yml
Labels: fuzzy testing

#2411 code style: explicit type instead of auto for constants
  silkworm/core/common/util_test.cpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/execution_test.cpp
  silkworm/core/trie/hash_builder_test.cpp
  silkworm/core/types/hash_test.cpp
  silkworm/db/access_layer_test.cpp
  silkworm/db/bitmap_test.cpp
  silkworm/db/buffer_test.cpp
  silkworm/db/chain/chain_test.cpp
  silkworm/db/datastore/snapshots/bittorrent/web_seed_client_test.cpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_seq_test.cpp
  silkworm/db/kv/api/state_cache_test.cpp
  silkworm/db/kv/grpc/server/kv_server_test.cpp
  silkworm/db/kv/grpc/server/state_change_collection_test.cpp
  silkworm/db/log_cbor_test.cpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/util_test.cpp
  silkworm/execution/grpc/client/endpoint/checkers_test.cpp
  silkworm/execution/grpc/server/endpoint/checkers_test.cpp
  silkworm/infra/grpc/common/conversion_test.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/node/stagedsync/stages_test.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/parity_api_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/receipts_test.cpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/ethdb/cbor_test.cpp
  silkworm/rpc/http/connection_test.cpp
  silkworm/rpc/json/execution_payload_test.cpp
  silkworm/rpc/json/log_test.cpp
  silkworm/rpc/json/receipt_test.cpp
  silkworm/rpc/json/types_test.cpp
  silkworm/rpc/json_rpc/request_handler_test.cpp
  silkworm/rpc/txpool/transaction_pool_test.cpp
  silkworm/rpc/types/dump_account_test.cpp
Labels: maintenance

#2419 snapshots: SnapshotPath.step_range
  cmd/dev/snapshots.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/core/common/base.hpp
  silkworm/db/blocks/bodies/body_index.hpp
  silkworm/db/blocks/bodies/body_txs_amount_query_test.cpp
  silkworm/db/blocks/headers/header_index.hpp
  silkworm/db/blocks/headers/header_snapshot.cpp
  silkworm/db/blocks/headers/header_snapshot.hpp
  silkworm/db/datastore/snapshot_merger.cpp
  silkworm/db/datastore/snapshots/config.cpp
  silkworm/db/datastore/snapshots/config.hpp
  silkworm/db/datastore/snapshots/config_test.cpp
  silkworm/db/datastore/snapshots/index_builder.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.hpp
  silkworm/db/datastore/snapshots/snapshot_path.cpp
  silkworm/db/datastore/snapshots/snapshot_path.hpp
  silkworm/db/datastore/snapshots/snapshot_path_test.cpp
  silkworm/db/datastore/snapshots/snapshot_reader.cpp
  silkworm/db/datastore/snapshots/snapshot_reader.hpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.hpp
  silkworm/db/datastore/snapshots/snapshot_type.hpp
  silkworm/db/datastore/snapshots/snapshot_word_serializer.hpp
  silkworm/db/datastore/snapshots/snapshot_writer.hpp
  silkworm/db/datastore/snapshots/step.hpp
  silkworm/db/kv/api/endpoint/common.hpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/snapshot_benchmark.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_decompressor_test.cpp
  silkworm/db/snapshot_index_builder_test.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshot_test.cpp
  silkworm/db/test_util/temp_snapshots.hpp
  silkworm/db/transactions/txn_index.cpp
  silkworm/db/transactions/txn_index.hpp
  silkworm/db/transactions/txn_to_block_index.cpp
  silkworm/db/transactions/txn_to_block_index.hpp
  silkworm/db/transactions/txs_and_bodies_query.cpp
  silkworm/db/transactions/txs_and_bodies_query.hpp
  silkworm/infra/test_util/temporary_file.hpp
Labels: snapshots

#2417 rpcdaemon: support only E3 + use Data API in unit tests
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  .github/workflows/start_integration_rpcdaemon.sh
  cmd/common/rpcdaemon_options.cpp
  silkworm/db/kv/api/endpoint/temporal_point.hpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/state/state_reader.cpp
  silkworm/db/state/state_reader.hpp
  silkworm/db/state/state_reader_test.cpp
  silkworm/db/state/version.cpp
  silkworm/db/state/version.hpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/settings.hpp
Labels: erigon3

#2423 snapshots: improve verbose dump in count subcommands
  cmd/dev/snapshots.cpp
Labels: snapshots

#2425 rpcdaemon: fix clang tidy after PR 2417
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2428 qa-tests: fix erigon management in integration tests
  .github/workflows/rpc-integration-tests.yml
Labels: integration testing

#2429 db: set operations on paginated Data API iterators
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
Labels: erigon3

#2427 snapshots: KV segments
  silkworm/db/datastore/snapshots/kv_segment/kv_segment_reader.cpp
  silkworm/db/datastore/snapshots/kv_segment/kv_segment_reader.hpp
  silkworm/db/datastore/snapshots/kv_segment/kv_segment_test.cpp
  silkworm/db/datastore/snapshots/kv_segment/kv_segment_writer.cpp
  silkworm/db/datastore/snapshots/kv_segment/kv_segment_writer.hpp
  silkworm/db/datastore/snapshots/seg/compression_kind.hpp
  silkworm/db/datastore/snapshots/seg/compressor.cpp
  silkworm/db/datastore/snapshots/seg/compressor.hpp
  silkworm/db/datastore/snapshots/seg/decompressor.cpp
  silkworm/db/datastore/snapshots/seg/decompressor.hpp
  silkworm/db/datastore/snapshots/segment/segment_test.cpp
  silkworm/db/datastore/snapshots/test_util/string_codec.hpp
Labels: snapshots, erigon3

#2431 rpcdaemon: remove totalDifficulty from RPC responses
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/json/block.cpp
  silkworm/rpc/json/block_test.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/json/types_test.cpp
  silkworm/rpc/types/block.cpp
  silkworm/rpc/types/block.hpp
  silkworm/rpc/types/block_test.cpp
Labels: json rpc api, erigon3

#2436 cmake: various conan-related fixes
  .circleci/config.yml
  .github/workflows/macOS.yml
  CMakeLists.txt
  cmd/CMakeLists.txt
  cmd/capi/CMakeLists.txt
  cmd/dev/CMakeLists.txt
  conanfile.py
  silkworm/db/CMakeLists.txt
  silkworm/db/datastore/CMakeLists.txt
  silkworm/db/datastore/snapshots/CMakeLists.txt
  silkworm/db/datastore/snapshots/bittorrent/CMakeLists.txt
  silkworm/db/datastore/snapshots/seg/CMakeLists.txt
  silkworm/infra/CMakeLists.txt
  silkworm/infra/test_util/CMakeLists.txt
  silkworm/node/CMakeLists.txt
  silkworm/node/stagedsync/stages/CMakeLists.txt
  silkworm/node/test_util/CMakeLists.txt
  silkworm/rpc/CMakeLists.txt
  silkworm/rpc/test_util/CMakeLists.txt
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/common/CMakeLists.txt
  silkworm/sentry/discovery/common/CMakeLists.txt
  silkworm/sentry/discovery/disc_v4/CMakeLists.txt
  silkworm/sentry/discovery/node_db/CMakeLists.txt
  tests/docker/Dockerfile
  third_party/cmake-conan/conan.cmake
Labels: maintenance

#2442 ci: fix macOS job pip3 cmd
  .circleci/config.yml
  .github/workflows/macOS.yml
  .github/workflows/windows.yml
Labels: maintenance

#2437 snapshots: timestamp-based repository
  cmd/capi/execute.cpp
  cmd/dev/check_changes.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  silkworm/capi/silkworm.cpp
  silkworm/db/datastore/snapshot_merger.cpp
  silkworm/db/datastore/snapshot_merger.hpp
  silkworm/db/datastore/snapshots/common/step.hpp
  silkworm/db/datastore/snapshots/common/timestamp.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle_factory.hpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.hpp
  silkworm/db/freezer.cpp
  silkworm/db/snapshot_benchmark.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_bundle_factory_impl.hpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/test_util/make_repository.cpp
  silkworm/db/test_util/make_repository.hpp
  silkworm/rpc/daemon.cpp
Labels: snapshots, erigon3

#2441 rpcdaemon: call ethbackend.canonical_body_for_storage if key empty in MaxTxNum
  silkworm/db/chain/chain.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/providers.hpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/grpc/client/remote_client.hpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/kv/txn_num_test.cpp
  silkworm/db/state/local_state.cpp
  silkworm/db/state/remote_state.cpp
  silkworm/db/state/remote_state.hpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/state/state_reader.cpp
  silkworm/db/state/state_reader.hpp
  silkworm/db/state/state_reader_test.cpp
  silkworm/rpc/commands/admin_api.hpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api.hpp
  silkworm/rpc/commands/net_api.hpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/parity_api.hpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/commands/trace_api.hpp
  silkworm/rpc/commands/web3_api.hpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker.hpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/cached_chain_test.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/call_many.hpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/evm_access_list_tracer.hpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
  silkworm/rpc/core/filter_storage.hpp
  silkworm/rpc/core/gas_price_oracle.hpp
  silkworm/rpc/core/override_state.cpp
  silkworm/rpc/core/receipts.hpp
  silkworm/rpc/core/receipts_test.cpp
  silkworm/rpc/core/storage_walker.hpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/ethdb/kv/backend_providers.hpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: erigon3

#2426 rpcdaemon: use ETHBACKEND.canonical_block_hash_from_number
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/db/chain/chain.cpp
  silkworm/db/chain/chain.hpp
  silkworm/db/chain/chain_test.cpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/txn_num.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/test_util/dummy_database.hpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: erigon3

#2450 db, rpcdaemon: fix canonical_hash_provider for state reader
  silkworm/core/execution/processor.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/state/remote_state.hpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/state/state_reader.cpp
  silkworm/db/state/state_reader.hpp
  silkworm/db/state/state_reader_test.cpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: maintenance, erigon3

#2430 rpcdaemon: use ETHBACKEND: block_number_from_hash instead of kv table
  .github/workflows/run_integration_tests.sh
  silkworm/db/chain/remote_chain_storage.cpp
Labels: erigon3

#2449 rpcdaemon: update parity_listStorageKeys API
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/commands/parity_api.cpp
Labels: json rpc api, erigon3

#2452 rpcdaemon: fix clang tidy after PR 2430
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2451 ci: schedule RPC fuzzer tests on long-running host
  .github/workflows/rpc-fuzzer-tests.yml
Labels: maintenance

#2445 clang-tidy: fix some warnings reported by clang 19
  .clang-tidy
  cmd/dev/grpc_toolbox.cpp
  silkworm/core/chain/config.cpp
  silkworm/core/execution/precompile.cpp
  silkworm/core/rlp/encode_test.cpp
  silkworm/core/trie/prefix_set.cpp
  silkworm/core/trie/vector_root.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_par.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_seq.hpp
  silkworm/db/mdbx_test.cpp
  silkworm/infra/common/binary_search_test.cpp
  silkworm/infra/common/log.hpp
  silkworm/infra/common/log_test.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/grpc/client/client_context_pool_test.cpp
  silkworm/infra/grpc/server/server_context_pool_test.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/gas_price_oracle_test.cpp
  silkworm/sentry/discovery/disc_v4/common/packet_type.hpp
  silkworm/sentry/discovery/disc_v4/server.cpp
  silkworm/sentry/eth/message_id.hpp
  silkworm/sync/internals/header_chain.cpp
Labels: maintenance

#2446 tests: fuzzer oom issue fix
  .github/actions/fuzzer-common-steps/action.yml
  .github/workflows/rpc-fuzzer-tests.yml
  CMakeLists.txt
  cmake/compiler_settings.cmake
  cmake/profiles/experimental/linux_x64_clang_16_release
  cmake/setup/compiler_install.sh
  cmd/test/CMakeLists.txt
Labels: enhancement, fuzzy testing

#2453 integration_tests: modify exception list
  .github/workflows/run_integration_tests.sh
Labels: integration testing, erigon3

#2438 qa-tests: add execution test workflow
  .github/workflows/execution-test.yml
Labels: enhancement, integration testing

#2462 execution: fix stages lookup in sanitizer builds
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
Labels: maintenance

#2454 rpcdaemon: fix mismatch in erigon_getHeaderBy[Hash|Number]
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/db/chain/providers.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/ethbackend/backend.hpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/ethbackend/remote_backend.hpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/ethdb/kv/backend_providers.hpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/json/types_test.cpp
  silkworm/rpc/test_util/mock_back_end.hpp
Labels: maintenance, erigon3

#2463 db: txn by idx in block for RemoteChainStorage
  silkworm/db/chain/chain_storage.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/local_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/test_util/mock_chain_storage.hpp
Labels: enhancement, erigon3

#2456 rpcdaemon: debug_traceTransaction error field
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: json rpc api, erigon3

#2461 make build helper target
  Makefile
  cmake/parallel_jobs_count.sh
Labels: enhancement

#2466 db: find block number from txn number over Data API
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/kv/txn_num_test.cpp
  silkworm/infra/common/async_binary_search.cpp
  silkworm/infra/common/async_binary_search.hpp
  silkworm/infra/common/async_binary_search_test.cpp
  silkworm/rpc/commands/erigon_api.cpp
Labels: enhancement, erigon3

#2455 rpcdaemon: eth_feeHistory for e3
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/core/types/block.cpp
  silkworm/core/types/block.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
  silkworm/rpc/core/fee_history_oracle_test.cpp
Labels: json rpc api, erigon3

#2470 rpcdaemon: Canonical body for storage return optional
  .github/workflows/run_integration_tests.sh
  silkworm/db/chain/providers.hpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/ethbackend/backend.hpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/ethbackend/remote_backend.hpp
  silkworm/rpc/ethdb/kv/backend_providers.hpp
  silkworm/rpc/test_util/mock_back_end.hpp
Labels: maintenance, erigon3
