Repository erigontech/silkworm, pull requests merged in 2024-12, with the labels that each got.

#2547 cmd: staged_pipeline dev tool
  cmd/dev/CMakeLists.txt
  cmd/dev/db_toolbox.cpp
  cmd/dev/staged_pipeline.cpp
  silkworm/core/execution/processor.cpp
  silkworm/db/datastore/snapshots/snapshot_settings.hpp
  silkworm/db/snapshot_sync.cpp
  silkworm/node/execution/block/block_executor.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
Labels: enhancement, integration testing

#2549 db: handle stream composition in temporal KV
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/storage_walker.cpp
Labels: maintenance, erigon3

#2542 core: unify transaction validation for execution and simulate paths
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/protocol/validation_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance

#2553 core: move get_block_hash() from EvmHost to EVM
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
Labels: evmone apiv2

#2554 core: use evmc::VM to own evmone's VM
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
Labels: evmone apiv2

#2556 test: fix Prague/Cancun test config
  silkworm/core/common/test_util.hpp
Labels: maintenance, pectra

#2558 qa-tests: fix snapshots test workflow
  .github/workflows/snapshot-test.yml
Labels: maintenance, integration testing

#2560 evm: refactor computation of execution gas limit
  silkworm/core/execution/processor.cpp
Labels: maintenance, evmone apiv2

#2562 style: clang-tidy fixes
  silkworm/core/protocol/validation.hpp
  silkworm/db/blocks/transactions/txs_and_bodies_query.cpp
  silkworm/db/blocks/transactions/txs_and_bodies_query.hpp
  silkworm/db/datastore/snapshot_merger.cpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/execution/state_factory.cpp
  silkworm/rpc/commands/debug_api.hpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/block_reader_test.cpp
Labels: maintenance

#2564 ci: fix clang ASAN after PR 2562
  silkworm/rpc/core/block_reader_test.cpp
Labels: maintenance

#2563 db: add range stream in temporal KV
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
Labels: erigon3, temporal kv

#2565 rpcdaemon: use transaction-level state in trace API
  .github/workflows/rpc-integration-tests.yml
  silkworm/db/kv/state_reader.cpp
  silkworm/db/kv/state_reader.hpp
  silkworm/execution/local_state.cpp
  silkworm/execution/local_state.hpp
  silkworm/execution/remote_state.hpp
  silkworm/execution/remote_state_test.cpp
  silkworm/execution/state_factory.cpp
  silkworm/execution/state_factory.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: enhancement, json rpc api, erigon3

#2567 rpcdaemon: use transaction-level state in ots API
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_trace.cpp
Labels: json rpc api, erigon3

#2568 rpcdaemon: remove unused includes
  silkworm/node/backend/ethereum_backend.hpp
  silkworm/node/backend/ethereum_backend_test.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/rpc_api.hpp
  silkworm/rpc/common/util_test.cpp
  silkworm/rpc/core/blocks_test.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/logs_walker.hpp
  silkworm/rpc/core/storage_walker.cpp
  silkworm/rpc/daemon.hpp
  silkworm/rpc/ethdb/file/local_database.hpp
  silkworm/rpc/ethdb/kv/remote_database.cpp
  silkworm/rpc/ethdb/kv/remote_database.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/json/authorization.cpp
  silkworm/rpc/json/call.cpp
  silkworm/rpc/json/transition_configuration.cpp
  silkworm/rpc/json_rpc/validator.hpp
  silkworm/rpc/test_util/api_test_database.hpp
  silkworm/rpc/test_util/mock_block_cache.hpp
  silkworm/rpc/test_util/service_context_test_base.hpp
  silkworm/rpc/transport/request_handler.hpp
  silkworm/rpc/txpool/miner_test.cpp
  silkworm/rpc/types/chain_traffic.hpp
  silkworm/rpc/types/dump_account.hpp
  silkworm/rpc/types/dump_account_test.cpp
  silkworm/rpc/types/error.hpp
  silkworm/rpc/types/execution_payload_test.cpp
  silkworm/rpc/types/transaction.hpp
Labels: maintenance

#2566 core: don't recreate evmone instance
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
Labels: enhancement, performance

#2571 core: fix WASM build after PR 2566
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
Labels: maintenance

#2573 snapshots: rename Decompressor::Iterator::skip_auto to skip
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.cpp
  silkworm/db/datastore/snapshots/segment/seg/decompressor.cpp
  silkworm/db/datastore/snapshots/segment/seg/decompressor.hpp
  silkworm/db/datastore/snapshots/segment/segment_reader.cpp
  silkworm/db/snapshot_decompressor_test.cpp
Labels: snapshots, maintenance

#2545 rpcdaemon: eth_getLogs for e3
  .github/workflows/rpc-integration-tests.yml
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/tables.hpp
  silkworm/db/util.cpp
  silkworm/db/util.hpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/logs_walker.hpp
Labels: json rpc api, erigon3

#2569 rpcdaemon: use transaction-level state in debug API
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug_test.cpp
Labels: json rpc api, erigon3

#2572 rpcdaemon: rework on execute trace_call
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: json rpc api, erigon3

#2579 test: increase stack size for cmd/test/ethereum
  cmd/test/ethereum.cpp
Labels: evmone apiv2

#2577 evm: clean up empty accounts after system contracts
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/validation.cpp
Labels: evmone apiv2

#2578 test: report unexpected accounts in cmd/test/ethereum
  cmd/test/ethereum.cpp
Labels: integration testing

#2581 evm: create txn receipt using results from evmone APIv2
  silkworm/core/execution/processor.cpp
Labels: evmone apiv2

#2574 cmd: move dev/snapshots and common to cli sublibraries
  cmake/common/targets.cmake
  cmd/CMakeLists.txt
  cmd/capi/CMakeLists.txt
  cmd/capi/execute.cpp
  cmd/dev/CMakeLists.txt
  cmd/dev/backend_kv_server.cpp
  cmd/dev/check_log_indices.cpp
  cmd/dev/check_senders.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/staged_pipeline.cpp
  cmd/rpcdaemon.cpp
  cmd/sentry.cpp
  cmd/silkworm.cpp
  cmd/test/CMakeLists.txt
  cmd/test/backend_kv_test.cpp
  silkworm/db/CMakeLists.txt
  silkworm/db/cli/CMakeLists.txt
  silkworm/db/cli/db_max_readers_option.cpp
  silkworm/db/cli/db_max_readers_option.hpp
  silkworm/db/cli/snapshot_options.cpp
  silkworm/db/cli/snapshot_options.hpp
  silkworm/db/cli/snapshots.cpp
  silkworm/infra/CMakeLists.txt
  silkworm/infra/cli/CMakeLists.txt
  silkworm/infra/cli/common.cpp
  silkworm/infra/cli/common.hpp
  silkworm/infra/cli/human_size_option.cpp
  silkworm/infra/cli/human_size_option.hpp
  silkworm/infra/cli/ip_endpoint_option.cpp
  silkworm/infra/cli/ip_endpoint_option.hpp
  silkworm/infra/cli/shutdown_signal.cpp
  silkworm/infra/cli/shutdown_signal.hpp
  silkworm/node/CMakeLists.txt
  silkworm/node/cli/CMakeLists.txt
  silkworm/node/cli/node_options.cpp
  silkworm/node/cli/node_options.hpp
  silkworm/rpc/CMakeLists.txt
  silkworm/rpc/cli/CMakeLists.txt
  silkworm/rpc/cli/rpcdaemon_options.cpp
  silkworm/rpc/cli/rpcdaemon_options.hpp
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/cli/CMakeLists.txt
  silkworm/sentry/cli/sentry_options.cpp
  silkworm/sentry/cli/sentry_options.hpp
Labels: snapshots, maintenance

#2580 node: restore account code hash in HashState unwind
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.hpp
Labels: maintenance

#2576 capi: fix capi_test with ASAN (#1881)
  cmake/compiler_settings.cmake
  cmd/capi/CMakeLists.txt
  silkworm/capi/CMakeLists.txt
  silkworm/capi/fork_validator.cpp
  silkworm/capi/instance.hpp
  silkworm/capi/rpcdaemon.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
Labels: maintenance

#2584 rpcdaemon: fix and improve perf in eth_getLogs
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/rpc/core/logs_walker.cpp
Labels: json rpc api, performance, erigon3

#2582 datastore: kvdb schema and DHII entities
  cmd/capi/execute.cpp
  cmd/dev/check_changes.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/staged_pipeline.cpp
  silkworm/capi/fork_validator.cpp
  silkworm/capi/instance.hpp
  silkworm/capi/rpcdaemon.cpp
  silkworm/capi/silkworm.cpp
  silkworm/db/data_store.cpp
  silkworm/db/data_store.hpp
  silkworm/db/datastore/data_store.hpp
  silkworm/db/datastore/kvdb/database.cpp
  silkworm/db/datastore/kvdb/database.hpp
  silkworm/db/datastore/kvdb/domain.hpp
  silkworm/db/datastore/kvdb/history.hpp
  silkworm/db/datastore/kvdb/inverted_index.hpp
  silkworm/db/datastore/kvdb/schema.cpp
  silkworm/db/datastore/kvdb/schema.hpp
  silkworm/db/datastore/schema.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.hpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/state/schema_config.cpp
  silkworm/db/state/schema_config.hpp
  silkworm/db/test_util/temp_chain_data.hpp
  silkworm/db/test_util/test_database_context.hpp
  silkworm/execution/local_state.hpp
  silkworm/node/node.cpp
  silkworm/node/stagedsync/stages_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/sync/internals/header_retrieval_test.cpp
  silkworm/sync/messages/inbound_get_block_bodies.cpp
  silkworm/sync/messages/inbound_get_block_headers.cpp
Labels: erigon3

#2588 rpcdaemon: refactor OtsRpcApi::collect_transactions_with_receipts
  silkworm/rpc/commands/ots_api.cpp
Labels: maintenance

#2590 evm: apply state diff from evmone APIv2 if enabled
  silkworm/core/execution/execution_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor_test.cpp
  silkworm/core/state/intra_block_state.hpp
Labels: evmone apiv2

#2591 test: enable evmone APIv2 for cmd/test/ethereum
  cmd/test/ethereum.cpp
  silkworm/core/protocol/blockchain.cpp
Labels: evmone apiv2

#2595 rpcdaemon: remove methods in db::chain namespace
  .github/workflows/rpc-integration-tests.yml
  silkworm/db/chain/chain.cpp
  silkworm/db/chain/chain.hpp
  silkworm/db/chain/chain_test.cpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/logs_walker.cpp
Labels: maintenance, erigon3

#2600 rpcdaemon: remove db::chain read header hash
  silkworm/db/chain/chain.cpp
  silkworm/db/chain/chain.hpp
  silkworm/db/chain/chain_storage.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/local_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/test_util/mock_chain_storage.hpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/core/logs_walker.cpp
Labels: maintenance, erigon3

#2602 rpcdaemon: use txn state for bundles in eth_callMany
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/call_many.hpp
Labels: enhancement, json rpc api, erigon3

#2587 rpcdaemon: fix data race in http::Server stop
  silkworm/capi/silkworm_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
Labels: maintenance

#2606 ci: update lint and wasm jobs to Ubuntu 24
  .circleci/config.yml
  .github/workflows/macOS.yml
  cmake/cmake_format.cmake
  cmake/cmake_format.yaml
  cmake/conan.cmake
  cmake/format.cmake
  silkworm/interfaces/generate_grpc.cmake
  tools/lint/ci_format.sh
Labels: maintenance

#2609 evm: enable evmone APIv2 in tool/test utils
  cmd/dev/check_changes.cpp
  cmd/dev/scan_txs.cpp
  cmd/state-transition/state_transition.cpp
  silkworm/core/execution/execution.hpp
  silkworm/db/test_util/test_database_context.cpp
Labels: evmone apiv2

#2610 cmake: TSAN suppression for MDBX false-positives in unit tests
  cmake/run_unit_tests.cmake
  cmake/run_unit_tests.sh
  tsan_suppressions.txt
Labels: maintenance, unit testing

#2603 rpcdaemon: StateFactory rework
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/execution/state_factory.cpp
  silkworm/execution/state_factory.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/receipts.cpp
Labels: maintenance, erigon3

#2599 node: handle code hash not found in Execution unwind
  silkworm/node/stagedsync/stages/stage_execution.cpp
Labels: maintenance

#2596 node: replace incremental with full mode in InterHashes stage
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.hpp
Labels: maintenance

#2594 node: fix reached block num in BlockHashes for existing blocks
  cmd/dev/staged_pipeline.cpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
Labels: maintenance

#2612 ci: fix TSAN suppressions
  .circleci/config.yml
  Makefile
  cmake/run_unit_tests.cmake
  cmake/run_unit_tests.sh
  tools/sanitizer/tsan_suppressions.txt
Labels: maintenance

#2613 docs: copy db_toolbox doc from GH wiki
  docs/db_toolbox.md
Labels: documentation

#2611 rpcdaemon: erigon_getLatestLogs for e3
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/common/util.hpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader_test.cpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/types/filter.hpp
Labels: json rpc api, erigon3

#2615 rpcdaemon: enabled erigon_getLatestLogs tests
  .github/workflows/run_integration_tests.sh
Labels: integration testing, erigon3

#2605 node: fix task caller lifecycle in Triggers schedule
  silkworm/node/stagedsync/stages/stage_triggers.cpp
  silkworm/node/stagedsync/stages/stage_triggers.hpp
  silkworm/node/stagedsync/stages/stage_triggers_test.cpp
Labels: maintenance

#2617 rpcdaemon: fix use-after-free in erigon_getLatestLogs
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/logs_walker.hpp
Labels: maintenance, erigon3

#2616 rpcdaemon: add NoRefunds flag in some debug API
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
  silkworm/rpc/core/evm_debug_test.cpp
Labels: enhancement, json rpc api

#2618 rpcdaemon: fix in debug_getRawHeader/debug_getRawBlock in case of header/block not found
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/debug_api.cpp
Labels: maintenance

#2619 rpcdaemon: debug_traceBlockByNumber with block number in hex format
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/debug_api.cpp
Labels: enhancement, json rpc api

#2623 rpcdaemon: StateReader using only txn_number
  silkworm/db/kv/state_reader.cpp
  silkworm/db/kv/state_reader.hpp
  silkworm/execution/remote_state.hpp
  silkworm/execution/remote_state_test.cpp
  silkworm/execution/state_factory.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance, erigon3

#2620 rpcdaemon: enable debug_traceCallMany tests
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
Labels: maintenance, integration testing

#2627 rpcdaemon: impl API debug_getRawReceipts
  .github/workflows/rpc-integration-tests.yml
  docs/JSON-RPC-API.md
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/debug_api.hpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/receipts.hpp
  silkworm/rpc/ethdb/cbor_test.cpp
  silkworm/rpc/json/receipt.cpp
  silkworm/rpc/json/receipt_test.cpp
  silkworm/rpc/json_rpc/methods.hpp
  silkworm/rpc/types/receipt.cpp
  silkworm/rpc/types/receipt.hpp
  silkworm/rpc/types/receipt_test.cpp
Labels: enhancement, json rpc api

#2631 rpcdaemon: remove unused code in EVMExecutor
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance

#2628 rpcdaemon: remove unnecessary call to read_rlp_transactions
  silkworm/db/chain/remote_chain_storage.cpp
Labels: maintenance

#2626 rpcdaemon: debug_traceBlockByNumber support for block tags
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/commands/debug_api.cpp
Labels: enhancement, json rpc api

#2607 cmake: upgrade to Conan 2 (#2318)
  .circleci/config.yml
  .github/actions/fuzzer-common-steps/action.yml
  .github/workflows/macOS.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  README.md
  cmake/compiler_settings.cmake
  cmake/conan.cmake
  cmake/conan_quiet.cmake
  cmake/conan_quiet.sh
  cmake/profiles/experimental/linux_arm64_gcc_12_debug
  cmake/profiles/experimental/linux_arm64_gcc_12_release
  cmake/profiles/experimental/linux_x64_clang_16_release
  cmake/profiles/experimental/linux_x64_gcc_12_debug
  cmake/profiles/experimental/linux_x64_gcc_12_release
  cmake/profiles/experimental/macos_arm64_clang_14_debug
  cmake/profiles/experimental/macos_arm64_clang_14_release
  cmake/profiles/experimental/macos_x64_clang_14_debug
  cmake/profiles/experimental/macos_x64_clang_14_release
  cmake/profiles/experimental/readme.txt
  cmake/profiles/experimental/windows_msvc_17_debug
  cmake/profiles/experimental/windows_msvc_17_release
  cmake/profiles/linux_x64_clang_16_debug
  cmake/profiles/linux_x64_clang_16_release
  cmake/profiles/linux_x64_gcc_11_debug
  cmake/profiles/linux_x64_gcc_11_release
  cmake/profiles/macos_arm64_clang_13_debug
  cmake/profiles/macos_arm64_clang_13_release
  cmake/profiles/macos_x64_clang_13_debug
  cmake/profiles/macos_x64_clang_13_release
  cmake/profiles/wasi_release
  cmake/profiles/windows_msvc_16_debug
  cmake/profiles/windows_msvc_16_release
  cmake/profiles/windows_msvc_193_debug
  cmake/profiles/windows_msvc_193_release
  cmake/setup/compiler_install.sh
  conanfile.py
  docs/fuzzer.md
  tests/docker/Dockerfile
  third_party/cmake-conan/LICENSE
  third_party/cmake-conan/conan.cmake
  third_party/cmake-conan/conan_provider.cmake
  third_party/cmake-conan/readme.txt
  third_party/erigon-mdbx-go/CMakeLists.txt
  third_party/gmp/CMakeLists.txt
  third_party/libff/CMakeLists.txt
  third_party/llvm/README.md
Labels: maintenance
