Repository erigontech/silkworm, pull requests merged in 2024-09, with the labels that each got.

#2279 BitTorrentClient related refactorings
  cmd/capi/execute.cpp
  cmd/common/settings.hpp
  cmd/common/snapshot_options.hpp
  cmd/dev/check_changes.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  silkworm/capi/instance.hpp
  silkworm/db/access_layer.cpp
  silkworm/db/blocks/bodies/body_index.hpp
  silkworm/db/blocks/headers/header_index.hpp
  silkworm/db/freezer.cpp
  silkworm/db/freezer.hpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_merger.cpp
  silkworm/db/snapshot_merger.hpp
  silkworm/db/snapshot_recompress.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/bittorrent/client.hpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
  silkworm/db/snapshots/bittorrent/settings.hpp
  silkworm/db/snapshots/bittorrent/web_seed_client.cpp
  silkworm/db/snapshots/bittorrent/web_seed_client_test.cpp
  silkworm/db/snapshots/config.cpp
  silkworm/db/snapshots/config_test.cpp
  silkworm/db/snapshots/index.hpp
  silkworm/db/snapshots/index_builder.hpp
  silkworm/db/snapshots/snapshot_bundle.hpp
  silkworm/db/snapshots/snapshot_bundle_factory.hpp
  silkworm/db/snapshots/snapshot_path.cpp
  silkworm/db/snapshots/snapshot_path.hpp
  silkworm/db/snapshots/snapshot_path_test.cpp
  silkworm/db/snapshots/snapshot_reader.hpp
  silkworm/db/snapshots/snapshot_repository.cpp
  silkworm/db/snapshots/snapshot_repository.hpp
  silkworm/db/snapshots/snapshot_settings.hpp
  silkworm/db/snapshots/snapshot_writer.hpp
  silkworm/db/test_util/temp_snapshots.hpp
  silkworm/db/transactions/txn_index.hpp
  silkworm/db/transactions/txn_to_block_index.hpp
  silkworm/db/transactions/txs_and_bodies_query.hpp
  silkworm/node/node.cpp
  silkworm/node/node.hpp
  silkworm/node/settings.hpp
  silkworm/rpc/daemon.hpp
Labels: maintenance

#2288 db: fix clang tidy and windows build after PR 2279
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
Labels: maintenance

#2281 rpcdaemon: fix gas_cost and memory of last STOP opcode in debug API
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
Labels: maintenance

#2287 rpcdaemon: some fixes after porting erigon 2.60
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/txpool_api.cpp
Labels: maintenance

#2289 rpcdaemon: fix clang tidy after PR 2287
  silkworm/rpc/commands/txpool_api.cpp
Labels: maintenance

#2283 snapshots: torrent file creation
  silkworm/core/common/bytes_to_string.hpp
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.hpp
  silkworm/db/snapshots/bittorrent/torrent_file_test.cpp
  silkworm/db/snapshots/bittorrent/trackers.cpp
  silkworm/db/snapshots/bittorrent/trackers.hpp
Labels: snapshots

#2293 db: fix clang tidy after PR 2283
  silkworm/db/snapshots/bittorrent/torrent_file.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.hpp
Labels: maintenance

#2286 infra: fix log timer lifecycle in execution pipeline
  silkworm/infra/common/asio_timer.hpp
  silkworm/infra/common/timer.cpp
  silkworm/infra/common/timer.hpp
  silkworm/infra/common/timer_test.cpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
Labels: maintenance

#2291 db: fix completed count when the same snapshot is downloaded twice
  silkworm/db/snapshot_sync.cpp
Labels: maintenance

#2292 cmd: support version update in schema command of snapshots tool
  cmd/dev/db_toolbox.cpp
Labels: enhancement

#2284 core: implement bor_transfer
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/rule_set.hpp
  silkworm/rpc/core/evm_executor.cpp
Labels: polygon

#2294 db: make SnapshotSync::download_snapshots callable multiple times again
  silkworm/db/snapshot_sync.cpp
Labels: maintenance

#2297 infra: fix timer cancellation using RAII
  silkworm/infra/common/timer.cpp
  silkworm/infra/common/timer.hpp
  silkworm/infra/common/timer_test.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
Labels: maintenance

#2295 rpcdaemon: add blob gas fields on tx
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/json/transaction.cpp
  silkworm/rpc/json/transaction.hpp
  silkworm/rpc/json/types.cpp
Labels: maintenance

#2290 db: move snapshots management from node to snapshot_sync
  cmd/dev/snapshots.cpp
  cmd/silkworm.cpp
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/access_layer_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
  silkworm/db/snapshots/bittorrent/settings.hpp
  silkworm/db/snapshots/bittorrent/web_seed_client_test.cpp
  silkworm/db/snapshots/config.cpp
  silkworm/db/snapshots/config.hpp
  silkworm/db/snapshots/config_test.cpp
  silkworm/db/util.hpp
  silkworm/infra/concurrency/awaitable_condition_variable.hpp
  silkworm/infra/concurrency/awaitable_future.hpp
  silkworm/node/node.cpp
  silkworm/node/node.hpp
Labels: snapshots

#2310 db: fix clang tidy after PR 2290
  cmd/dev/snapshots.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/node/node.cpp
Labels: maintenance

#2309 doc: erigon++ platforms
  README.md
Labels: documentation

#2302 db: snapshots seeding
  silkworm/db/snapshot_merger.cpp
  silkworm/db/snapshot_merger.hpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.hpp
  silkworm/db/snapshots/config.cpp
  silkworm/db/snapshots/config.hpp
  silkworm/db/snapshots/config_test.cpp
  silkworm/db/snapshots/snapshot_path.hpp
  silkworm/db/snapshots/snapshot_repository.hpp
  silkworm/db/snapshots/snapshot_size.hpp
Labels: snapshots

#2306 sentry: handle errors when accessing socket endpoints
  silkworm/sentry/rlpx/client.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/rlpx/peer.hpp
  silkworm/sentry/rlpx/server.cpp
Labels: maintenance

#2314 db: fix clang tidy after PR 2302
  silkworm/db/snapshot_merger.cpp
  silkworm/db/snapshot_merger.hpp
  silkworm/db/snapshots/bittorrent/torrent_file.cpp
  silkworm/db/snapshots/bittorrent/torrent_file.hpp
Labels: maintenance

#2305 rpcdaemon: remove base fee from to_transaction
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/types/call.hpp
  silkworm/rpc/types/call_test.cpp
Labels: maintenance

#2321 cmake: update min macOS to 14.0
  README.md
  cmake/toolchain/cxx20.cmake
  cmd/capi/sample-go-client/README.md
Labels: maintenance

#2315 infra: logs subfolder in data directory
  silkworm/infra/common/directories.hpp
Labels: maintenance

#2322 rpcdaemon: new gas bailout handling
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/state/intra_block_state.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2328 fix clang tidy and sanitizer builds after PR 2320-2322
  cmake/conan.cmake
  conanfile.py
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#2316 snapshots: refactor SnapshotSync::download_and_index_snapshots
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshots/snapshot_repository.cpp
Labels: snapshots, maintenance

#2323 rpcdaemon: add eth_estimateGas extra field for gas limit
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
Labels: enhancement, json rpc api

#2332 rpcdaemon: fix clang tidy after PR 2323
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance

#2329 test: switch fuzzer to single thread and increase its memory limit
  .github/workflows/rpc-fuzzer-tests.yml
Labels: maintenance

#2336 db: fix clang tidy after PR 2325
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2331 db: rename mdbx::env db to env
  cmd/silkworm.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/db/db_utils_test.cpp
  silkworm/db/mdbx/mdbx.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync.hpp
  silkworm/db/test_util/test_database_context.cpp
  silkworm/db/test_util/test_database_context.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/test_util/api_test_database.hpp
Labels: maintenance

#2340 cmd: fix clang tidy after PR 2331
  cmd/silkworm.cpp
Labels: maintenance

#2326 rpcdaemon: fix memory size 0, special case on SELF_DESTRUCT
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2334 lint: fix cppcoreguidelines-slicing in snapshots cmd
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/types/block.hpp
  silkworm/db/buffer.cpp
Labels: maintenance

#2335 snapshots: fix torrent.verify_on_startup
  cmd/common/snapshot_options.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/bittorrent/client.hpp
  silkworm/db/snapshots/bittorrent/client_test.cpp
  silkworm/db/snapshots/bittorrent/settings.hpp
  silkworm/db/snapshots/snapshot_settings.hpp
Labels: snapshots

#2339 rpcdaemon: fix response in case no tx present
  silkworm/rpc/commands/txpool_api.cpp
Labels: maintenance

#2337 snapshots: --snapshots.stop option
  cmd/common/snapshot_options.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshots/snapshot_settings.hpp
Labels: snapshots

#2341 rpcdaemon: DebugTracer code refactoring and cleanup
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2343 Add option to do table deep check with db_toolbox
  cmd/dev/db_toolbox.cpp
Labels: enhancement

#2346 tidy: upgrade to v18 (#2277)
  .circleci/config.yml
  cmd/dev/snapshots.cpp
Labels: maintenance

#2307 Use the same block executor for both CAPI and StagedSync
  silkworm/capi/silkworm.cpp
  silkworm/node/CMakeLists.txt
  silkworm/node/execution/block/CMakeLists.txt
  silkworm/node/execution/block/block_executor.cpp
  silkworm/node/execution/block/block_executor.hpp
  silkworm/node/stagedsync/stages/CMakeLists.txt
  silkworm/node/stagedsync/stages/stage_execution.cpp
Labels: maintenance

#2345 tidy: include db headers
  .clang-tidy
  silkworm/db/access_layer.cpp
  silkworm/db/db_utils.cpp
  silkworm/db/etl/buffer.hpp
  silkworm/db/etl/collector.cpp
  silkworm/db/etl/collector.hpp
  silkworm/db/etl/file_provider.cpp
  silkworm/db/etl/util.hpp
  silkworm/db/mdbx/mdbx.cpp
  silkworm/db/mdbx/mdbx.hpp
  silkworm/db/mdbx_test.cpp
  silkworm/db/snapshots/common/iterator/iterator_read_into_vector.hpp
  silkworm/db/snapshots/index_builder.hpp
  silkworm/db/snapshots/rec_split/common/common.hpp
  silkworm/db/snapshots/rec_split/encoding/elias_fano.hpp
  silkworm/db/snapshots/rec_split/rec_split.cpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
  silkworm/db/snapshots/rec_split/rec_split_par_test.cpp
  silkworm/db/snapshots/rec_split/rec_split_seq_test.cpp
  silkworm/db/snapshots/seg/compressor/pattern_extractor.hpp
  silkworm/db/snapshots/seg/decompressor.cpp
  silkworm/db/snapshots/seg/decompressor.hpp
  silkworm/db/snapshots/snapshot_type.hpp
  silkworm/db/stage.hpp
  silkworm/db/test_util/temp_snapshots.hpp
  silkworm/db/transactions/txs_and_bodies_query.hpp
  silkworm/node/stagedsync/stages/stage_blockhashes.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_call_trace_index.cpp
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_finish.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_history_index.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
  silkworm/node/stagedsync/stages/stage_log_index.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
Labels: maintenance

#2344 execution: rename BlockNumAndHash to BlockId
  silkworm/core/types/block_id.hpp
  silkworm/execution/api/active_direct_service.cpp
  silkworm/execution/api/active_direct_service.hpp
  silkworm/execution/api/direct_service.cpp
  silkworm/execution/api/direct_service.hpp
  silkworm/execution/api/endpoint/validation.hpp
  silkworm/execution/api/service.hpp
  silkworm/execution/grpc/client/endpoint/validation.cpp
  silkworm/execution/grpc/client/endpoint/validation.hpp
  silkworm/execution/grpc/client/remote_client.cpp
  silkworm/execution/grpc/server/endpoint/validation.cpp
  silkworm/execution/grpc/server/endpoint/validation.hpp
  silkworm/node/execution/active_direct_service_test.cpp
  silkworm/node/execution/direct_service_test.cpp
  silkworm/sync/sync_pos_test.cpp
  silkworm/sync/test_util/mock_execution_client.hpp
Labels: maintenance

#2351 node: fix revision check for tx type in stage Senders
  silkworm/node/execution/active_direct_service_test.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/node/stagedsync/stages_test.cpp
Labels: maintenance

#2352 rpcdaemon: trap einval exception to manage block not found
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance

#2356 rpcdaemon: fix block and block_from_tx_hash providers in RemoteStorage
  silkworm/rpc/ethdb/kv/backend_providers.hpp
Labels: maintenance

#2357 rpcdaemon: add catch invalid argument in debug_accountStorageAt, trace_filter, eth_estimateGas
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2360 node: fix Execution stage unwind after invalid block
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages_test.cpp
Labels: maintenance

#2354 core, rpcdaemon: move gas+funds bailout mechanism into evm
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#2355 sentry: move init to node
  cmd/common/node_options.cpp
  cmd/common/node_options.hpp
  cmd/common/settings.hpp
  cmd/dev/backend_kv_server.cpp
  cmd/silkworm.cpp
  silkworm/node/node.cpp
  silkworm/node/node.hpp
  silkworm/node/settings.hpp
  silkworm/sentry/eth/status_data_provider.cpp
  silkworm/sentry/eth/status_data_provider.hpp
Labels: maintenance

#2361 node: refactor NodeSettings.asio_context
  cmd/dev/backend_kv_server.cpp
  cmd/dev/db_toolbox.cpp
  silkworm/capi/fork_validator.cpp
  silkworm/node/common/node_settings.hpp
  silkworm/node/execution/active_direct_service_test.cpp
  silkworm/node/execution/direct_service_test.cpp
  silkworm/node/execution/header_chain_plus_exec_test.cpp
  silkworm/node/node.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/execution_pipeline.hpp
  silkworm/node/stagedsync/forks/extending_fork.cpp
  silkworm/node/stagedsync/forks/extending_fork.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/node/stagedsync/forks/fork_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain.hpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
  silkworm/node/stagedsync/timer_factory.hpp
  silkworm/node/test_util/mock_execution_engine.hpp
Labels: maintenance

#2353 rpcdaemon: gas cost in trace_replay* API
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2365 sentry: move make_client_id to ApplicationInfo
  cmd/sentry.cpp
  cmd/silkworm.cpp
  silkworm/infra/common/application_info.cpp
  silkworm/infra/common/application_info.hpp
  silkworm/sentry/sentry.cpp
  silkworm/sentry/sentry.hpp
Labels: maintenance

#2366 node: exec_api_address setting
  cmd/common/node_options.cpp
  silkworm/node/common/node_settings.hpp
  silkworm/node/node.cpp
  silkworm/node/settings.hpp
Labels: enhancement, modular consensus

#2368 db: move db setup from silkworm.cpp into Node and db
  cmd/CMakeLists.txt
  cmd/silkworm.cpp
  silkworm/db/chain_data_init.cpp
  silkworm/db/chain_data_init.hpp
  silkworm/node/node.cpp
  silkworm/node/node.hpp
Labels: maintenance

#2371 qa-tests: split integration tests on Erigon v2 and v3
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing, integration testing

#2377 tests: update fuzzer to Clang 16.0.6
  third_party/llvm/CMakeLists.txt
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer.a
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer_interceptors.a
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer_no_main.a
  third_party/llvm/lib_libc++/clang/16.0.6/lib/x86_64-linux/libclang_rt.fuzzer.a
  third_party/llvm/lib_libc++/clang/16.0.6/lib/x86_64-linux/libclang_rt.fuzzer_interceptors.a
  third_party/llvm/lib_libc++/clang/16.0.6/lib/x86_64-linux/libclang_rt.fuzzer_no_main.a
Labels: maintenance, fuzzy testing

#2374 snapshots: move encoding modules to common
  silkworm/db/snapshots/common/encoding/elias_fano.hpp
  silkworm/db/snapshots/common/encoding/elias_fano_test.cpp
  silkworm/db/snapshots/common/encoding/golomb_rice.hpp
  silkworm/db/snapshots/common/encoding/golomb_rice_test.cpp
  silkworm/db/snapshots/common/encoding/sequence.hpp
  silkworm/db/snapshots/common/encoding/sequence_test.cpp
  silkworm/db/snapshots/common/encoding/util.hpp
  silkworm/db/snapshots/index/btree_index.hpp
  silkworm/db/snapshots/rec_split/murmur_hash3.cpp
  silkworm/db/snapshots/rec_split/murmur_hash3.hpp
  silkworm/db/snapshots/rec_split/murmur_hash3_test.cpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
Labels: maintenance

#2378 rpcdaemon: fix gas cost in case of early failures
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug_test.cpp
Labels: maintenance

#2367 db: add BTree index for kv snapshots
  cmd/dev/snapshots.cpp
  silkworm/db/snapshot_decompressor_test.cpp
  silkworm/db/snapshots/common/bitmask_operators.hpp
  silkworm/db/snapshots/common/encoding/elias_fano.hpp
  silkworm/db/snapshots/common/encoding/elias_fano_test.cpp
  silkworm/db/snapshots/common/encoding/golomb_rice.hpp
  silkworm/db/snapshots/common/encoding/golomb_rice_test.cpp
  silkworm/db/snapshots/common/encoding/sequence.hpp
  silkworm/db/snapshots/common/encoding/sequence_test.cpp
  silkworm/db/snapshots/common/encoding/util.hpp
  silkworm/db/snapshots/index/btree.cpp
  silkworm/db/snapshots/index/btree.hpp
  silkworm/db/snapshots/index/btree_index.cpp
  silkworm/db/snapshots/index/btree_index.hpp
  silkworm/db/snapshots/index/btree_index_test.cpp
  silkworm/db/snapshots/rec_split/murmur_hash3.cpp
  silkworm/db/snapshots/rec_split/murmur_hash3.hpp
  silkworm/db/snapshots/rec_split/murmur_hash3_test.cpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
  silkworm/db/snapshots/seg/decompressor.cpp
  silkworm/db/snapshots/seg/decompressor.hpp
Labels: snapshots, erigon3

#2388 capi: skip some unit tests in macOS after PR 2308
  silkworm/capi/silkworm_test.cpp
Labels: maintenance
