Repository erigontech/silkworm, pull requests merged in 2024-08, with the labels that each got.

#2198 db: temporal KV client history_range API via gRPC
  cmd/dev/grpc_toolbox.cpp
  silkworm/core/common/bytes_to_string.hpp
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/endpoint/key_value.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/temporal_range.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/service.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/endpoint/temporal_range.cpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/grpc/test_util/sample_protos.hpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: enhancement, temporal kv

#2199 rpcdaemon: fix clang tidy after PR 2198
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: maintenance

#2197 db: reduce copies in KV gRPC remote cursor
  silkworm/db/kv/grpc/client/remote_cursor.cpp
Labels: maintenance

#2187 rpcdaemon: fix trace_* API family gas cost
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2200 clang-tidy: address google-runtime-int
  .clang-tidy
  cmd/state-transition/expected_state.cpp
  cmd/state-transition/expected_state.hpp
  silkworm/core/common/assert.cpp
  silkworm/core/common/assert.hpp
  silkworm/db/log_cbor.cpp
  silkworm/db/receipt_cbor.cpp
  silkworm/infra/common/bounded_buffer_test.cpp
  silkworm/infra/common/measure.hpp
  silkworm/infra/common/mem_usage.cpp
  silkworm/rpc/ethdb/cbor.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/json_rpc/validator.cpp
  silkworm/sync/internals/body_retrieval.hpp
  silkworm/sync/internals/header_retrieval.cpp
  silkworm/sync/internals/header_retrieval.hpp
  silkworm/sync/internals/statistics.cpp
  silkworm/sync/messages/outbound_new_block.hpp
Labels: maintenance

#2202 db: temporal KV client domain_range API via gRPC
  cmd/dev/README.md
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/endpoint/temporal_point.hpp
  silkworm/db/kv/api/endpoint/temporal_range.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/service.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/endpoint/temporal_point_test.cpp
  silkworm/db/kv/grpc/client/endpoint/temporal_range.cpp
  silkworm/db/kv/grpc/client/endpoint/temporal_range_test.cpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/grpc/test_util/sample_protos.hpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: enhancement, temporal kv

#2207 db: temporal KV client history_seek API via gRPC
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/service.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: enhancement, temporal kv

#2204 rpc-integration-tests: avoid saving unuseful result
  .github/workflows/rpc-integration-tests.yml
Labels: integration testing

#2210 db: temporal KV client domain_get API via gRPC
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/service.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/grpc/test_util/sample_protos.hpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: enhancement, temporal kv

#2205 rpc-performance-tests: preserve the results
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#2209 db: remove unused table names
  silkworm/db/access_layer_test.cpp
  silkworm/db/stages.cpp
  silkworm/db/stages.hpp
  silkworm/db/tables.hpp
Labels: maintenance

#2208 core: convert literal operators to consteval
  silkworm/core/common/base.hpp
Labels: maintenance

#2212 db: snapshot freezers cleanup
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/bodies/body_snapshot_freezer.cpp
  silkworm/db/bodies/body_snapshot_freezer.hpp
  silkworm/db/freezer.cpp
  silkworm/db/freezer.hpp
  silkworm/db/headers/header_snapshot_freezer.cpp
  silkworm/db/headers/header_snapshot_freezer.hpp
  silkworm/db/snapshot_freezer.hpp
  silkworm/db/transactions/txn_snapshot_freezer.cpp
  silkworm/db/transactions/txn_snapshot_freezer.hpp
Labels: snapshots

#2201 capi: fork validator
  silkworm/capi/CMakeLists.txt
  silkworm/capi/fork_validator.cpp
  silkworm/capi/instance.hpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
  silkworm/db/kv/grpc/server/kv_calls_test.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/execution_engine.hpp
  silkworm/node/stagedsync/forks/main_chain.cpp
Labels: c api, erigon2 backlog, execution at tip

#2216 capi: fix Windows build after PR 2201
  silkworm/capi/fork_validator.cpp
Labels: maintenance

#2211 rpcdaemon: fix memory gas cost in call
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2214 rpcdaemon: fixing fuzzer tests
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
Labels: maintenance, fuzzer trophy

#2219 ci: avoid cancelling master workflow pushing on ci/* branch
  .github/workflows/macOS.yml
  .github/workflows/windows.yml
Labels: maintenance

#2213 clang-tidy: fix hicpp-no-malloc & misc-unused-using-decls
  .clang-tidy
  cmd/silkworm.cpp
  silkworm/capi/rpcdaemon.cpp
  silkworm/core/crypto/ecdsa.c
  silkworm/core/crypto/ecdsa.h
  silkworm/db/chain/chain_test.cpp
  silkworm/db/chain/remote_chain_storage_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/infra/common/bounded_buffer_test.cpp
  silkworm/infra/grpc/client/call_test.cpp
  silkworm/node/execution/api/active_direct_service_test.cpp
  silkworm/node/execution/api/direct_service_test.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_senders.hpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/types/chain_config_test.cpp
Labels: maintenance

#2221 rpcdaemon: fix data storage access in local state
  .github/workflows/rpc-integration-tests.yml
  silkworm/db/state/local_state.cpp
  silkworm/db/state/local_state.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2229 db: first and last queries in KV local cursor
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/kv/api/cursor.hpp
  silkworm/db/kv/api/local_cursor.cpp
  silkworm/db/kv/api/local_cursor.hpp
  silkworm/db/kv/api/local_cursor_test.cpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/grpc/client/remote_cursor.cpp
  silkworm/db/kv/grpc/client/remote_cursor.hpp
  silkworm/db/kv/grpc/client/remote_cursor_test.cpp
  silkworm/db/mdbx/mdbx.cpp
  silkworm/db/mdbx/mdbx.hpp
  silkworm/db/test_util/mock_cursor.hpp
  silkworm/infra/grpc/test_util/grpc_matcher.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
Labels: maintenance

#2233 RPC Integration Tests: skip failing trace_rawTransaction test
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance

#2220 db: snapshots repository thread safety
  cmd/capi/execute.cpp
  cmd/dev/snapshots.cpp
  silkworm/db/access_layer.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshots/repository.cpp
  silkworm/db/snapshots/repository.hpp
  silkworm/db/transactions/txn_queries.hpp
Labels: snapshots

#2238 db: fix Clang Tidy after PR 2220
  silkworm/db/snapshots/repository.cpp
  silkworm/db/snapshots/repository.hpp
Labels: maintenance

#2231 db: txn unique numbering over KV API
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/kv/txn_num_test.cpp
  silkworm/db/tables.hpp
Labels: enhancement, temporal kv

#2232 rpcdaemon: make TraceEx optional to match Erigon output in OUT_OF_GAS case
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2234 style: typedef consistency improvements
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/snapshots/common/iterator/map_values_view.hpp
  silkworm/db/snapshots/index_builder.hpp
  silkworm/db/snapshots/repository.cpp
  silkworm/db/snapshots/repository.hpp
  silkworm/db/snapshots/seg/decompressor.hpp
  silkworm/db/snapshots/snapshot_reader.hpp
  silkworm/db/snapshots/snapshot_writer.hpp
  silkworm/db/transactions/txs_and_bodies_query.hpp
  silkworm/rpc/core/filter_storage.hpp
  silkworm/rpc/core/gas_price_oracle.hpp
  silkworm/rpc/types/log.hpp
  silkworm/sentry/api/router/messages_call.hpp
  silkworm/sentry/api/router/peer_events_call.hpp
  silkworm/sentry/common/random.hpp
  silkworm/sync/packets/hash_or_number.hpp
Labels: maintenance

#2240 stagedsync: remove unused stage names
  silkworm/db/stages.hpp
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance

#2241 db: move headers/bodies under blocks
  cmd/dev/snapshots.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/db/access_layer.cpp
  silkworm/db/blocks/bodies/body_index.cpp
  silkworm/db/blocks/bodies/body_index.hpp
  silkworm/db/blocks/bodies/body_queries.hpp
  silkworm/db/blocks/bodies/body_snapshot.cpp
  silkworm/db/blocks/bodies/body_snapshot.hpp
  silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
  silkworm/db/blocks/bodies/body_snapshot_freezer.hpp
  silkworm/db/blocks/bodies/body_txs_amount_query.cpp
  silkworm/db/blocks/bodies/body_txs_amount_query.hpp
  silkworm/db/blocks/bodies/body_txs_amount_query_test.cpp
  silkworm/db/blocks/headers/header_index.cpp
  silkworm/db/blocks/headers/header_index.hpp
  silkworm/db/blocks/headers/header_queries.hpp
  silkworm/db/blocks/headers/header_snapshot.cpp
  silkworm/db/blocks/headers/header_snapshot.hpp
  silkworm/db/blocks/headers/header_snapshot_freezer.cpp
  silkworm/db/blocks/headers/header_snapshot_freezer.hpp
  silkworm/db/freezer.cpp
  silkworm/db/snapshot_benchmark.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_index_builder_test.cpp
  silkworm/db/snapshot_recompress.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshot_test.cpp
  silkworm/db/transactions/txn_index.cpp
Labels: snapshots, maintenance

#2242 clang-tidy: modernize-use-using & modernize-use-transparent-functors
  .clang-tidy
  silkworm/core/common/lru_cache.hpp
  silkworm/db/snapshots/seg/compressor/huffman_code.cpp
  silkworm/db/snapshots/seg/compressor/pattern_aggregator.cpp
  silkworm/sentry/rlpx/crypto/aes.hpp
Labels: maintenance

#2246 db: refactor KV Tx API to use agrpc
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_cursor.cpp
  silkworm/db/kv/grpc/client/remote_cursor.hpp
  silkworm/db/kv/grpc/client/remote_cursor_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/grpc/client/rpc.hpp
  silkworm/infra/grpc/client/bidi_streaming_rpc.hpp
  silkworm/infra/grpc/client/server_streaming_rpc.hpp
  silkworm/infra/grpc/test_util/grpc_actions.hpp
  silkworm/infra/grpc/test_util/grpc_responder.hpp
  silkworm/rpc/ethdb/kv/remote_database_test.cpp
Labels: maintenance

#2247 rpcdaemon: fixes on debug_accountRange
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/storage_walker.cpp
  silkworm/rpc/core/storage_walker.hpp
Labels: maintenance

#2248 infra: encapsulate usage of asio co_spawn
  silkworm/db/kv/api/service_router.cpp
  silkworm/db/kv/state_changes_stream.cpp
  silkworm/infra/concurrency/awaitable_wait_for_all.hpp
  silkworm/infra/concurrency/awaitable_wait_for_one.hpp
  silkworm/infra/concurrency/co_spawn_sw.hpp
  silkworm/infra/concurrency/parallel_group_test.cpp
  silkworm/infra/concurrency/spawn.hpp
  silkworm/infra/concurrency/spawn_test.cpp
  silkworm/infra/concurrency/sync_wait.hpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/test_util/context_test_base.hpp
  silkworm/node/execution/api/active_direct_service.cpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/stages/stage_triggers.cpp
  silkworm/rpc/daemon.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.cpp
  silkworm/sentry/message_receiver.cpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/peer_manager_api.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pow.cpp
Labels: maintenance

#2251 core: decode account from E3 encoded storage
  silkworm/core/types/account.cpp
  silkworm/core/types/account.hpp
  silkworm/core/types/account_test.cpp
Labels: erigon3

#2254 core: fix decoding account from E3 encoded storage
  silkworm/core/types/account.cpp
Labels: maintenance

#2249 db: unify read_canonical_hash/read_canonical_header_hash
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
  silkworm/db/blocks/headers/header_snapshot_freezer.cpp
  silkworm/db/chain/chain_storage.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/local_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/chain_head.cpp
  silkworm/db/db_utils_test.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/state/local_state.cpp
  silkworm/db/state/remote_state.cpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/test_util/mock_chain_storage.hpp
  silkworm/db/transactions/txn_snapshot_freezer.cpp
  silkworm/node/stagedsync/execution_engine_test.cpp
  silkworm/node/stagedsync/forks/canonical_chain.cpp
  silkworm/node/stagedsync/forks/fork_test.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/forks/main_chain_test.cpp
  silkworm/node/stagedsync/stages/stage_bodies_test.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_headers_test.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup.cpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/core/cached_chain.cpp
  silkworm/sync/internals/header_chain_plus_exec_test.cpp
  silkworm/sync/internals/header_retrieval.cpp
Labels: maintenance

#2250 infra: keep the naming consistent for temp subdirectory with erigon
  cmd/dev/check_tx_lookup.cpp
  cmd/dev/db_toolbox.cpp
  silkworm/db/bitmap_test.cpp
  silkworm/db/etl_collector_test.cpp
  silkworm/infra/common/directories.cpp
  silkworm/infra/common/directories.hpp
  silkworm/infra/common/directories_test.cpp
  silkworm/node/common/node_settings.hpp
  silkworm/node/node.cpp
  silkworm/node/resource_usage.cpp
  silkworm/node/stagedsync/stages/stage_history_index_test.cpp
  silkworm/node/stagedsync/stages/stage_interhashes/_test.cpp
  silkworm/node/stagedsync/stages/stage_tx_lookup_test.cpp
Labels: maintenance

#2255 db: db_toolbox freeze fixes
  cmd/dev/CMakeLists.txt
  cmd/dev/db_toolbox.cpp
  silkworm/db/access_layer.cpp
  silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
  silkworm/db/blocks/headers/header_snapshot_freezer.cpp
  silkworm/db/data_migration.cpp
  silkworm/db/data_migration.hpp
  silkworm/db/data_migration_command.hpp
  silkworm/db/freezer.cpp
  silkworm/db/freezer.hpp
  silkworm/db/snapshot_freezer.hpp
  silkworm/db/stage_scheduler.hpp
  silkworm/db/transactions/txn_snapshot_freezer.cpp
  silkworm/node/stagedsync/stages/stage_triggers.cpp
  silkworm/node/stagedsync/stages/stage_triggers.hpp
Labels: snapshots, maintenance

#2256 rpcdaemon: fix on determine staticcall type
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2257 rpcdaemon: fix STATICCALL type on ots_traceTransaction and recipient for CALLCODE
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2261 clang-tidy: fix some readability warnings
  .clang-tidy
  cmd/dev/db_toolbox.cpp
  silkworm/core/protocol/intrinsic_gas.hpp
  silkworm/db/snapshots/seg/compressor/lcp_kasai.cpp
  silkworm/infra/common/log.hpp
  silkworm/infra/concurrency/idle_strategy.hpp
  silkworm/node/common/node_settings.hpp
  silkworm/rpc/common/util.cpp
  silkworm/rpc/core/evm_access_list_tracer.hpp
  silkworm/sync/internals/chain_elements.hpp
Labels: maintenance

#2262 rpcdaemon: add STOP opcode as last opcode in specific success cases
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2264 rpcdaemon: fix on format to have one error for each block not found
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2267 infra: fix ClientContextPool destruction after mixed dispatching
  silkworm/infra/concurrency/context_pool_test.cpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/infra/grpc/client/client_context_pool_test.cpp
Labels: maintenance

#2266 base: BlockNumRange struct
  silkworm/core/common/base.hpp
  silkworm/db/blocks/bodies/body_snapshot_freezer.cpp
  silkworm/db/blocks/headers/header_snapshot_freezer.cpp
  silkworm/db/freezer.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_freezer.hpp
  silkworm/db/snapshot_merger.cpp
  silkworm/db/snapshots/snapshot_bundle.hpp
  silkworm/db/transactions/txn_snapshot_freezer.cpp
  silkworm/node/execution/grpc/client/endpoint/range.cpp
Labels: maintenance

#2269 db: fix clang tidy after PR 2266
  silkworm/db/snapshot_merger.cpp
Labels: maintenance

#2273 db: fix unit tests after PR 2263 merge
  silkworm/db/snapshots/bittorrent/web_seed_client.cpp
  silkworm/db/snapshots/bittorrent/web_seed_client_test.cpp
  silkworm/db/snapshots/bittorrent/web_session_test.cpp
Labels: maintenance

#2274 rpcdaemon: fix JWT file creation if path not existent
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/http/jwt.cpp
  silkworm/rpc/http/jwt_test.cpp
Labels: maintenance

#2272 tidy: disable new checks
  .clang-tidy
  cmd/dev/embed_toml.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/db/snapshot_freezer.hpp
  silkworm/db/snapshots/basic_queries.hpp
  silkworm/db/snapshots/common/iterator/map_values_view.hpp
  silkworm/db/snapshots/config/bor_mainnet.hpp
  silkworm/db/snapshots/config/mainnet.hpp
  silkworm/db/snapshots/config/mumbai.hpp
  silkworm/db/snapshots/config/sepolia.hpp
  silkworm/db/snapshots/index_builder.hpp
  silkworm/db/snapshots/rec_split/encoding/elias_fano.hpp
  silkworm/db/snapshots/seg/compressor/intermediate_compressed_stream.hpp
  silkworm/db/snapshots/seg/compressor/patricia_tree.hpp
  silkworm/db/snapshots/seg/compressor/pattern_aggregator.hpp
  silkworm/db/snapshots/seg/compressor/raw_words_stream.hpp
  silkworm/db/snapshots/seg/compressor/seg_stream.hpp
  silkworm/db/snapshots/seg/decompressor.cpp
  silkworm/db/snapshots/snapshot_reader.hpp
  silkworm/db/snapshots/snapshot_writer.hpp
  silkworm/db/transactions/txn_index.hpp
  silkworm/db/transactions/txn_queries.hpp
  silkworm/db/transactions/txn_to_block_index.hpp
  silkworm/infra/common/asio_timer.hpp
  silkworm/infra/concurrency/context_pool.cpp
  silkworm/infra/concurrency/context_pool.hpp
  silkworm/infra/concurrency/parallel_group_utils.cpp
  silkworm/infra/concurrency/task.hpp
  silkworm/infra/grpc/client/client_context_pool.cpp
  silkworm/infra/grpc/client/client_context_pool.hpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/infra/grpc/server/server_context_pool.hpp
  silkworm/node/common/node_settings.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/web3_api.cpp
  silkworm/rpc/types/filter.cpp
  silkworm/sentry/discovery/disc_v4/find/lookup.cpp
  silkworm/sentry/multi_sentry_client.cpp
Labels: maintenance

#2268 Add snapshot setting to keep exported blocks in mdbx
  cmd/common/snapshot_options.cpp
  cmd/dev/db_toolbox.cpp
  cmd/silkworm.cpp
  silkworm/db/freezer.cpp
  silkworm/db/freezer.hpp
  silkworm/db/snapshots/settings.hpp
  silkworm/node/node.cpp
Labels: snapshots

#2270 db: snapshot merger cleanup
  silkworm/capi/silkworm.cpp
  silkworm/db/snapshot_bundle_factory_impl.cpp
  silkworm/db/snapshot_merger.cpp
  silkworm/db/snapshot_merger.hpp
  silkworm/db/snapshot_sync_test.cpp
  silkworm/db/snapshots/snapshot_bundle.cpp
  silkworm/db/snapshots/snapshot_bundle.hpp
Labels: snapshots

#2253 db: support for E3 data format in remote state reader
  cmd/dev/grpc_toolbox.cpp
  cmd/test/ethereum.cpp
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/state/in_memory_state.hpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/core/state/state.hpp
  silkworm/db/buffer.cpp
  silkworm/db/buffer.hpp
  silkworm/db/genesis.cpp
  silkworm/db/state/local_state.cpp
  silkworm/db/state/local_state.hpp
  silkworm/db/state/remote_state.cpp
  silkworm/db/state/remote_state.hpp
  silkworm/db/state/remote_state_test.cpp
  silkworm/db/state/state_reader.cpp
  silkworm/db/state/state_reader.hpp
  silkworm/db/state/state_reader_test.cpp
  silkworm/db/state/version.cpp
  silkworm/db/state/version.hpp
  silkworm/db/tables.hpp
  silkworm/db/util.cpp
  silkworm/db/util.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/override_state.cpp
  silkworm/rpc/core/override_state.hpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/daemon.hpp
Labels: erigon3

#2280 wasm: fix interface after PR 2253
  silkworm/rpc/daemon.cpp
  silkworm/wasm/silkworm_wasm_api.cpp
  silkworm/wasm/silkworm_wasm_api.hpp
Labels: maintenance

#2278 rpcdaemon: fix trace state diff with CREATE and SELFDESTRUCT
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/state/intra_block_state.cpp
  silkworm/core/state/intra_block_state.hpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance
