Repository erigontech/silkworm, pull requests merged in 2024-01, with the labels that each got.

#1722 rpcdaemon: enable weekly fuzzer job
  .circleci/config.yml
  cmd/test/CMakeLists.txt
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_investigation.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/rpc/test/api_test_database.cpp
  tests/docker/run-docker.sh
  third_party/CMakeLists.txt
  third_party/llvm/CMakeLists.txt
  third_party/llvm/README.md
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer.a
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer_interceptors.a
  third_party/llvm/lib_libc++/clang/15.0.7/lib/x86_64-linux/libclang_rt.fuzzer_no_main.a
Labels: enhancement

#1723 rpcdaemon: block number as string in debug_traceBlockByNumber
  silkworm/rpc/commands/debug_api.cpp
Labels: enhancement

#1725 rpcdaemon: use opcode number instead of name in eth_createAccessList
  silkworm/rpc/core/evm_access_list_tracer.cpp
  silkworm/rpc/core/evm_access_list_tracer.hpp
Labels: maintenance

#1726 rpcdaemon: eth_getTransactionByHash using glaze
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api.hpp
  silkworm/rpc/commands/rpc_api_table.cpp
  silkworm/rpc/json/transaction.cpp
  silkworm/rpc/json/transaction.hpp
Labels: enhancement

#1727 rpc: fix clang-tidy warnings
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/core/evm_access_list_tracer.hpp
  silkworm/rpc/json/stream.cpp
Labels: maintenance

#1735 rpcdaemon: fix missing logging initialization
  silkworm/infra/common/log.cpp
  silkworm/infra/common/log.hpp
  silkworm/rpc/daemon.cpp
Labels: maintenance

#1736 rpcdaemon: skip tests in sanitizer build to avoid ASAN error after glaze 1.9.9
  silkworm/rpc/json/glaze.cpp
  silkworm/rpc/json/glaze.hpp
  silkworm/rpc/json/glaze_test.cpp
Labels: maintenance

#1730 rpcdaemon: erigon_getBlockByTimestamp using glaze
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/rpc/commands/rpc_api_table.cpp
Labels: maintenance

#1732 sentry: treat clang-tidy warnings as errors
  silkworm/sentry/CMakeLists.txt
  silkworm/sentry/common/random.hpp
  silkworm/sentry/discovery/common/node_address.cpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/discovery/disc_v4/enr/enr_response_message_test.cpp
  silkworm/sentry/discovery/disc_v4/enr/fetch_enr_record.cpp
  silkworm/sentry/discovery/disc_v4/find/find_neighbors.cpp
  silkworm/sentry/discovery/disc_v4/find/find_node_message.cpp
  silkworm/sentry/discovery/disc_v4/find/lookup.cpp
  silkworm/sentry/discovery/disc_v4/find/neighbors_message.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.cpp
  silkworm/sentry/discovery/disc_v4/ping/ping_message.cpp
  silkworm/sentry/discovery/disc_v4/ping/pong_message.cpp
  silkworm/sentry/discovery/disc_v4/server.cpp
  silkworm/sentry/discovery/discovery.cpp
  silkworm/sentry/discovery/enr/enr_codec.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite.cpp
  silkworm/sentry/discovery/node_db/serial_node_db.cpp
  silkworm/sentry/eth/status_data.hpp
  silkworm/sentry/eth/status_message.hpp
  silkworm/sentry/grpc/interfaces/eth_version.cpp
  silkworm/sentry/grpc/interfaces/message.hpp
  silkworm/sentry/grpc/interfaces/peer_info.hpp
  silkworm/sentry/message_sender.cpp
  silkworm/sentry/multi_sentry_client.cpp
  silkworm/sentry/peer_manager_api.cpp
  silkworm/sentry/rlpx/auth/handshake.hpp
  silkworm/sentry/rlpx/common/disconnect_message.cpp
  silkworm/sentry/rlpx/crypto/aes.cpp
  silkworm/sentry/rlpx/crypto/sha3_hasher.cpp
  silkworm/sentry/rlpx/framing/framing_cipher.cpp
  silkworm/sentry/rlpx/framing/message_frame_codec.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/sentry_client_factory.cpp
  silkworm/sentry/sentry_client_factory.hpp
  silkworm/sentry/session_sentry_client.cpp
Labels: maintenance

#1734 rpcdaemon: fix balance and nonce dumps in debug_accountAt
  silkworm/rpc/commands/debug_api.cpp
Labels: maintenance

#1737 rpcdaemon: fix malformed tx handling in eth_call
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance, fuzzy-test

#1738 rpcdaemon: find min block after binary search in erigon_getBlockByTimestamp
  silkworm/rpc/commands/erigon_api.cpp
Labels: maintenance

#1740 sync: treat clang-tidy warnings as errors
  silkworm/rpc/commands/erigon_api_test.cpp
  silkworm/sync/CMakeLists.txt
  silkworm/sync/block_exchange.cpp
  silkworm/sync/internals/body_sequence.cpp
  silkworm/sync/internals/body_sequence.hpp
  silkworm/sync/internals/chain_fork_view.hpp
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/internals/header_chain.hpp
  silkworm/sync/internals/statistics.cpp
  silkworm/sync/messages/outbound_new_block.cpp
  silkworm/sync/messages/outbound_new_block_hashes.cpp
  silkworm/sync/sentry_client.cpp
Labels: maintenance

#1743 cmake: update copyright check for 2024
  cmake/copyright.cmake
Labels: maintenance

#1744 rpcdaemon: separate HTTP connection from JSONRPC request handler
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/http/channel_writer.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/types/writer.cpp
  silkworm/rpc/types/writer.hpp
Labels: maintenance

#1747 rpcdaemon: fix clang-tidy after PR 1739
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator.hpp
Labels: maintenance

#1748 rpcdaemon: fix clang-tidy after PR 1744
  silkworm/rpc/http/channel_writer.hpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#1750 rpcdaemon: some more refactoring in JsonRpcValidator
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator.hpp
  silkworm/rpc/http/json_rpc_validator_test.cpp
  silkworm/rpc/test/api_test_database.hpp
Labels: maintenance

#1742 rpcdaemon: fix ASAN error in eth_feeHistory
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
  silkworm/rpc/test/api_test_database.hpp
Labels: maintenance, fuzzy-test

#1745 all: treat clang-tidy warnings as errors
  .clang-tidy
  CMakeLists.txt
  cmd/common/db_checklist.cpp
  cmd/silkworm.cpp
  silkworm/capi/sentry.cpp
  silkworm/capi/silkworm.cpp
  silkworm/core/CMakeLists.txt
  silkworm/infra/CMakeLists.txt
  silkworm/node/CMakeLists.txt
  silkworm/rpc/CMakeLists.txt
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/common/util_test.cpp
  silkworm/rpc/core/account_walker_test.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/gas_price_oracle_test.cpp
  silkworm/rpc/core/rawdb/chain_test.cpp
  silkworm/rpc/core/state_reader_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/txpool/miner_test.cpp
  silkworm/rpc/txpool/transaction_pool_test.cpp
  silkworm/sentry/CMakeLists.txt
  silkworm/sync/CMakeLists.txt
Labels: maintenance

#1751 rpcdaemon: fix gas and rewards in eth_feeHistory
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
  silkworm/rpc/core/fee_history_oracle_test.cpp
Labels: maintenance

#1753 rpcdaemon: fix clang-tidy in FeeHistoryOracle
  silkworm/rpc/core/fee_history_oracle.cpp
Labels: maintenance

#1754 rpcdaemon: simplify unit tests for eth namespace
  silkworm/rpc/commands/eth_api_test.cpp
Labels: maintenance

#1752 rpcdaemon: refactor stream data types
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/http/channel.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/json/stream_test.cpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/types/writer.cpp
  silkworm/rpc/types/writer.hpp
  silkworm/rpc/types/writer_test.cpp
Labels: maintenance

#1755 rpcdaemon: JsonRpcValidator perf improvements
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator_test.cpp
Labels: enhancement

#1756 CI: fix fuzzer build and add it to integration workflow
  .circleci/config.yml
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_investigation.cpp
  cmd/test/fuzzer_test.cpp
Labels: maintenance

#1746 core: amend incarnation logic
  silkworm/core/execution/evm_test.cpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/core/types/account.hpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/buffer_test.cpp
Labels: maintenance

#1758 rpcdaemon: comment validator for perf reason
  silkworm/rpc/http/request_handler.hpp
Labels: maintenance

#1761 rpcdaemon: load JSON RPC validation spec once at startup
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator.hpp
  silkworm/rpc/http/json_rpc_validator_test.cpp
  silkworm/rpc/http/request_handler.hpp
Labels: maintenance

#1759 Address cert-oop54-cpp & concurrency-mt-unsafe warnings
  .clang-tidy
  silkworm/core/common/small_map.hpp
  silkworm/core/concurrency/resettable_once_flag.hpp
  silkworm/infra/common/directories.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/infra/common/safe_strerror.cpp
  silkworm/infra/common/safe_strerror.hpp
  silkworm/infra/concurrency/parallel_group_test.cpp
  silkworm/node/bittorrent/client.cpp
  silkworm/node/etl/file_provider.cpp
  silkworm/node/etl/util.hpp
  silkworm/sentry/discovery/disc_v4/ping/ping_check.cpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1766 sentry/discovery: fix lookup seg fault on release builds
  silkworm/sentry/discovery/disc_v4/find/lookup.cpp
Labels: maintenance

#1765 Address cppcoreguidelines-explicit-virtual-functions & no-malloc warnings
  .clang-tidy
  silkworm/node/db/mdbx.hpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/rpc/ethdb/bitmap.cpp
Labels: maintenance

#1762 rpcdaemon: use boost::beast for HTTP
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/common/constants.hpp
  silkworm/rpc/http/channel.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/reply.cpp
  silkworm/rpc/http/reply.hpp
  silkworm/rpc/http/reply_test.cpp
  silkworm/rpc/http/request.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
  silkworm/rpc/http/request_handler_test.cpp
  silkworm/rpc/http/request_parser.cpp
  silkworm/rpc/http/request_parser.hpp
  silkworm/rpc/http/request_parser_test.cpp
  silkworm/rpc/http/request_test.cpp
  silkworm/rpc/test/api_test_database.hpp
Labels: enhancement

#1769 rpcdaemon: fix clang-tidy and fuzzer build after PR 1762
  cmd/test/fuzzer_test.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/test/api_test_database.hpp
Labels: maintenance

#1764 rpcdaemon: fix wrong chunk sequence in streaming
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
Labels: maintenance

#1768 rpcdaemon: fix effective_gas_price for block > London in ots_getBlockDetails
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/json/types.cpp
Labels: maintenance

#1621 capi: block execution commits after state batch has been flushed
  silkworm/capi/silkworm.cpp
  silkworm/core/common/util.cpp
  silkworm/core/common/util.hpp
  silkworm/core/state/in_memory_state.cpp
  silkworm/core/state/intra_block_state.cpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/buffer.hpp
  silkworm/node/db/buffer_test.cpp
  silkworm/node/db/mdbx.cpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
Labels: maintenance, c-api

#1774 node: fix mdbx test in sanitizer build after PR 1621
  silkworm/node/db/mdbx_test.cpp
Labels: maintenance

#1775 node: fix clang-tidy after PR 1763
  silkworm/node/db/access_layer_test.cpp
  silkworm/node/db/memory_mutation_cursor.hpp
  silkworm/node/db/prune_mode.cpp
  silkworm/node/db/prune_mode.hpp
  silkworm/node/db/receipt_cbor_test.cpp
  silkworm/node/db/stages.hpp
  silkworm/node/db/tables.hpp
Labels: maintenance

#1772 node: fix mdbx::env lifecycle in db::ROAccess and db::RWAccess
  silkworm/node/db/mdbx.hpp
  silkworm/node/db/mdbx_test.cpp
Labels: maintenance

#1776 node: fix clang-tidy after PR 1772
  cmd/dev/backend_kv_server.cpp
  cmd/dev/check_changes.cpp
  cmd/dev/check_pow.cpp
  cmd/dev/check_tx_lookup.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/genesistool.cpp
  cmd/dev/kzg_g2_uncompress.cpp
  cmd/dev/scan_txs.cpp
  cmd/dev/snapshots.cpp
  silkworm/node/db/db_utils_test.cpp
  silkworm/node/db/eth_status_data_provider.hpp
  silkworm/node/db/mdbx.hpp
  silkworm/node/stagedsync/execution_engine.cpp
  silkworm/node/stagedsync/forks/main_chain.cpp
  silkworm/node/stagedsync/server.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/ethdb/cursor.cpp
  silkworm/rpc/json/call_bundle_test.cpp
  silkworm/rpc/test/api_test_database.cpp
  silkworm/sync/block_exchange.cpp
  silkworm/sync/block_exchange.hpp
Labels: maintenance

#1770 infra: migrate `ensure` to the dynamic format for performance reasons
  cmd/capi/execute.cpp
  cmd/dev/check_log_indices.cpp
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  silkworm/infra/common/ensure.hpp
  silkworm/infra/common/ensure_test.cpp
  silkworm/infra/common/memory_mapped_file.cpp
  silkworm/node/db/access_layer.cpp
  silkworm/node/db/bitmap.cpp
  silkworm/node/db/log_cbor.cpp
  silkworm/node/snapshots/index.cpp
  silkworm/node/snapshots/rec_split/rec_split.hpp
  silkworm/node/snapshots/repository.cpp
  silkworm/node/snapshots/snapshot.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
  silkworm/node/stagedsync/forks/canonical_chain.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/node/stagedsync/stages/stage_senders.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
Labels: performance

#1771 rpcdaemon: add websocket impl (no streaming)
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: enhancement

#1777 rpcdaemon: fix async loop in JSON streaming
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/json/stream_test.cpp
Labels: maintenance

#1781 rpcdaemon: workaround for Windows build error after PR 1777
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
Labels: maintenance

#1779 rpcdaemon: add Date header in HTTP response
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#1780 rpcdaemon: add --websocket option to enable websocket
  cmd/common/rpcdaemon_options.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
  silkworm/rpc/settings.hpp
Labels: enhancement

#1785 rpcdaemon: trace_filter use stream reference
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#1788 sentry: improve error message when RLPx port is occupied (#1398)
  silkworm/sentry/rlpx/server.cpp
Labels: maintenance
