Repository erigontech/silkworm, pull requests merged in 2024-02, with the labels that each got.

#1791 ci: fix conan profile in fuzzer build after PR 1679
  .circleci/config.yml
Labels: maintenance

#1783 snapshots seg compressor: pattern extractor and patricia tree
  silkworm/node/CMakeLists.txt
  silkworm/node/common/bit_count.hpp
  silkworm/node/snapshots/index.cpp
  silkworm/node/snapshots/index.hpp
  silkworm/node/snapshots/rec_split/common/common.hpp
  silkworm/node/snapshots/seg/compressor/lcp_kasai.cpp
  silkworm/node/snapshots/seg/compressor/lcp_kasai.hpp
  silkworm/node/snapshots/seg/compressor/patricia_tree.cpp
  silkworm/node/snapshots/seg/compressor/patricia_tree.hpp
  silkworm/node/snapshots/seg/compressor/patricia_tree_test.cpp
  silkworm/node/snapshots/seg/compressor/pattern_extractor.cpp
  silkworm/node/snapshots/seg/compressor/pattern_extractor.hpp
  silkworm/node/snapshots/seg/compressor/pattern_extractor_test.cpp
  silkworm/node/snapshots/seg/decompressor.cpp
  silkworm/node/snapshots/seg/decompressor.hpp
  silkworm/node/snapshots/seg/decompressor_test.cpp
  silkworm/node/snapshots/snapshot.cpp
  silkworm/node/snapshots/snapshot.hpp
  silkworm/node/snapshots/snapshot_benchmark.cpp
  silkworm/node/snapshots/snapshot_test.cpp
  third_party/CMakeLists.txt
  third_party/sais-lite/CMakeLists.txt
  third_party/sais-lite/sais-lite/README.md
  third_party/sais-lite/sais-lite/sais.c
  third_party/sais-lite/sais-lite/sais.h
Labels: snapshots

#1792 cmd: fix CLI11 parse regression in snapshots utility
  .gitignore
  cmd/dev/snapshots.cpp
Labels: maintenance

#1793 node: fix corner case errors in snapshot decompressor
  silkworm/node/snapshots/seg/decompressor.cpp
  silkworm/node/snapshots/seg/decompressor_test.cpp
Labels: maintenance

#1795 snapshots seg: clz UBSAN fix
  silkworm/node/snapshots/seg/compressor/patricia_tree.cpp
Labels: maintenance

#1794 snapshots seg compressor: pattern covering search
  silkworm/node/snapshots/seg/compressor/pattern_covering.cpp
  silkworm/node/snapshots/seg/compressor/pattern_covering.hpp
  silkworm/node/snapshots/seg/compressor/pattern_covering_test.cpp
Labels: snapshots

#1790 rpcdaemon: json streamed request exception handling
  silkworm/rpc/http/request_handler.cpp
Labels: maintenance

#1798 rpcdaemon: add ws compression
  cmd/common/rpcdaemon_options.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
  silkworm/rpc/settings.hpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: enhancement

#1799 rpcdaemon: add ws ping in case of inactivity
  silkworm/rpc/ws/connection.cpp
Labels: enhancement

#1800 docs: how to develop and test C API in contribution guide
  docs/CONTRIBUTING.md
Labels: documentation

#1804 rpcdaemon: fix json rpc validation and enable for integration tests
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator_test.cpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/json/call.cpp
  silkworm/rpc/json/call_test.cpp
Labels: maintenance

#1797 node: fix error handling in snapshot index build
  silkworm/capi/silkworm.cpp
  silkworm/infra/test_util/temporary_file.hpp
  silkworm/node/snapshots/index.cpp
  silkworm/node/snapshots/index_test.cpp
  silkworm/node/snapshots/repository.cpp
  silkworm/node/snapshots/seg/decompressor.cpp
  silkworm/node/snapshots/sync.cpp
Labels: maintenance

#1805 rpcdaemon: add optional interface log in JSON RPC end-points
  cmd/common/rpcdaemon_options.cpp
  silkworm/rpc/common/interface_log.cpp
  silkworm/rpc/common/interface_log.hpp
  silkworm/rpc/common/interface_log_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
  silkworm/rpc/settings.hpp
Labels: enhancement

#1808 rpcdaemon: fix clang-tidy and Windows build after PR 1805
  silkworm/rpc/common/interface_log.hpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
Labels: maintenance

#1803 snapshots seg compressor: huffman code
  .clang-tidy
  silkworm/node/snapshots/index.cpp
  silkworm/node/snapshots/seg/common/varint.cpp
  silkworm/node/snapshots/seg/common/varint.hpp
  silkworm/node/snapshots/seg/common/varint_test.cpp
  silkworm/node/snapshots/seg/compressor/bit_stream.cpp
  silkworm/node/snapshots/seg/compressor/bit_stream.hpp
  silkworm/node/snapshots/seg/compressor/bit_stream_test.cpp
  silkworm/node/snapshots/seg/compressor/huffman_code.cpp
  silkworm/node/snapshots/seg/compressor/huffman_code.hpp
  silkworm/node/snapshots/seg/compressor/huffman_code_test.cpp
  silkworm/node/snapshots/seg/compressor/patricia_tree.cpp
  silkworm/node/snapshots/seg/compressor/pattern_covering.cpp
  silkworm/node/snapshots/seg/decompressor.cpp
  silkworm/node/snapshots/seg/decompressor_test.cpp
  silkworm/node/snapshots/test_util/common.hpp
Labels: snapshots

#1813 node: fix Clang Tidy after PR 1803
  silkworm/node/snapshots/seg/compressor/bit_stream.hpp
Labels: maintenance

#1812 rpcdaemon: expected result in JSON RPC validator
  silkworm/rpc/http/json_rpc_validator.cpp
  silkworm/rpc/http/json_rpc_validator.hpp
  silkworm/rpc/http/json_rpc_validator_test.cpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/http/request_handler.hpp
Labels: maintenance

#1787 capi: buffer blocks in a separate thread
  silkworm/capi/silkworm.cpp
  silkworm/infra/common/bounded_buffer.hpp
  silkworm/infra/common/bounded_buffer_test.cpp
  silkworm/node/db/buffer.cpp
  silkworm/node/db/mdbx.hpp
Labels: performance, c-api

#1811 rpcdaemon: move HTTP chunk handling in http::Connection
  silkworm/rpc/http/channel.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/request_handler.cpp
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/json/stream_test.cpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/types/writer.cpp
  silkworm/rpc/types/writer.hpp
  silkworm/rpc/types/writer_test.cpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: maintenance

#1819 rpcdaemon: fix Clang Tidy warnings after PR 1811
  silkworm/rpc/types/writer_test.cpp
Labels: maintenance

#1807 snapshots seg: library target
  cmake/common/targets.cmake
  cmd/test/CMakeLists.txt
  silkworm/core/common/bit_count.hpp
  silkworm/node/CMakeLists.txt
  silkworm/node/snapshots/rec_split/common/common.hpp
  silkworm/node/snapshots/seg/CMakeLists.txt
  silkworm/node/snapshots/seg/compressor/patricia_tree.cpp
  silkworm/node/snapshots/seg/compressor/patricia_tree_test.cpp
  silkworm/node/snapshots/seg/compressor/pattern_extractor.hpp
  silkworm/node/snapshots/seg/decompressor.hpp
  silkworm/node/snapshots/snapshot_decompressor_test.cpp
  tests/unit/README.md
  tests/unit/run_unit_test_loop.py
Labels: maintenance

#1818 capi, infra: add TTY detection to customize log format
  silkworm/capi/silkworm.cpp
  silkworm/infra/common/log.cpp
  silkworm/infra/common/log_test.cpp
  silkworm/infra/common/terminal.cpp
  silkworm/infra/common/terminal.hpp
Labels: maintenance, c-api

#1824 node: fix Clang Tidy after PR 1820
  silkworm/node/snapshots/seg/compressor/patricia_tree.cpp
Labels: maintenance

#1826 ci: add rpc-tests version in integration workflow
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance, integration testing

#1810 tests: workflow for perf tests
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing

#1815 rpcdaemon: Erigon compatibility in eth_callMany API
  silkworm/rpc/core/call_many.cpp
Labels: maintenance

#1823 rpcdaemon: use of OverrideState in CallExecutor::executes_all_bundles
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance

#1825 rpcdaemon: fix fuzzer diagnostics
  .circleci/config.yml
  cmd/test/CMakeLists.txt
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_investigation.cpp
  docs/fuzzer.md
Labels: fuzzy testing

#1829 ci: update rpc-tests to 0.2.0 in integration tests
  .github/workflows/rpc-integration-tests.yml
Labels: integration testing

#1822 rpcdaemon: align feeRecipient to suggestedFeeRecipient according validator
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/json/payload_attributes.cpp
  silkworm/rpc/json/payload_attributes_test.cpp
Labels: maintenance

#1821 rpcdaemon: full streaming support in websockets
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/types/writer.hpp
  silkworm/rpc/types/writer_test.cpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: maintenance

#1831 rpcdaemon: fix Clang Tidy after PR 1821
  silkworm/rpc/json/stream.cpp
Labels: maintenance

#1834 ci: fix fuzzer diagnostics build after PR 1830
  cmd/test/fuzzer_diagnostics.cpp
Labels: maintenance

#1835 doc: add badges for RPC tests in README
  README.md
Labels: documentation

#1833 core: rename polygon to bor-mainnet
  cmake/copyright.cmake
  cmake/format.cmake
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/genesis.cpp
  silkworm/core/chain/genesis_bor_mainnet.cpp
  silkworm/core/chain/genesis_bor_mainnet.hpp
  silkworm/core/chain/genesis_bor_mainnet.json
  silkworm/core/chain/genesis_test.cpp
  silkworm/core/common/small_map.hpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/bor/config.cpp
  silkworm/core/protocol/bor/config.hpp
  silkworm/core/protocol/bor/config_test.cpp
  silkworm/core/protocol/bor/span.cpp
  silkworm/core/protocol/bor/span.hpp
  silkworm/core/protocol/bor/span_test.cpp
  silkworm/core/protocol/bor_rule_set.cpp
  silkworm/core/protocol/bor_rule_set.hpp
  silkworm/core/protocol/rule_set.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/node/db/genesis_test.cpp
  silkworm/node/snapshots/config.hpp
Labels: maintenance, polygon

#1839 ci: fix fuzzer build targets for macOS arm64
  cmd/test/CMakeLists.txt
Labels: fuzzy testing

#1841 capi: some basic unit tests
  cmake/common/targets.cmake
  silkworm/capi/CMakeLists.txt
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/infra/concurrency/signal_handler_test.cpp
Labels: maintenance, c api

#1844 capi: fix Windows build after PR 1841
  silkworm/capi/sentry.cpp
  silkworm/capi/silkworm_test.cpp
Labels: maintenance

#1842 rpcdaemon: remove nlohmann::json::array from to_json in eth_feeHistory
  silkworm/rpc/core/fee_history_oracle.cpp
Labels: maintenance, fuzzer trophy

#1843 rpcdaemon: change result to optional string in RequestHandler::handle
  silkworm/rpc/common/channel.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/json_rpc/request_handler.cpp
  silkworm/rpc/json_rpc/request_handler.hpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: maintenance

#1848 rpcdaemon: detect nil character in JSON request
  silkworm/rpc/json_rpc/request_handler.cpp
  silkworm/rpc/json_rpc/request_handler.hpp
  silkworm/rpc/json_rpc/request_handler_test.cpp
Labels: maintenance

#1849 rpcdaemon: fix Clang Tidy after PR 1848
  silkworm/rpc/json_rpc/request_handler.cpp
Labels: maintenance

#1837 snapshots seg compressor: testing fixes
  cmd/dev/snapshots.cpp
  silkworm/node/snapshots/seg/compressor.cpp
  silkworm/node/snapshots/seg/compressor/bit_stream.hpp
  silkworm/node/snapshots/seg/compressor/bit_stream_test.cpp
  silkworm/node/snapshots/seg/compressor/huffman_code.cpp
  silkworm/node/snapshots/seg/compressor/huffman_code.hpp
  silkworm/node/snapshots/seg/compressor/intermediate_compressed_stream.cpp
  silkworm/node/snapshots/seg/compressor/lcp_kasai.hpp
  silkworm/node/snapshots/seg/compressor/output_file_transaction.cpp
  silkworm/node/snapshots/seg/compressor/pattern_covering.cpp
  silkworm/node/snapshots/seg/compressor/pattern_covering.hpp
  silkworm/node/snapshots/seg/compressor/pattern_extractor.cpp
  silkworm/node/snapshots/seg/compressor/raw_words_stream.cpp
  silkworm/node/snapshots/seg/compressor/raw_words_stream.hpp
  silkworm/node/snapshots/seg/compressor/seg_stream.cpp
  silkworm/node/snapshots/seg/seg_zip.cpp
  silkworm/node/snapshots/seg/seg_zip.hpp
Labels: maintenance

#1847 cmake: fix silkworm_library function for shared libraries
  cmake/common/targets.cmake
Labels: maintenance

#1851 node: fix Clang Tidy after PR 1873
  silkworm/node/snapshots/seg/compressor/pattern_covering.cpp
  silkworm/node/snapshots/seg/compressor/pattern_covering.hpp
Labels: maintenance

#1846 tests: add integration tests on websocket in integration workflow
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance, integration testing

#1852 rpcdaemon: fix compression option on websockets
  silkworm/rpc/ws/connection.cpp
Labels: maintenance

#1853 rpcdaemon: move HTTP body termination char to connection
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/json_rpc/request_handler.cpp
Labels: maintenance

#1856 core: comment on pre-Byzantium receipts
  silkworm/core/execution/processor.cpp
Labels: maintenance

#1857 snapshots: fix seg_unzip
  silkworm/node/snapshots/seg/decompressor.cpp
  silkworm/node/snapshots/seg/seg_zip.cpp
Labels: snapshots, maintenance

#1860 sentry: invalid MAC error handling
  silkworm/sentry/common/error.hpp
  silkworm/sentry/rlpx/auth/auth_ack_message.cpp
  silkworm/sentry/rlpx/auth/auth_message.cpp
  silkworm/sentry/rlpx/auth/auth_message_error.hpp
  silkworm/sentry/rlpx/auth/ecies_cipher.cpp
  silkworm/sentry/rlpx/auth/ecies_cipher_error.hpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1861 node: fix snapshot sync progress update with STOP_AT_BLOCK
  silkworm/node/snapshots/sync.cpp
  silkworm/node/stagedsync/execution_pipeline.cpp
Labels: maintenance

#1865 sentry: invalid MAC error - log as TRACE
  silkworm/sentry/rlpx/auth/ecies_cipher_test.cpp
  silkworm/sentry/rlpx/peer.cpp
Labels: maintenance

#1862 seg: avoid stackoverflow in PatternTable::build_condensed
  silkworm/node/snapshots/seg/decompressor.cpp
Labels: snapshots, maintenance

#1850 rpcdaemon: error messages for eth_callMany API
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance
