Repository erigontech/silkworm, pull requests merged in 2024-04, with the labels that each got.

#1951 perf-workflow: generate and save json result file
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#1954 integration-workflow: use rpc-tests v0.8.2
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance, integration testing

#1953 rpcdaemon: extract awaitable async task run by executor
  .github/workflows/rpc-performance-tests.yml
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/common/async_task.hpp
  silkworm/rpc/common/async_task_benchmark.cpp
  silkworm/rpc/common/async_task_test.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/http/connection.cpp
Labels: maintenance

#1956 capi: fix sample Golang client
  cmd/capi/sample-go-client/main.go
Labels: maintenance

#1959 rpcdaemon: add config flag to toggle response dump in interface log
  cmd/common/rpcdaemon_options.cpp
  silkworm/rpc/common/interface_log.cpp
  silkworm/rpc/common/interface_log.hpp
  silkworm/rpc/common/interface_log_test.cpp
Labels: maintenance

#1962 rpcdaemon: extract JSON-RPC handler out of transport
  silkworm/rpc/commands/admin_api.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/debug_api.hpp
  silkworm/rpc/commands/engine_api.hpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/eth_api.hpp
  silkworm/rpc/commands/net_api.hpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/commands/parity_api.hpp
  silkworm/rpc/commands/rpc_api.hpp
  silkworm/rpc/commands/rpc_api_table.hpp
  silkworm/rpc/commands/trace_api.hpp
  silkworm/rpc/commands/txpool_api.hpp
  silkworm/rpc/commands/web3_api.hpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/server.cpp
  silkworm/rpc/http/server.hpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/json_rpc/request_handler.cpp
  silkworm/rpc/json_rpc/request_handler.hpp
  silkworm/rpc/test/api_test_database.hpp
  silkworm/rpc/transport/request_handler.hpp
  silkworm/rpc/transport/stream_writer.hpp
  silkworm/rpc/transport/stream_writer_test.cpp
  silkworm/rpc/ws/connection.cpp
  silkworm/rpc/ws/connection.hpp
Labels: maintenance

#1963 rpcdaemon: fix Clang Tidy after PR 1962
  silkworm/rpc/json_rpc/request_handler.hpp
Labels: maintenance

#1949 core, rpcdaemon: add check on NoPreMergeConfig and terminal total difficulty
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/chain/config_test.cpp
  silkworm/core/protocol/merge_rule_set.cpp
  silkworm/core/protocol/rule_set.cpp
  silkworm/core/protocol/rule_set_test.cpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/daemon.cpp
Labels: maintenance

#1966 rpcdaemon: fix Clang in sanitizer build after PR 1949
  silkworm/rpc/commands/engine_api_test.cpp
Labels: maintenance

#1960 rcpdaemon: error messages in TraceTracer
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#1961 rpcdaemon: author value in trace_block reward action
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#1967 rpcdaemon: fix state access in eth_estimateGas
  silkworm/rpc/core/estimate_gas_oracle.cpp
Labels: maintenance

#1965 rpcdaemon: yParity field not conditioned to Erigon compatibility flag
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/json/transaction.cpp
Labels: maintenance

#1971 perf-workflow: remove copy of reference binary data
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance

#1968 capi: export RpcDaemon configuration settings
  cmd/capi/execute.cpp
  silkworm/capi/common.cpp
  silkworm/capi/common.hpp
  silkworm/capi/instance.hpp
  silkworm/capi/rpcdaemon.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
  silkworm/infra/concurrency/context_pool_settings.hpp
  silkworm/rpc/common/worker_pool.hpp
  silkworm/rpc/settings.hpp
Labels: enhancement, c api

#1975 capi: fix Windows build after PR 1968
  silkworm/capi/common.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
Labels: maintenance

#1973 rpcdaemon: improve close of state-changes stream after server-side termination
  silkworm/rpc/ethdb/kv/state_changes_stream.cpp
  silkworm/rpc/ethdb/kv/state_changes_stream_test.cpp
  silkworm/rpc/grpc/server_streaming_rpc.hpp
Labels: maintenance

#1976 rpcdaemon: improve error handling in HTTP server
  silkworm/rpc/http/server.cpp
Labels: maintenance

#1978 capi: fix C99 compilation
  cmd/capi/CMakeLists.txt
  cmd/capi/main.c
  silkworm/capi/silkworm.h
Labels: maintenance, c api

#1980 perf_workflow: add two new qps/time on eth_getTransactionReceipt tests
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#1969 rpcdaemon: fix eth_estimateGas error handling
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance

#1982 rpcdaemon: improve JWT handling in HTTP connection
  silkworm/rpc/common/constants.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/connection_test.cpp
Labels: maintenance

#1984 rpcdaemon: add safe and finalized blocks in BlockNumberOrHash
  silkworm/rpc/types/block.cpp
Labels: maintenance

#1986 rpcdaemon: fix Clang Tidy after PR 1984
  silkworm/rpc/types/block.cpp
Labels: maintenance

#1985 rpcademon: fix block header serialization for erigon_getHeaderByHash
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/json/types_test.cpp
Labels: maintenance

#1988 rpcdaemon: fix warning in StateChanges stream unit test
  silkworm/rpc/ethdb/kv/state_changes_stream_test.cpp
Labels: maintenance

#1983 rpcdaemon: compatibility flag in trace_get API
  silkworm/rpc/commands/trace_api.cpp
Labels: maintenance

#1992 fuzzer: fix build after PR 1989
  cmd/test/CMakeLists.txt
  cmd/test/fuzzer_diagnostics.cpp
  cmd/test/fuzzer_test.cpp
Labels: maintenance
