Repository erigontech/silkworm, pull requests merged in 2024-07, with the labels that each got.

#2156 infra: fix thread dispatching in gRPC calls
  cmd/dev/grpc_toolbox.cpp
  silkworm/db/kv/grpc/client/state_changes_stream.cpp
  silkworm/infra/CMakeLists.txt
  silkworm/infra/grpc/client/bidi_streaming_rpc.hpp
  silkworm/infra/grpc/client/call.hpp
  silkworm/infra/grpc/client/call_test.cpp
  silkworm/infra/grpc/client/reconnect.cpp
  silkworm/infra/grpc/client/reconnect.hpp
  silkworm/infra/grpc/client/server_streaming_rpc.hpp
  silkworm/infra/grpc/client/unary_rpc.hpp
  silkworm/infra/grpc/client/util.hpp
  silkworm/infra/grpc/client/util_test.cpp
  silkworm/sentry/grpc/client/sentry_client.cpp
Labels: maintenance

#2158 infra: fix ASAN build after PR 2156
  silkworm/infra/grpc/client/call.hpp
  silkworm/infra/grpc/client/call_test.cpp
Labels: maintenance

#2159 rpcdaemon, sync: remote exec engine
  silkworm/node/execution/api/direct_service.cpp
  silkworm/rpc/CMakeLists.txt
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/engine/conversion.cpp
  silkworm/rpc/engine/conversion.hpp
  silkworm/rpc/engine/remote_execution_engine.cpp
  silkworm/rpc/engine/remote_execution_engine.hpp
  silkworm/rpc/engine/validation.cpp
  silkworm/rpc/engine/validation.hpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
Labels: enhancement, json rpc api

#2160 integration-workflow: update rpc-tests version to 0.29
  .github/workflows/rpc-integration-tests.yml
Labels: maintenance, integration testing

#2163 rpcdaemon: fix clang tidy after PR 1939
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_trace_test.cpp
Labels: maintenance

#2161 doc: update JSON RPC API partial comment
  docs/JSON-RPC-API.md
Labels: documentation

#2154 qa-tests: save latency percentile distribution analysis data in backup directory
  .github/workflows/rpc-performance-tests.yml
Labels: enhancement, perf testing

#1932 rpcdaemon: support compression on HTTP streaming
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: enhancement

#2164 core: introduce overflow-safe num_words
  silkworm/core/execution/call_tracer.cpp
  silkworm/core/execution/precompile.cpp
  silkworm/core/protocol/intrinsic_gas.cpp
  silkworm/core/protocol/intrinsic_gas.hpp
  silkworm/core/protocol/intrinsic_gas_test.cpp
Labels: maintenance

#2165 db: handle deletion from multivalue in memory mutation
  silkworm/db/mdbx/memory_mutation.cpp
  silkworm/db/mdbx/memory_mutation.hpp
  silkworm/db/mdbx/memory_mutation_cursor.cpp
  silkworm/db/mdbx/memory_mutation_cursor.hpp
  silkworm/db/mdbx/memory_mutation_test.cpp
  silkworm/db/memory_mutation_cursor_test.cpp
Labels: maintenance

#2166 ci: gcc 14 in linux-gcc-thread-sanitizer
  .circleci/config.yml
Labels: maintenance

#2167 rpcdaeomon: static call in gas cost for debug API endpoints
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2171 db: add extra tests for Buffer
  silkworm/db/buffer_test.cpp
Labels: unit testing

#2176 db: fix ASAN error and Windows build after PR 2168
  silkworm/db/kv/api/direct_service_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
Labels: maintenance

#2175 db: KV begin_transaction as txn factory
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/direct_service_test.cpp
  silkworm/db/kv/api/service_router.cpp
  silkworm/db/kv/api/service_router.hpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client.hpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/db/test_util/test_database_context.hpp
  silkworm/infra/grpc/test_util/test_runner.hpp
  silkworm/rpc/daemon.cpp
Labels: maintenance

#2173 rpcdaemon: add get_capacity on StreamWriter
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/json/stream.cpp
  silkworm/rpc/json/stream.hpp
  silkworm/rpc/test_util/api_test_database.hpp
  silkworm/rpc/transport/stream_writer.hpp
  silkworm/rpc/transport/stream_writer_test.cpp
  silkworm/rpc/ws/connection.hpp
Labels: maintenance

#2174 qa-tests: fix upload task in perf tests
  .github/workflows/rpc-performance-tests.yml
Labels: maintenance, perf testing

#2179 infra: move sleep utility function from sentry
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/infra/concurrency/sleep.cpp
  silkworm/infra/concurrency/sleep.hpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/rlpx/client.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sentry/session_sentry_client.cpp
Labels: maintenance

#2178 rpcdaemon: if gas bailout subtract only if there is enough balance
  .github/workflows/rpc-integration-tests.yml
  silkworm/core/execution/evm.cpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance

#2180 move interfaces from ledgerwatch to erigontech
  .gitmodules
  README.md
  docs/CONTRIBUTING.md
  silkworm/core/protocol/blockchain.hpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/trie/hash_builder.cpp
Labels: maintenance

#2181 rpcdaemon: fix cost, used-gas in case of EVMC errors
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: maintenance

#2182 Update links to erigon after its move from ledgerwatch to erigontech
  .gitmodules
  README.md
  docs/CONTRIBUTING.md
  silkworm/core/protocol/blockchain.hpp
  silkworm/core/protocol/validation.hpp
  silkworm/core/trie/hash_builder.cpp
  silkworm/sentry/discovery/bootnodes.cpp
Labels: maintenance

#2183 rpcdaemon: fix clang tidy after PR 2172
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2184 rpcdaemon: renamed fix call gas data structure
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: maintenance

#2188 core: get rid of SILKWORM_CONSTINIT
  silkworm/core/chain/config.cpp
  silkworm/core/chain/config.hpp
  silkworm/core/common/base.hpp
Labels: maintenance

#2186 db: paginated sequence for temporal KV API
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
Labels: enhancement, temporal kv

#2191 clang-tidy: fix cppcoreguidelines-prefer-member-initializer
  .clang-tidy
  cmd/state-transition/state_transition.cpp
  cmd/state-transition/state_transition.hpp
  cmd/test/backend_kv_test.cpp
  silkworm/core/crypto/sha256.c
  silkworm/core/state/intra_block_state.cpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/stages/stage_bodies.cpp
  silkworm/node/stagedsync/stages/stage_headers.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/ethdb/split_cursor.cpp
  silkworm/sync/internals/chain_elements.hpp
  silkworm/sync/messages/inbound_new_block.cpp
  silkworm/sync/messages/inbound_new_block_hashes.cpp
Labels: maintenance

#2193 clang-tidy: address google-explicit-constructor
  .clang-tidy
  cmd/test/ethereum.cpp
  silkworm/core/common/bytes.hpp
  silkworm/core/common/random_number.hpp
  silkworm/core/types/hash.hpp
  silkworm/db/freezer.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
  silkworm/db/log_cbor.cpp
  silkworm/db/snapshots/seg/compressor/bit_stream.hpp
  silkworm/db/snapshots/seg/compressor/bit_stream_test.cpp
  silkworm/db/snapshots/seg/compressor/huffman_code.cpp
  silkworm/db/snapshots/seg/compressor/pattern_aggregator.cpp
  silkworm/infra/common/memory_mapped_file.hpp
  silkworm/infra/concurrency/sync_wait_test.cpp
  silkworm/node/execution/api/endpoint/checkers.hpp
  silkworm/node/execution/api/endpoint/insertion.hpp
  silkworm/node/stagedsync/stages/stage_headers.hpp
  silkworm/sentry/discovery/disc_v4/enr/enr_response_message.hpp
  silkworm/sentry/discovery/disc_v4/find/find_node_message.hpp
  silkworm/sentry/discovery/node_db/node_db.hpp
  silkworm/sentry/rlpx/auth/handshake.hpp
  silkworm/sentry/status_manager.hpp
  silkworm/sync/internals/chain_elements.hpp
  silkworm/sync/internals/chain_fork_view.hpp
  silkworm/sync/internals/header_only_state.hpp
  silkworm/sync/messages/internal_message.hpp
Labels: maintenance

#2194 db: fix clang tidy and sanitizers after PR 2189
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
Labels: maintenance

#2190 rpcdaemon: fix trace gasCost for opcode EXP in case of stack fault
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2195 clang-tidy: fix google-readability-casting
  .clang-tidy
  cmd/dev/db_toolbox.cpp
  cmd/dev/snapshots.cpp
  cmd/test/sentry_client_test.cpp
  silkworm/capi/silkworm.cpp
  silkworm/core/common/util.hpp
  silkworm/db/kv/grpc/server/kv_calls_test.cpp
  silkworm/db/log_cbor.cpp
  silkworm/db/mdbx/mdbx.cpp
  silkworm/db/snapshot_sync.cpp
  silkworm/db/snapshots/bittorrent/client.cpp
  silkworm/db/snapshots/rec_split/encoding/elias_fano.hpp
  silkworm/db/snapshots/rec_split/rec_split.hpp
  silkworm/db/snapshots/seg/compressor/bit_stream.cpp
  silkworm/db/snapshots/seg/compressor/patricia_tree.cpp
  silkworm/db/snapshots/seg/decompressor.cpp
  silkworm/db/snapshots/seg/decompressor.hpp
  silkworm/infra/common/clock_time_test.cpp
  silkworm/node/execution/grpc/client/endpoint/status.cpp
  silkworm/node/execution/grpc/server/endpoint/status.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/gas_price_oracle.cpp
  silkworm/rpc/core/gas_price_oracle_test.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/json/block_test.cpp
  silkworm/rpc/json/transaction.cpp
  silkworm/rpc/json/types_test.cpp
  silkworm/rpc/txpool/miner.cpp
  silkworm/rpc/types/block.cpp
  silkworm/rpc/types/log.cpp
  silkworm/rpc/types/receipt_test.cpp
  silkworm/sentry/rlpx/peer.cpp
  silkworm/sync/internals/priority_queue_test.cpp
Labels: maintenance
