Repository erigontech/silkworm, pull requests merged in 2025-04, with the labels that each got.

#2820 db: add D/II LRU caches in snapshots
  silkworm/capi/silkworm_test.cpp
  silkworm/capi/snapshots.cpp
  silkworm/db/blocks/schema_config.cpp
  silkworm/db/cli/snapshots.cpp
  silkworm/db/datastore/common/entity_name.hpp
  silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
  silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.hpp
  silkworm/db/datastore/snapshots/common/cache.hpp
  silkworm/db/datastore/snapshots/common/key_hasher.cpp
  silkworm/db/datastore/snapshots/common/key_hasher.hpp
  silkworm/db/datastore/snapshots/common/key_hasher_test.cpp
  silkworm/db/datastore/snapshots/domain_cache.hpp
  silkworm/db/datastore/snapshots/domain_get_latest_query.hpp
  silkworm/db/datastore/snapshots/history_get_query.hpp
  silkworm/db/datastore/snapshots/inverted_index_cache.hpp
  silkworm/db/datastore/snapshots/inverted_index_find_by_key_segment_query.hpp
  silkworm/db/datastore/snapshots/inverted_index_seek_query.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.hpp
  silkworm/db/datastore/snapshots/snapshot_repository_ro_access.hpp
  silkworm/db/state/schema_config.cpp
Labels: snapshots, performance, erigon3

#2817 rpcdaemon: improve data access in ots_searchTransactions
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/json/types.cpp
  silkworm/rpc/types/block.hpp
Labels: performance, erigon3

#2822 rpcdaemon: improve data access in eth_feeHistory
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
Labels: performance, erigon3

#2831 cmd: fix ChainConfig lifetime in staged_pipeline dev tool
  cmd/dev/staged_pipeline.cpp
Labels: maintenance

#2832 rpcdaemon: eth_feeHistory error
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api_test.cpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
Labels: json rpc api

#2839 rpc: move cached_chain module into BlockReader
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/cached_chain.cpp
  silkworm/rpc/core/cached_chain.hpp
  silkworm/rpc/core/cached_chain_test.cpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/logs_walker.cpp
Labels: maintenance

#2843 docs: conan
  docs/conan.md
Labels: documentation

#2845 rpcdaemon: erigon_getBalanceChanges avoid block read optimization
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
Labels: json rpc api, performance

#2847 rpcdaemon: load+execute single txn in ots_getContractCreator
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: json rpc api, performance

#2840 rpcdaemon: add caches for single txn receipt and block receipts
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/core/fee_history_oracle.cpp
  silkworm/rpc/core/fee_history_oracle.hpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/receipts.hpp
  silkworm/rpc/core/receipts_cache.hpp
  silkworm/rpc/core/receipts_test.cpp
  silkworm/rpc/ethdb/cbor.cpp
  silkworm/rpc/ethdb/cbor.hpp
  silkworm/rpc/ethdb/cbor_test.cpp
  silkworm/rpc/json/receipt.cpp
  silkworm/rpc/json/receipt.hpp
  silkworm/rpc/types/receipt.hpp
Labels: performance

#2848 core, rpcdaemon: remove std::optional from block cache
  silkworm/core/common/block_cache.hpp
  silkworm/core/common/block_cache_test.cpp
  silkworm/rpc/core/block_reader.cpp
Labels: maintenance

#2852 rpcdaemon: first try with highest gas in eth_estimateGas
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/test_util/mock_estimate_gas_oracle.hpp
Labels: json rpc api

#2851 rpcdaemon: read effective_gas_price from receipt in ots_getBlockDetails
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/receipts.cpp
Labels: json rpc api, performance

#2858 cmd: refactor dev/CMakeLists.txt
  cmake/run_smoke_tests.cmake
  cmd/CMakeLists.txt
  cmd/dev/CMakeLists.txt
  docs/CONTRIBUTING.md
  docs/db_toolbox.md
  docs/dev_tools.md
  silkworm/db/cli/CMakeLists.txt
  silkworm/dev/cli/CMakeLists.txt
  silkworm/node/cli/CMakeLists.txt
  silkworm/rpc/cli/CMakeLists.txt
  silkworm/sentry/cli/CMakeLists.txt
Labels: maintenance

#2855 capi: calculate receipts' properties after each txn
  silkworm/capi/instance.hpp
  silkworm/capi/silkworm.cpp
  silkworm/core/state/state.hpp
  silkworm/execution/domain_state.cpp
  silkworm/execution/domain_state.hpp
Labels: c api, erigon3

#2850 capi: move cmd to cli
  cmd/CMakeLists.txt
  silkworm/capi/CMakeLists.txt
  silkworm/capi/cli/CMakeLists.txt
  silkworm/capi/cli/execute.cpp
  silkworm/capi/cli/main.c
  silkworm/capi/cli/sample-go-client/README.md
  silkworm/capi/cli/sample-go-client/main.go
Labels: c api

#2859 rpcdaemon: optimization on eth_createAccessList
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/core/evm_access_list_tracer.cpp
  silkworm/rpc/core/evm_debug.cpp
Labels: json rpc api, performance

#2860 db: add high level wrappers for inverted indexes put queries
  silkworm/db/state/log_address_inverted_index.hpp
  silkworm/db/state/log_topics_inverted_index.hpp
  silkworm/db/state/traces_from_inverted_index.hpp
  silkworm/db/state/traces_to_inverted_index.hpp
Labels: erigon3

#2867 capi: store log index for address and topics
  silkworm/db/state/log_topics_inverted_index.hpp
  silkworm/execution/domain_state.cpp
  silkworm/execution/domain_state.hpp
Labels: c api, erigon3

#2865 qa-tests: cleanup datadir in Execution Test
  .github/workflows/execution-test.yml
Labels: integration testing

#2869 sync: add check on withdrawals root for bodies from p2p
  silkworm/sync/internals/body_sequence.cpp
  silkworm/sync/internals/body_sequence.hpp
  silkworm/sync/internals/body_sequence_test.cpp
Labels: maintenance

#2870 rpcdaemon: fix and enable auto-flushing in InterfaceLog
  silkworm/rpc/common/interface_log.cpp
  silkworm/rpc/common/interface_log.hpp
  silkworm/rpc/common/interface_log_test.cpp
  silkworm/rpc/json_rpc/request_handler.cpp
Labels: maintenance

#2875 ci: fix clang tidy after PR 2863
  silkworm/rpc/http/chunker.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
Labels: maintenance

#2876 ci: fix Windows build after PR 2874
  silkworm/sync/sync_pos_test.cpp
Labels: maintenance

#2871 rpcdaemon: use zlib for streaming
  .github/actions/perf-common-steps/action.yml
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/http/chunker.hpp
  silkworm/rpc/http/connection.cpp
  silkworm/rpc/http/connection.hpp
  silkworm/rpc/http/zlib_compressor.hpp
Labels: performance

#2877 rpcdaemon: substitute read_block...() with read_header()
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
Labels: performance

#2868 db: increase default mdbx max size
  silkworm/db/datastore/kvdb/mdbx.hpp
Labels: maintenance

#2879 ci: fix debug_traceTransaction pattern in perf tests
  .github/actions/perf-common-steps/action.yml
Labels: maintenance

#2866 infra: raise MaxTasksReachedError in TaskGroup
  silkworm/infra/concurrency/task_group.cpp
  silkworm/infra/concurrency/task_group.hpp
  silkworm/infra/concurrency/task_group_test.cpp
Labels: maintenance

#2864 db: streams hiding pagination in kv::api::Transaction range Data API
  .github/workflows/run_integration_tests.sh
  silkworm/db/datastore/common/ranges/merge_many_view.hpp
  silkworm/db/datastore/common/ranges/merge_many_view_test.cpp
  silkworm/db/datastore/domain_range_as_of_query.hpp
  silkworm/db/datastore/history_range_in_period_query.hpp
  silkworm/db/datastore/inverted_index_range_by_key_query.hpp
  silkworm/db/datastore/kvdb/domain_range_latest_query.hpp
  silkworm/db/datastore/kvdb/history_range_by_keys_query.hpp
  silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
  silkworm/db/datastore/snapshots/history_range_by_keys_query.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence.hpp
  silkworm/db/kv/api/endpoint/paginated_sequence_benchmark.cpp
  silkworm/db/kv/api/endpoint/paginated_sequence_test.cpp
  silkworm/db/kv/api/endpoint/sequence.hpp
  silkworm/db/kv/api/endpoint/temporal_range.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/test_util/dummy_transaction.hpp
Labels: performance, erigon3

#2881 ci: upgrade rpc-tests in perf workflow
  .github/actions/perf-common-steps/action.yml
Labels: maintenance

#2883 datastore: fix out-of-bounds index handling in snapshots BTree
  silkworm/db/datastore/snapshots/btree/btree.cpp
Labels: snapshots, maintenance
