Repository erigontech/silkworm, pull requests merged in 2025-02, with the labels that each got.

#2630 Don't compute hashes of empty requests
  silkworm/core/types/eip_7685_requests.cpp
  silkworm/core/types/eip_7685_requests_test.cpp
Labels: pectra

#2637 Updating contract addresses
  silkworm/core/protocol/param.hpp
Labels: pectra

#2667 Udpate historical block hashes contract address
  silkworm/core/protocol/param.hpp
Labels: pectra

#2688 cmd: move check commands in cli packages
  cmd/dev/CMakeLists.txt
  cmd/dev/check_pow.cpp
  silkworm/db/cli/check_blockhashes.cpp
  silkworm/db/cli/check_changes.cpp
  silkworm/db/cli/check_hashstate.cpp
  silkworm/db/cli/check_log_indices.cpp
  silkworm/db/cli/check_senders.cpp
  silkworm/db/cli/check_tx_lookup.cpp
  silkworm/node/cli/backend_kv_server.cpp
Labels: maintenance

#2691 rpcdaemon: fix eth_getStorageAt index must have hash length
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance

#2692 rpcdaemon: fix state change KV client
  silkworm/rpc/daemon.cpp
  silkworm/rpc/daemon.hpp
Labels: maintenance, erigon3

#2693 rpcdaemon: remove totalDifficulty from eth_getBlockByNumber/eth_getBlockByHash
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/json/block.cpp
  silkworm/rpc/types/block.hpp
Labels: maintenance

#2695 rpcdaemon: eth_createAccessList optimise_gas set default as false
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance, json rpc api

#2687 evm: enable evmone APIv2 in block executor
  silkworm/core/execution/processor.hpp
  silkworm/node/execution/block/block_executor.cpp
Labels: evmone apiv2

#2696 rpcdaemon: remove double validation from processor and executor
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/core/protocol/validation.cpp
  silkworm/core/protocol/validation.hpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_executor_test.cpp
Labels: maintenance

#2683 capi: add state snapshot
  cmd/capi/execute.cpp
  docs/code_style.md
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
  silkworm/capi/snapshots.cpp
  silkworm/db/datastore/snapshots/btree/btree_index.cpp
  silkworm/db/datastore/snapshots/btree/btree_index.hpp
  silkworm/db/datastore/snapshots/schema.hpp
  silkworm/db/test_util/temp_snapshots.hpp
Labels: c api, erigon3

#2702 ci: fix gcc12 build after PR 2698
  silkworm/db/datastore/common/caching_view.hpp
Labels: maintenance

#2705 ci: fix Windows build after PR 2698
  silkworm/db/datastore/kvdb/cursor_iterator.hpp
Labels: maintenance

#2706 db: split latest and historical snapshots repos
  cmd/capi/execute.cpp
  silkworm/capi/fork_validator.cpp
  silkworm/capi/instance.hpp
  silkworm/capi/rpcdaemon.cpp
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm.h
  silkworm/capi/silkworm_test.cpp
  silkworm/capi/snapshots.cpp
  silkworm/db/data_store.cpp
  silkworm/db/data_store.hpp
  silkworm/db/datastore/domain_get_as_of_query.hpp
  silkworm/db/datastore/snapshots/domain.hpp
  silkworm/db/datastore/snapshots/history_get_query.hpp
  silkworm/db/datastore/snapshots/schema.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.cpp
  silkworm/db/datastore/snapshots/snapshot_bundle.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/state/schema_config.cpp
  silkworm/db/state/schema_config.hpp
  silkworm/db/test_util/temp_snapshots.hpp
  silkworm/execution/domain_state.hpp
  silkworm/execution/domain_state_test.cpp
  silkworm/execution/local_state.cpp
  silkworm/execution/local_state.hpp
Labels: snapshots, erigon3

#2711 datastore: canonical hash by number in snapshots
  silkworm/db/access_layer.cpp
Labels: snapshots, erigon3

#2713 datastore: implement LocalTransaction::first_txn_num_in_block
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/blocks/bodies/body_queries.hpp
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
Labels: snapshots, erigon3

#2708 snapshots: extend max encoded integer sequence length
  silkworm/db/datastore/snapshots/common/encoding/sequence.hpp
Labels: snapshots, erigon3

#2715 datastore: fix state storage format
  silkworm/db/state/storage_codecs.hpp
  silkworm/db/state/storage_domain.hpp
  silkworm/db/state/storage_domain_test.cpp
Labels: maintenance, erigon3

#2716 rpcdaemon: debug_getRawTransaction fix for block not found
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/debug_api.cpp
Labels: maintenance, json rpc api

#2718 db: fix SnapshotRepository reopen
  silkworm/capi/silkworm_test.cpp
  silkworm/capi/snapshots.cpp
  silkworm/db/datastore/snapshots/schema.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/state/schema_config.cpp
  silkworm/db/tables.hpp
Labels: snapshots, erigon3

#2721 rpcdaemon: net_listening use peers
  silkworm/rpc/commands/net_api.cpp
Labels: maintenance, json rpc api

#2722 rpcdaemon: reset EVM executor running debug_traceBlockBy*
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_debug.cpp
Labels: maintenance

#2717 db: cleanup DomainState unit tests
  silkworm/execution/domain_state_test.cpp
Labels: maintenance, erigon3

#2724 capi: flush state after executing a single txn
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/execution/domain_state.cpp
Labels: c api, erigon3

#2723 rpcdaemon: add state overrides on eth_call
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
Labels: enhancement, json rpc api

#2729 ci: fix Windows build after new grpc/1.67.1 recipe revision
  conanfile.py
Labels: maintenance

#2727 db: handle canonical chain in kvdb+snapshots
  silkworm/db/access_layer.cpp
Labels: erigon3

#2728 db: fix account codec for self-destructed
  silkworm/db/state/account_codec.hpp
  silkworm/db/state/account_codec_test.cpp
  silkworm/db/state/account_codecs.hpp
  silkworm/db/state/account_codecs_test.cpp
  silkworm/execution/local_state.cpp
Labels: erigon3

#2731 datastore: history range query 2
  silkworm/db/datastore/history_range_query.hpp
  silkworm/db/datastore/kvdb/history_range_query.hpp
  silkworm/db/datastore/merge_view.hpp
  silkworm/db/datastore/merge_view_test.cpp
  silkworm/db/datastore/snapshots/history.hpp
  silkworm/db/datastore/snapshots/history_queries.hpp
  silkworm/db/datastore/snapshots/history_range_query.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.cpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
  silkworm/db/datastore/snapshots/segment/segment_reader.cpp
  silkworm/db/datastore/snapshots/segment/segment_reader.hpp
  silkworm/db/kv/api/local_transaction.cpp
Labels: snapshots, erigon3

#2732 rpcdaemon: canonical body provider from chain storage
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/chain/chain_storage.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/local_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
  silkworm/db/test_util/mock_chain_storage.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/logs_walker.hpp
Labels: erigon3

#2733 db: read transaction by idx in block in local storage
  silkworm/db/chain/chain_storage.hpp
  silkworm/db/chain/local_chain_storage.cpp
  silkworm/db/chain/local_chain_storage.hpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/chain/remote_chain_storage.hpp
Labels: erigon3

#2730 rpcdaemon: fix gas cost for REVERT opcode in debug API
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_debug.cpp
Labels: maintenance

#2734 db: complete Data API LocalTransaction::index_range
  silkworm/db/kv/api/local_transaction.cpp
Labels: erigon3

#2735 rpcdaemon: fix data race in json_rpc::Validator patterns
  silkworm/rpc/json_rpc/validator.cpp
Labels: maintenance

#2738 rpcdaemon: fix open kvdb as readonly
  silkworm/rpc/daemon.cpp
Labels: maintenance

#2739 snapshots: avoid EliasFanoList32 copy in InvertedIndexSeekSegmentQuery
  silkworm/db/datastore/snapshots/inverted_index_seek_query.hpp
Labels: snapshots, performance, erigon3

#2742 db: fix BlockNum & TxnId overflow in StepRange
  silkworm/core/common/base.hpp
  silkworm/db/datastore/common/step.hpp
  silkworm/db/datastore/common/step_test.cpp
  silkworm/db/datastore/kvdb/domain_get_latest_query.hpp
Labels: maintenance, erigon3

#2743 rpcdaemon: fix canonical body provider in ots API
  silkworm/db/chain/providers.hpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/core/logs_walker.hpp
Labels: maintenance, erigon3

#2744 db: Data API history_range in LocalTransaction
  silkworm/db/kv/api/local_transaction.cpp
Labels: erigon3, temporal kv

#2746 db: Data API history_seek in LocalTransaction
  silkworm/db/kv/api/local_transaction.cpp
  silkworm/db/kv/api/local_transaction.hpp
Labels: erigon3, temporal kv

#2750 db: Data API timestamp conversion
  silkworm/db/datastore/common/timestamp.hpp
  silkworm/db/kv/api/as_datastore_ts_range.cpp
  silkworm/db/kv/api/as_datastore_ts_range.hpp
  silkworm/db/kv/api/as_datastore_ts_range_test.cpp
  silkworm/db/kv/api/endpoint/temporal_range.hpp
  silkworm/db/kv/api/local_transaction.cpp
Labels: erigon3, temporal kv

#2751 db: fix BloomFilter path lifecycle for operator>>
  silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
Labels: maintenance, erigon3

#2752 db: fix std::basic_string::compare result in snapshot BTree
  silkworm/db/datastore/snapshots/btree/btree.cpp
Labels: snapshots, maintenance, erigon3

#2753 db: improve performance of InvertedIndexFindByKeySegmentQuery
  silkworm/db/blocks/bodies/body_segment.hpp
  silkworm/db/blocks/headers/header_segment.hpp
  silkworm/db/blocks/transactions/txn_segment_word_codec.hpp
  silkworm/db/datastore/snapshots/btree/btree_index_test.cpp
  silkworm/db/datastore/snapshots/common/codec.hpp
  silkworm/db/datastore/snapshots/common/raw_codec.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder_test.cpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.cpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list_test.cpp
  silkworm/db/datastore/snapshots/rec_split/rec_split.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_par.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_seq.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_test.cpp
  silkworm/db/datastore/snapshots/test_util/string_codec.hpp
  silkworm/db/state/account_codecs.hpp
  silkworm/db/state/account_codecs_test.cpp
  silkworm/db/state/address_codecs.hpp
  silkworm/db/state/address_codecs_test.cpp
  silkworm/db/state/hash_decoder.hpp
  silkworm/db/state/hash_decoder_test.cpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/db/state/receipts_domain_test.cpp
  silkworm/db/state/storage_codecs.cpp
  silkworm/db/state/storage_codecs.hpp
  silkworm/db/state/storage_domain_test.cpp
Labels: snapshots, performance, erigon3

#2757 datastore: reduce transform copies
  silkworm/db/datastore/common/ranges/merge_unique_many_view.hpp
  silkworm/db/datastore/common/ranges/merge_unique_many_view_test.cpp
  silkworm/db/datastore/domain_range_latest_query.hpp
  silkworm/db/datastore/kvdb/domain_range_latest_query.hpp
  silkworm/db/datastore/kvdb/history_range_query.hpp
  silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
  silkworm/db/datastore/snapshots/history_range_query.hpp
  silkworm/db/kv/api/local_transaction.cpp
Labels: erigon3, temporal kv
