Repository erigontech/silkworm, pull requests merged in 2025-01, with the labels that each got.

#2625 snapshots: queries refactoring
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/blocks/bodies/body_queries.hpp
  silkworm/db/blocks/bodies/body_txs_amount_query.cpp
  silkworm/db/blocks/bodies/body_txs_amount_query.hpp
  silkworm/db/blocks/bodies/body_txs_amount_query_test.cpp
  silkworm/db/blocks/headers/header_queries.hpp
  silkworm/db/blocks/schema_config.hpp
  silkworm/db/blocks/transactions/txn_index.cpp
  silkworm/db/blocks/transactions/txn_queries.hpp
  silkworm/db/blocks/transactions/txn_to_block_index.cpp
  silkworm/db/blocks/transactions/txn_to_block_index.hpp
  silkworm/db/blocks/transactions/txs_and_bodies_query.cpp
  silkworm/db/blocks/transactions/txs_and_bodies_query.hpp
  silkworm/db/cli/snapshots.cpp
  silkworm/db/datastore/snapshots/basic_queries.hpp
  silkworm/db/datastore/snapshots/common/util/iterator/map_values_view.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder_test.cpp
  silkworm/db/datastore/snapshots/index_builders_factory.hpp
  silkworm/db/datastore/snapshots/rec_split/accessor_index.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split.hpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_par_test.cpp
  silkworm/db/datastore/snapshots/rec_split/rec_split_seq_test.cpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
  silkworm/db/datastore/snapshots/segment_and_accessor_index.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.hpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/datastore/snapshots/snapshot_repository.hpp
  silkworm/db/datastore/snapshots/snapshot_repository_ro_access.hpp
  silkworm/db/freezer.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_test.cpp
Labels: snapshots, erigon3

#2638 docs: update README to include files under LGPL
  README.md
Labels: documentation

#2636 rpcdaemon: replace UnaryRpc with rpc::unary_rpc
  cmd/dev/grpc_toolbox.cpp
  examples/get_latest_block.cpp
  silkworm/infra/grpc/client/unary_rpc.hpp
  silkworm/rpc/commands/net_api_test.cpp
  silkworm/rpc/commands/trace_api.hpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/ethbackend/remote_backend.cpp
  silkworm/rpc/ethbackend/remote_backend.hpp
  silkworm/rpc/ethbackend/remote_backend_test.cpp
  silkworm/rpc/test_util/api_test_base.hpp
  silkworm/rpc/test_util/service_context_test_base.cpp
  silkworm/rpc/txpool/miner.cpp
  silkworm/rpc/txpool/miner.hpp
  silkworm/rpc/txpool/miner_test.cpp
  silkworm/rpc/txpool/transaction_pool.cpp
  silkworm/rpc/txpool/transaction_pool.hpp
  silkworm/rpc/txpool/transaction_pool_test.cpp
Labels: maintenance

#2640 rpcdaemon: replace Database hierarchy with KV Service
  cmake/conan.cmake
  examples/get_latest_block.cpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/debug_api.hpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/commands/engine_api.cpp
  silkworm/rpc/commands/engine_api.hpp
  silkworm/rpc/commands/engine_api_test.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/erigon_api.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/eth_api.hpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/parity_api.hpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/commands/trace_api.hpp
  silkworm/rpc/commands/txpool_api.hpp
  silkworm/rpc/commands/web3_api.hpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/daemon.hpp
  silkworm/rpc/ethdb/database.hpp
  silkworm/rpc/ethdb/file/local_database.cpp
  silkworm/rpc/ethdb/file/local_database.hpp
  silkworm/rpc/ethdb/kv/remote_database.cpp
  silkworm/rpc/ethdb/kv/remote_database.hpp
  silkworm/rpc/ethdb/kv/remote_database_test.cpp
  silkworm/rpc/test_util/api_test_database.hpp
  silkworm/rpc/test_util/dummy_client.hpp
  silkworm/rpc/test_util/dummy_database.hpp
  silkworm/rpc/test_util/mock_database.hpp
  silkworm/rpc/test_util/service_context_test_base.cpp
  tests/docker/README.md
Labels: maintenance

#2642 ci: fix Windows/Sanitizer/WASM build after PR 2607
  cmake/conan.cmake
  cmake/profiles/wasi_release
  silkworm/db/datastore/snapshots/common/util/iterator/map_values_view.hpp
Labels: maintenance

#2641 rpcdaemon: fix and improve perf in trace_filter
  silkworm/rpc/core/evm_trace.cpp
Labels: enhancement, json rpc api

#2646 rpcdaemon: remove useless Catch2 expectations
  silkworm/db/kv/state_reader_test.cpp
  silkworm/execution/remote_state_test.cpp
Labels: maintenance

#2647 node: handle STOP_AT_BLOCK in Execution stage
  silkworm/node/stagedsync/stages/stage_execution.cpp
  silkworm/node/stagedsync/stages/stage_hashstate.cpp
  silkworm/node/stagedsync/stages/stage_interhashes.cpp
Labels: maintenance

#2650 cmd: fix bisect command in staged_pipeline utility
  cmd/dev/staged_pipeline.cpp
Labels: maintenance

#2648 db, node, sentry, sync: more exception handlers
  silkworm/db/snapshot_sync.cpp
  silkworm/node/node.cpp
  silkworm/sentry/discovery/disc_v4/discovery.cpp
  silkworm/sentry/message_receiver.cpp
  silkworm/sentry/peer_manager.cpp
  silkworm/sentry/sentry.cpp
  silkworm/sync/sentry_client.cpp
  silkworm/sync/sync_pos.cpp
Labels: maintenance

#2651 cmd: add table_get command in db_toolbox utility
  cmd/dev/db_toolbox.cpp
Labels: enhancement

#2653 evm: de-duplicate bailout flag
  silkworm/core/execution/processor.cpp
  silkworm/core/execution/processor.hpp
  silkworm/rpc/core/evm_executor.cpp
Labels: maintenance

#2655 CI: add conan.cmake to the cache killer key
  .circleci/config.yml
Labels: maintenance

#2654 CI - gcc 11 on PR workflow
  .circleci/config.yml
Labels: maintenance

#2660 ci: fix Windows build after PR 2632
  silkworm/core/rlp/decode_test.cpp
  silkworm/db/datastore/concat_view.hpp
  silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
  silkworm/db/datastore/snapshots/bittorrent/torrent_file.cpp
  silkworm/db/datastore/snapshots/elias_fano/list_iterator.hpp
  silkworm/infra/concurrency/task_group_test.cpp
  silkworm/infra/concurrency/timeout_test.cpp
  silkworm/infra/grpc/server/server_context_pool.cpp
  silkworm/interfaces/CMakeLists.txt
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/sentry/discovery/node_db/node_db_sqlite_test.cpp
  silkworm/sentry/message_receiver.cpp
  silkworm/sentry/rlpx/crypto/hmac.cpp
Labels: maintenance

#2633 rpcdaemon: fixes for parallel RPC integration tests
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/execution/remote_state.cpp
  silkworm/execution/remote_state.hpp
  silkworm/infra/grpc/client/call.hpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/daemon.cpp
Labels: maintenance, integration testing

#2662 ci: fix clang tidy after PR 2660
  silkworm/core/protocol/bor/config.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/blocks/schema_config.cpp
  silkworm/db/chain/remote_chain_storage.cpp
  silkworm/db/datastore/concat_view.hpp
  silkworm/db/datastore/domain_get_latest_query.hpp
  silkworm/db/datastore/inverted_index_range_by_key_query.hpp
  silkworm/db/datastore/kvdb/cursor_iterator.hpp
  silkworm/db/datastore/kvdb/database.hpp
  silkworm/db/datastore/kvdb/domain_get_latest_query.hpp
  silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
  silkworm/db/datastore/kvdb/kvts_codec.hpp
  silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
  silkworm/db/datastore/snapshots/domain_get_latest_query.hpp
  silkworm/db/datastore/snapshots/elias_fano/double_elias_fano_list.hpp
  silkworm/db/datastore/snapshots/inverted_index_range_by_key_query.hpp
  silkworm/db/datastore/snapshots/snapshot_bundle.hpp
  silkworm/db/datastore/snapshots/snapshot_repository.cpp
  silkworm/db/state/account_codec.cpp
  silkworm/db/state/account_codecs.hpp
  silkworm/db/state/code_domain.hpp
  silkworm/db/state/schema_config.cpp
  silkworm/execution/local_state.cpp
  silkworm/rpc/commands/debug_api_test.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/logs_walker.cpp
Labels: maintenance

#2663 rpcdaemon: support state reader on latest
  silkworm/db/kv/state_reader.cpp
  silkworm/db/kv/state_reader.hpp
  silkworm/rpc/commands/eth_api.cpp
Labels: enhancement, erigon3

#2664 rpcdaemon: fix stack data access in TraceTracer
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2666 db, rpcdaemon: refactor user_txn_id_at
  silkworm/db/kv/api/transaction.hpp
  silkworm/execution/state_factory.hpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/receipts.cpp
Labels: maintenance

#2659 rpcdaemon: debug_traceCall with txIndex
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
Labels: enhancement, json rpc api

#2583 clang-tidy: enforce parameter case
  .clang-tidy
  silkworm/db/datastore/snapshots/rec_split/rec_split_seq.hpp
  silkworm/db/datastore/snapshots/segment/seg/compressor/pattern_covering_test.cpp
  silkworm/infra/common/ensure.hpp
  silkworm/node/stagedsync/forks/fork.cpp
  silkworm/node/stagedsync/forks/fork.hpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/ots_api.hpp
  silkworm/rpc/commands/rpc_api_test.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/engine/execution_engine.hpp
  silkworm/rpc/engine/remote_execution_engine.cpp
  silkworm/rpc/engine/remote_execution_engine.hpp
  silkworm/sync/internals/chain_elements.hpp
  silkworm/sync/internals/header_chain.cpp
  silkworm/sync/sync_pos.cpp
  silkworm/sync/sync_pos.hpp
Labels: maintenance

#2671 rpcdaemon: enable some debug_traceBlockBy* skipped tests
  .github/workflows/run_integration_tests.sh
Labels: integration testing

#2672 rpcdaemon: rebuild receipt only for selected transactions
  .github/workflows/run_integration_tests.sh
  silkworm/db/kv/txn_num.cpp
  silkworm/db/kv/txn_num.hpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/logs_walker.cpp
  silkworm/rpc/core/receipts.cpp
  silkworm/rpc/core/receipts.hpp
Labels: json rpc api, performance

#2661 datastore: improve domain get and put queries
  .clang-tidy
  silkworm/db/cli/snapshots.cpp
  silkworm/db/datastore/kvdb/cursor_iterator.hpp
  silkworm/db/datastore/kvdb/domain_delete_query.hpp
  silkworm/db/datastore/kvdb/domain_put_latest_query.hpp
  silkworm/db/datastore/kvdb/domain_put_latest_query_test.cpp
  silkworm/db/datastore/kvdb/domain_put_query.hpp
  silkworm/db/datastore/kvdb/inverted_index_range_by_key_query_test.cpp
  silkworm/db/datastore/snapshots/bloom_filter/bloom_filter.cpp
  silkworm/db/state/account_codecs.hpp
  silkworm/db/state/accounts_domain.hpp
  silkworm/db/state/code_domain.hpp
  silkworm/db/state/commitment_domain.hpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/db/state/storage_domain.hpp
  silkworm/execution/local_state.cpp
Labels: erigon3

#2677 db: clang-tidy fixes
  .clang-tidy
  silkworm/db/datastore/kvdb/domain_put_latest_query_test.cpp
  silkworm/db/state/accounts_domain.hpp
  silkworm/db/state/code_domain.hpp
  silkworm/db/state/commitment_domain.hpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/db/state/storage_domain.hpp
  silkworm/rpc/core/receipts.cpp
Labels: maintenance

#2675 rpcdaemon: StateReader's txn_id must be nullopt in case of latest block
  .github/workflows/rpc-integration-tests.yml
  silkworm/db/kv/grpc/client/endpoint/temporal_point.cpp
  silkworm/db/kv/state_reader.cpp
  silkworm/execution/local_state.cpp
  silkworm/execution/local_state.hpp
  silkworm/execution/remote_state.hpp
  silkworm/execution/state_factory.cpp
  silkworm/execution/state_factory.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/call_many.hpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
Labels: enhancement, json rpc api

#2681 execution: use read-only tx in LocalState
  silkworm/execution/local_state.cpp
  silkworm/execution/local_state.hpp
Labels: maintenance

#2649 rpcdaemon: fix invalid data access for CREATE2 in trace_filter
  .github/workflows/run_integration_tests.sh
  silkworm/rpc/core/evm_trace.cpp
Labels: maintenance

#2684 integration tests: update exception list for E3 beta1
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
Labels: integration testing, erigon3

#2686 execution: use domain GetAsOf queries in LocalState
  silkworm/db/datastore/snapshots/history_get_query.hpp
  silkworm/execution/local_state.cpp
  silkworm/execution/local_state.hpp
Labels: erigon3
