Repository erigontech/silkworm, pull requests merged in 2025-03, with the labels that each got.

#2766 ci: fix Clang ASAN and Windows build after PR 2753
  conanfile.py
  silkworm/db/datastore/common/ranges/merge_unique_many_view_test.cpp
  silkworm/db/snapshot_repository_test.cpp
  silkworm/db/snapshot_test.cpp
Labels: maintenance

#2767 ci: RPC integration tests on local E3 datastore
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
  .github/workflows/start_integration_rpcdaemon.sh
Labels: integration testing, erigon3

#2760 db: improve performance of Decompressor::Iterator
  silkworm/core/common/bytes.hpp
  silkworm/db/blocks/bodies/body_segment.hpp
  silkworm/db/blocks/headers/header_segment.hpp
  silkworm/db/blocks/transactions/txn_segment.hpp
  silkworm/db/blocks/transactions/txn_segment_word_codec.hpp
  silkworm/db/cli/snapshots.cpp
  silkworm/db/datastore/domain_range_latest_query.hpp
  silkworm/db/datastore/kvdb/raw_codec.hpp
  silkworm/db/datastore/snapshots/common/codec.hpp
  silkworm/db/datastore/snapshots/common/raw_codec.hpp
  silkworm/db/datastore/snapshots/domain_get_latest_query.hpp
  silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_decoder_test.cpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.cpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.hpp
  silkworm/db/datastore/snapshots/history_range_query.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.cpp
  silkworm/db/datastore/snapshots/segment/kv_segment_test.cpp
  silkworm/db/datastore/snapshots/segment/seg/decompressor.cpp
  silkworm/db/datastore/snapshots/segment/seg/decompressor.hpp
  silkworm/db/datastore/snapshots/test_util/string_codec.hpp
  silkworm/db/snapshot_decompressor_test.cpp
  silkworm/db/snapshot_test.cpp
  silkworm/db/state/account_codecs.hpp
  silkworm/db/state/account_codecs_test.cpp
  silkworm/db/state/address_codecs.hpp
  silkworm/db/state/address_codecs_test.cpp
  silkworm/db/state/hash_decoder.hpp
  silkworm/db/state/hash_decoder_test.cpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/db/state/receipts_domain_test.cpp
  silkworm/db/state/storage_codecs.cpp
  silkworm/db/state/storage_codecs.hpp
  silkworm/db/state/storage_domain_test.cpp
  silkworm/rpc/core/receipts.cpp
Labels: performance, erigon3

#2774 rpcdaemon: fix storage location as quantity in eth_getStorageAt
  .github/workflows/rpc-integration-tests.yml
  silkworm/rpc/commands/eth_api.cpp
Labels: maintenance

#2775 ci: fix Windows build after PR 2760
  silkworm/db/snapshot_test.cpp
Labels: maintenance

#2771 datastore: fix debug_getModifiedAccountsBy regression
  silkworm/db/datastore/common/ranges/caching_view.hpp
  silkworm/db/datastore/common/ranges/merge_many_view.hpp
  silkworm/db/datastore/common/ranges/vector_from_range.hpp
  silkworm/db/datastore/snapshots/history_range_in_period_query.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_test.cpp
  silkworm/db/datastore/snapshots/segment/segment_reader.hpp
  silkworm/db/datastore/snapshots/segment/segment_test.cpp
Labels: maintenance

#2773 ci: enable RPC performance tests on local E3 datastore
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing

#2780 ci: fix perf light workflow
  .github/actions/perf-common-steps/action.yml
  .github/workflows/rpc-performance-tests-light.yml
  .github/workflows/rpc-performance-tests.yml
Labels: perf testing

#2781 integration tests: update exception list after PR 2771
  .github/workflows/rpc-integration-tests.yml
  .github/workflows/run_integration_tests.sh
Labels: integration testing

#2784 ci: fix input for perf tests HDR analysis
  .github/actions/perf-common-steps/action.yml
Labels: perf testing

#2789 db: KV state cache over Data API
  silkworm/db/kv/api/base_transaction.cpp
  silkworm/db/kv/api/state_cache.cpp
  silkworm/db/kv/api/state_cache.hpp
  silkworm/db/kv/api/state_cache_test.cpp
  silkworm/db/util.hpp
Labels: erigon3, temporal kv

#2785 ci: fix typo in input for perf tests HDR analysis
  .github/actions/perf-common-steps/action.yml
Labels: perf testing

#2796 db: more fix std::basic_string::compare result in snapshot BTree
  silkworm/db/datastore/snapshots/btree/btree.cpp
Labels: snapshots, maintenance, erigon3

#2801 datastore: fix and optimize timestamp_range_filter
  silkworm/db/datastore/common/timestamp.hpp
  silkworm/db/datastore/snapshots/elias_fano/elias_fano_list.hpp
  silkworm/db/datastore/snapshots/inverted_index_find_by_key_segment_query.hpp
Labels: maintenance, erigon3

#2792 rpcdaemon: implement erigon_cacheCheck
  .github/workflows/rpc-integration-tests.yml
  docs/JSON-RPC-API.md
  silkworm/db/kv/api/state_cache.cpp
  silkworm/db/kv/api/state_cache.hpp
  silkworm/db/test_util/mock_state_cache.hpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/json/cache_validation_result.cpp
  silkworm/rpc/json/cache_validation_result.hpp
  silkworm/rpc/types/cache_validation_result.hpp
Labels: json rpc api

#2800 EIP-6110 Deposit contract fix
  silkworm/core/types/eip_7685_requests.cpp
  silkworm/core/types/eip_7685_requests_test.cpp
Labels: pectra

#2782 capi: Update Silkworm single txn execution
  silkworm/capi/silkworm.cpp
  silkworm/capi/silkworm_test.cpp
  silkworm/core/chain/config.cpp
  silkworm/core/chain/genesis_holesky.cpp
  silkworm/core/chain/genesis_holesky.json
  silkworm/core/chain/genesis_sepolia.cpp
  silkworm/core/chain/genesis_sepolia.json
  silkworm/db/datastore/snapshot_merger.cpp
  silkworm/db/state/code_domain.hpp
  silkworm/db/state/storage_domain.hpp
  silkworm/execution/domain_state.cpp
  silkworm/execution/domain_state.hpp
  silkworm/sentry/eth/fork_id_test.cpp
Labels: c api, erigon3

#2787 rpcdaemon: align eth_estimateGas implementation to erigon
  silkworm/core/execution/evm.cpp
  silkworm/core/execution/evm.hpp
  silkworm/core/execution/evm_test.cpp
  silkworm/core/execution/processor.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle.hpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_executor.cpp
  silkworm/rpc/core/evm_executor.hpp
Labels: maintenance, json rpc api

#2806 db: KV state cache in api::Transaction
  cmd/dev/grpc_toolbox.cpp
  examples/get_latest_block.cpp
  silkworm/db/kv/api/base_transaction.hpp
  silkworm/db/kv/api/direct_service.cpp
  silkworm/db/kv/api/direct_service.hpp
  silkworm/db/kv/api/direct_service_test.cpp
  silkworm/db/kv/api/local_transaction.hpp
  silkworm/db/kv/api/transaction.hpp
  silkworm/db/kv/grpc/client/remote_client.cpp
  silkworm/db/kv/grpc/client/remote_client.hpp
  silkworm/db/kv/grpc/client/remote_client_test.cpp
  silkworm/db/kv/grpc/client/remote_transaction.cpp
  silkworm/db/kv/grpc/client/remote_transaction.hpp
  silkworm/db/kv/grpc/client/remote_transaction_test.cpp
  silkworm/db/kv/state_changes_stream_test.cpp
  silkworm/db/kv/state_reader.cpp
  silkworm/db/kv/state_reader.hpp
  silkworm/db/kv/state_reader_test.cpp
  silkworm/db/test_util/mock_transaction.hpp
  silkworm/execution/remote_state.hpp
  silkworm/execution/remote_state_test.cpp
  silkworm/execution/state_factory.cpp
  silkworm/execution/state_factory.hpp
  silkworm/rpc/commands/debug_api.cpp
  silkworm/rpc/commands/erigon_api.cpp
  silkworm/rpc/commands/eth_api.cpp
  silkworm/rpc/commands/ots_api.cpp
  silkworm/rpc/commands/parity_api.cpp
  silkworm/rpc/commands/trace_api.cpp
  silkworm/rpc/core/account_dumper.cpp
  silkworm/rpc/core/account_dumper.hpp
  silkworm/rpc/core/account_dumper_test.cpp
  silkworm/rpc/core/block_reader.cpp
  silkworm/rpc/core/block_reader.hpp
  silkworm/rpc/core/block_reader_test.cpp
  silkworm/rpc/core/cached_chain.cpp
  silkworm/rpc/core/cached_chain.hpp
  silkworm/rpc/core/call_many.cpp
  silkworm/rpc/core/call_many.hpp
  silkworm/rpc/core/estimate_gas_oracle.cpp
  silkworm/rpc/core/estimate_gas_oracle_test.cpp
  silkworm/rpc/core/evm_debug.cpp
  silkworm/rpc/core/evm_debug.hpp
  silkworm/rpc/core/evm_debug_test.cpp
  silkworm/rpc/core/evm_executor_test.cpp
  silkworm/rpc/core/evm_trace.cpp
  silkworm/rpc/core/evm_trace.hpp
  silkworm/rpc/core/evm_trace_test.cpp
  silkworm/rpc/core/logs_walker.hpp
  silkworm/rpc/core/storage_walker_test.cpp
  silkworm/rpc/daemon.cpp
  silkworm/rpc/test_util/api_test_database.hpp
  silkworm/rpc/test_util/dummy_transaction.hpp
  silkworm/rpc/test_util/service_context_test_base.cpp
Labels: maintenance

#2811 rpcdaemon: read header only instead of full block in LogsWalker
  silkworm/rpc/core/logs_walker.cpp
Labels: performance, erigon3

#2812 rpcdaemon: read_transaction_by_idx_in_block() read single txn
  silkworm/db/access_layer.cpp
  silkworm/db/access_layer.hpp
  silkworm/db/chain/local_chain_storage.cpp
Labels: performance

#2810 snapshots: optimize access pattern in BTree index
  silkworm/db/datastore/snapshots/btree/btree.cpp
  silkworm/db/datastore/snapshots/btree/btree.hpp
  silkworm/db/datastore/snapshots/btree/btree_index.cpp
  silkworm/db/datastore/snapshots/btree/btree_index.hpp
  silkworm/db/datastore/snapshots/btree/btree_index_test.cpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.cpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
Labels: performance, erigon3

#2813 snapshots: fewer copies in BTree index using BytesOrByteView
  silkworm/db/datastore/snapshots/btree/btree.cpp
  silkworm/db/datastore/snapshots/btree/btree.hpp
  silkworm/db/datastore/snapshots/btree/btree_index.cpp
  silkworm/db/datastore/snapshots/btree/btree_index.hpp
  silkworm/db/datastore/snapshots/btree/btree_index_test.cpp
  silkworm/db/datastore/snapshots/common/raw_codec.hpp
  silkworm/db/datastore/snapshots/domain_get_latest_query.hpp
  silkworm/db/datastore/snapshots/domain_range_latest_query.hpp
  silkworm/db/datastore/snapshots/segment/kv_segment_reader.hpp
Labels: performance, erigon3

#2816 rpcdaemon: fix key used while querying cumulative gas used for receipt
  silkworm/rpc/core/receipts.cpp
Labels: maintenance, erigon3

#2818 capi: single individual txn receipts into database
  silkworm/capi/silkworm.cpp
  silkworm/core/state/state.hpp
  silkworm/db/state/receipts_domain.hpp
  silkworm/execution/domain_state.cpp
  silkworm/execution/domain_state.hpp
Labels: c api, erigon3
